/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Particles.BeyondTheStandardModel.TwoHDM.GramMatrix
/-!
# A polynomial family of orbit representatives for the two Higgs doublet model

Every gauge orbit of the two Higgs doublet model meets the four–real–parameter family

`repHiggs X = ⟨(X₀, 0), (X₁ + i X₂, X₃)⟩`.

The crucial feature of this family (compared with the normalised representatives of
`gaugeGroupI_exists_fst_eq_snd_eq`) is that it is a *polynomial* family: the Gram vector of
`repHiggs X` is a polynomial in `X`, with no square roots. Consequently the value of a gauge
invariant potential on any field configuration is `V (repHiggs X)` for a suitable `X`, and the
question of whether `V` is a polynomial in the Gram vector reduces to the purely algebraic question
of whether `V ∘ repHiggs` lies in the subring generated by the (polynomial) Gram components of the
representative family.

-/

@[expose] public section

noncomputable section

namespace TwoHiggsDoublet

open InnerProductSpace
open StandardModel
open ComplexConjugate

/-- A four–real–parameter polynomial family of representatives for the gauge orbits: the first
  doublet is `(X₀, 0)` and the second is `(X₁ + i X₂, X₃)`. -/
def repHiggs (X : Fin 4 → ℝ) : TwoHiggsDoublet where
  Φ1 := !₂[(X 0 : ℂ), 0]
  Φ2 := !₂[(X 1 : ℂ) + Complex.I * (X 2 : ℂ), (X 3 : ℂ)]

@[simp]
lemma repHiggs_Φ1 (X : Fin 4 → ℝ) : (repHiggs X).Φ1 = !₂[(X 0 : ℂ), 0] := rfl

@[simp]
lemma repHiggs_Φ2 (X : Fin 4 → ℝ) :
    (repHiggs X).Φ2 = !₂[(X 1 : ℂ) + Complex.I * (X 2 : ℂ), (X 3 : ℂ)] := rfl

lemma normSq_repHiggs_Φ1 (X : Fin 4 → ℝ) : ‖(repHiggs X).Φ1‖ ^ 2 = X 0 ^ 2 := by
  rw [repHiggs_Φ1, PiLp.norm_sq_eq_of_L2, Fin.sum_univ_two]
  simp [Complex.norm_real, Real.norm_eq_abs, sq_abs]

lemma normSq_repHiggs_Φ2 (X : Fin 4 → ℝ) :
    ‖(repHiggs X).Φ2‖ ^ 2 = X 1 ^ 2 + X 2 ^ 2 + X 3 ^ 2 := by
  rw [repHiggs_Φ2, PiLp.norm_sq_eq_of_L2, Fin.sum_univ_two]
  rw [← Complex.normSq_eq_norm_sq, ← Complex.normSq_eq_norm_sq]
  simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Complex.normSq_apply,
    Complex.add_re, Complex.add_im, Complex.ofReal_re, Complex.ofReal_im, Complex.mul_re,
    Complex.mul_im, Complex.I_re, Complex.I_im]
  ring

lemma inner_repHiggs (X : Fin 4 → ℝ) :
    ⟪(repHiggs X).Φ1, (repHiggs X).Φ2⟫_ℂ = (X 0 : ℂ) * ((X 1 : ℂ) + Complex.I * (X 2 : ℂ)) := by
  rw [repHiggs_Φ1, repHiggs_Φ2, PiLp.inner_apply, Fin.sum_univ_two]
  simp only [Matrix.cons_val_zero, Matrix.cons_val_one, RCLike.inner_apply,
    map_zero, Complex.conj_ofReal]
  ring

/-!

## The Gram vector of a representative

The Gram vector of `repHiggs X` is an explicit polynomial in the four real parameters `X`.

-/

@[simp]
lemma gramVector_repHiggs_inl (X : Fin 4 → ℝ) :
    (repHiggs X).gramVector (Sum.inl 0) = X 0 ^ 2 + (X 1 ^ 2 + X 2 ^ 2 + X 3 ^ 2) := by
  rw [gramVector_inl_zero_eq, normSq_repHiggs_Φ1, normSq_repHiggs_Φ2]

@[simp]
lemma gramVector_repHiggs_inr0 (X : Fin 4 → ℝ) :
    (repHiggs X).gramVector (Sum.inr 0) = 2 * X 0 * X 1 := by
  rw [gramVector_inr_zero_eq, inner_repHiggs]
  simp only [Complex.mul_re, Complex.add_re, Complex.add_im, Complex.ofReal_re, Complex.ofReal_im,
    Complex.I_re, Complex.I_im, Complex.mul_im]
  ring

@[simp]
lemma gramVector_repHiggs_inr1 (X : Fin 4 → ℝ) :
    (repHiggs X).gramVector (Sum.inr 1) = 2 * X 0 * X 2 := by
  rw [gramVector_inr_one_eq, inner_repHiggs]
  simp only [Complex.mul_im, Complex.add_re, Complex.add_im, Complex.ofReal_re, Complex.ofReal_im,
    Complex.I_re, Complex.I_im, Complex.mul_re]
  ring

@[simp]
lemma gramVector_repHiggs_inr2 (X : Fin 4 → ℝ) :
    (repHiggs X).gramVector (Sum.inr 2) = X 0 ^ 2 - (X 1 ^ 2 + X 2 ^ 2 + X 3 ^ 2) := by
  rw [gramVector_inr_two_eq, normSq_repHiggs_Φ1, normSq_repHiggs_Φ2]

/-!

## Every configuration is gauge equivalent to a representative

-/

/-- Every field configuration is in the gauge orbit of a representative `repHiggs X`. This is the
  key fact that lets a gauge invariant potential be evaluated on the polynomial family. -/
lemma exists_smul_eq_repHiggs (φ : TwoHiggsDoublet) :
    ∃ (X : Fin 4 → ℝ) (g : GaugeGroupI), g • φ = repHiggs X := by
  by_cases h : φ.Φ1 = 0
  · refine ⟨![0, ‖φ.Φ2‖, 0, 0], HiggsVec.toRealGroupElem φ.Φ2, ?_⟩
    ext1
    · rw [gaugeGroupI_smul_fst, h, map_zero, repHiggs_Φ1]
      ext i
      fin_cases i <;> simp
    · rw [gaugeGroupI_smul_snd, HiggsVec.toRealGroupElem_apply_self, repHiggs_Φ2,
        HiggsVec.ofReal]
      ext i
      fin_cases i <;> simp [Real.sqrt_sq, norm_nonneg]
  · obtain ⟨g, h1, h2⟩ := gaugeGroupI_exists_fst_eq_snd_eq h
    refine ⟨![‖φ.Φ1‖, (⟪φ.Φ1, φ.Φ2⟫_ℂ / ‖φ.Φ1‖).re, (⟪φ.Φ1, φ.Φ2⟫_ℂ / ‖φ.Φ1‖).im,
      √(φ.gramMatrix.det.re) / ‖φ.Φ1‖], g, ?_⟩
    ext1
    · rw [gaugeGroupI_smul_fst, h1, repHiggs_Φ1]
      ext i
      fin_cases i <;> simp
    · rw [gaugeGroupI_smul_snd, h2, repHiggs_Φ2]
      ext i
      fin_cases i
      · show ⟪φ.Φ1, φ.Φ2⟫_ℂ / ↑‖φ.Φ1‖ =
          ↑(⟪φ.Φ1, φ.Φ2⟫_ℂ / ↑‖φ.Φ1‖).re + Complex.I * ↑(⟪φ.Φ1, φ.Φ2⟫_ℂ / ↑‖φ.Φ1‖).im
        rw [mul_comm Complex.I, Complex.re_add_im]
      · simp [Complex.ofReal_div]

end TwoHiggsDoublet
