/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import PhyslibAlpha.AlgebraicFramework.JordanOrderUnit.Power.Associative

/-!

# The subalgebra generated by a single element

## i. Overview

`J[a] := \operatorname{span}_ℝ\{1, a, a^2, a^3, \dots\}`: the smallest ℝ-subspace of a Jordan
order-unit algebra containing `1` and closed under `∘`-multiplication by `a`. Every element of
`J[a]` is (by definition of `span`) a finite real-linear combination of powers `a^{[n]}`.

This file only builds the *module*-level object and its membership API; the payoff — that `J[a]`
carries a genuine commutative *associative* ring structure, reducing single-observable spectral
theory to mathlib's ordinary associative machinery (`Power/Associative.lean`'s module docstring
spells out the architecture) — is `Ring.lean`.

## ii. Key definitions and results

- `IsJordanOrderUnit.generatedByOne`
- `IsJordanOrderUnit.jpow_mem_generatedByOne`, `IsJordanOrderUnit.one_mem_generatedByOne`,
  `IsJordanOrderUnit.self_mem_generatedByOne`
- `IsJordanOrderUnit.mul_mem_generatedByOne` : `J[a]` is closed under `∘`

## iii. Table of contents

- A. The generated submodule
- B. Closure under the Jordan product

-/

@[expose] public section

namespace JordanAlgebra

variable {E : Type*} [NonAssocCommRing E] [Module ℝ E] [SMulCommClass ℝ E E]
  [IsScalarTower ℝ E E] [IsCommJordan E]

open scoped JordanAlgebra

/-! ## A. The generated submodule -/

/-- The subalgebra generated by `1` and `a`, as an ℝ-submodule: the span of all Jordan powers of
`a` (which already includes `a^{[0]} = 1`). -/
def generatedByOne (a : E) : Submodule ℝ E := Submodule.span ℝ (Set.range (jpow a))

omit [SMulCommClass ℝ E E] [IsScalarTower ℝ E E] [IsCommJordan E] in
theorem jpow_mem_generatedByOne (a : E) (n : ℕ) : a ^[n] ∈ generatedByOne a :=
  Submodule.subset_span ⟨n, rfl⟩

omit [SMulCommClass ℝ E E] [IsScalarTower ℝ E E] [IsCommJordan E] in
theorem one_mem_generatedByOne (a : E) : (1 : E) ∈ generatedByOne a := by
  have h := jpow_mem_generatedByOne a 0
  rwa [jpow_zero] at h

omit [SMulCommClass ℝ E E] [IsScalarTower ℝ E E] [IsCommJordan E] in
theorem self_mem_generatedByOne (a : E) : a ∈ generatedByOne a := by
  have h := jpow_mem_generatedByOne a 1
  rwa [jpow_one] at h

/-! ## B. Closure under the Jordan product -/

/-- `J[a]` is closed under the Jordan product: multiplying two finite real-linear combinations of
powers of `a` gives another one, by bilinearity of `∘` together with the power-associativity
identity `pow_add` (`Power/Associative.lean`). This is the module-level shadow of the deeper fact
(`Ring.lean`) that `∘` restricted to `J[a]` is not just closed but genuinely associative. -/
theorem mul_mem_generatedByOne (a : E) {x y : E} (hx : x ∈ generatedByOne a)
    (hy : y ∈ generatedByOne a) : x * y ∈ generatedByOne a := by
  induction hx, hy using Submodule.span_induction₂ with
  | mem_mem x y hx hy =>
      obtain ⟨m, rfl⟩ := hx
      obtain ⟨n, rfl⟩ := hy
      exact pow_add a m n ▸ jpow_mem_generatedByOne a (m + n)
  | zero_left => simp
  | zero_right => simp
  | add_left _ _ _ _ _ _ ihx ihy => simpa [add_mul] using (generatedByOne a).add_mem ihx ihy
  | add_right _ _ _ _ _ _ ihy ihz => simpa [mul_add] using (generatedByOne a).add_mem ihy ihz
  | smul_left r _ _ _ _ ih => simpa [smul_mul_assoc] using (generatedByOne a).smul_mem r ih
  | smul_right r _ _ _ _ ih => simpa [mul_smul_comm] using (generatedByOne a).smul_mem r ih

end JordanAlgebra
