/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import PhyslibAlpha.AlgebraicFramework.JordanOrderUnit.Hom
public import PhyslibAlpha.AlgebraicFramework.JordanOrderUnit.Power.GeneratedByOne

/-!
# Jordan submodules generated by arbitrary observables

The existing `generatedByOne a` is the computable power-span presentation of the one-observable
Jordan algebra.  This file provides the complementary universal construction: the smallest
unital real submodule closed under the Jordan product and containing an arbitrary set of
observables.  Its singleton case is proved equal to the existing power span.

This is deliberately only a closure carrier.  It makes no false associativity claim for two
generators: proving that the two-generated algebra is special is the later Shirshov--Cohn step
needed for intrinsic quadratic positivity.
-/

@[expose] public section

namespace JordanAlgebra

variable {E : Type*} [NonAssocCommRing E] [Module ℝ E]

open scoped JordanAlgebra

/-- A real submodule is Jordan-closed when it contains the unit and is closed under the Jordan
product.  This is the closure notion used for arbitrary generated Jordan fragments. -/
def IsJordanSubmodule (J : Submodule ℝ E) : Prop :=
  (1 : E) ∈ J ∧ ∀ ⦃x y : E⦄, x ∈ J → y ∈ J → x * y ∈ J

/-- The smallest unital Jordan submodule containing the set `s`. -/
def generatedBySet (s : Set E) : Submodule ℝ E :=
  sInf {J : Submodule ℝ E | s ⊆ J ∧ IsJordanSubmodule J}

/-- The generating set is contained in its generated Jordan submodule. -/
theorem subset_generatedBySet (s : Set E) : s ⊆ generatedBySet s := by
  intro x hx
  change x ∈ sInf {J : Submodule ℝ E | s ⊆ J ∧ IsJordanSubmodule J}
  rw [Submodule.mem_sInf]
  intro J hJ
  exact hJ.1 hx

/-- The generated Jordan submodule contains the order unit. -/
theorem one_mem_generatedBySet (s : Set E) : (1 : E) ∈ generatedBySet s := by
  change (1 : E) ∈ sInf {J : Submodule ℝ E | s ⊆ J ∧ IsJordanSubmodule J}
  rw [Submodule.mem_sInf]
  intro J hJ
  exact hJ.2.1

/-- The generated Jordan submodule is closed under the Jordan product. -/
theorem mul_mem_generatedBySet (s : Set E) {x y : E} (hx : x ∈ generatedBySet s)
    (hy : y ∈ generatedBySet s) : x * y ∈ generatedBySet s := by
  change x ∈ sInf {J : Submodule ℝ E | s ⊆ J ∧ IsJordanSubmodule J} at hx
  change y ∈ sInf {J : Submodule ℝ E | s ⊆ J ∧ IsJordanSubmodule J} at hy
  change x * y ∈ sInf {J : Submodule ℝ E | s ⊆ J ∧ IsJordanSubmodule J}
  rw [Submodule.mem_sInf] at hx hy ⊢
  intro J hJ
  exact hJ.2.2 (hx J hJ) (hy J hJ)

/-- The universal generated submodule is itself unital and Jordan-closed. -/
theorem isJordanSubmodule_generatedBySet (s : Set E) : IsJordanSubmodule (generatedBySet s) :=
  ⟨one_mem_generatedBySet s, fun _ _ hx hy => mul_mem_generatedBySet s hx hy⟩

/-- Universal property of arbitrary Jordan generation: every unital Jordan submodule containing
the generators contains `generatedBySet s`. -/
theorem generatedBySet_le {s : Set E} {J : Submodule ℝ E} (hs : s ⊆ J)
    (hJ : IsJordanSubmodule J) : generatedBySet s ≤ J := by
  rw [generatedBySet]
  exact sInf_le ⟨hs, hJ⟩

/-- Enlarging the generating set can only enlarge its generated Jordan fragment. -/
theorem generatedBySet_mono {s t : Set E} (hst : s ⊆ t) :
    generatedBySet s ≤ generatedBySet t :=
  generatedBySet_le (fun _ hx => subset_generatedBySet t (hst hx))
    (isJordanSubmodule_generatedBySet t)

/-- The arbitrary generated Jordan fragment as its own carrier type. -/
abbrev GeneratedBySet (s : Set E) : Type _ := generatedBySet s

namespace GeneratedBySet

variable (s : Set E)

instance : Mul (GeneratedBySet s) where
  mul x y := ⟨(x : E) * (y : E), mul_mem_generatedBySet s x.2 y.2⟩

@[simp]
theorem val_mul (x y : GeneratedBySet s) : ((x * y : GeneratedBySet s) : E) = (x : E) * (y : E) :=
  rfl

instance : One (GeneratedBySet s) := ⟨⟨1, one_mem_generatedBySet s⟩⟩

@[simp]
theorem val_one : ((1 : GeneratedBySet s) : E) = 1 := rfl

/-- The canonical inclusion of a generated Jordan fragment into its ambient algebra. -/
def inclusion : GeneratedBySet s →ₗ[ℝ] E := (generatedBySet s).subtype

@[simp]
theorem inclusion_apply (x : GeneratedBySet s) : inclusion s x = (x : E) := rfl

theorem inclusion_injective : Function.Injective (inclusion s) := Subtype.val_injective

/-- Every generated Jordan fragment inherits the ambient unital commutative nonassociative ring.
Associativity is intentionally absent: it is exceptional extra structure, not part of closure. -/
instance instNonAssocCommRing : NonAssocCommRing (GeneratedBySet s) where
  __ := (inferInstance : AddCommGroup (GeneratedBySet s))
  mul := (· * ·)
  one := 1
  mul_comm x y := Subtype.ext (_root_.mul_comm (x : E) (y : E))
  one_mul x := Subtype.ext (_root_.one_mul (x : E))
  mul_one x := Subtype.ext (_root_.mul_one (x : E))
  left_distrib x y z := Subtype.ext (mul_add (x : E) (y : E) (z : E))
  right_distrib x y z := Subtype.ext (add_mul (x : E) (y : E) (z : E))
  zero_mul x := Subtype.ext (by simp)
  mul_zero x := Subtype.ext (by simp)

/-- The canonical inclusion, bundled as a unital real Jordan homomorphism. -/
def inclusionJordanHom : JordanHom (GeneratedBySet s) E where
  toLinearMap := inclusion s
  map_one' := rfl
  map_mul' _ _ := rfl

end GeneratedBySet

variable [SMulCommClass ℝ E E] [IsScalarTower ℝ E E] [IsCommJordan E]

namespace GeneratedBySet

variable (s : Set E)

instance : SMulCommClass ℝ (GeneratedBySet s) (GeneratedBySet s) where
  smul_comm r x y := by
    apply Subtype.ext
    simp only [smul_eq_mul, val_mul, Submodule.coe_smul]
    exact (mul_smul_comm r (x : E) (y : E)).symm

instance : IsScalarTower ℝ (GeneratedBySet s) (GeneratedBySet s) where
  smul_assoc r x y := Subtype.ext (smul_mul_assoc r (x : E) (y : E))

/-- The Jordan identity restricts to every generated Jordan fragment. -/
instance : IsCommJordan (GeneratedBySet s) where
  lmul_comm_rmul_rmul x y :=
    Subtype.ext (IsCommJordan.lmul_comm_rmul_rmul (x : E) (y : E))

omit [SMulCommClass ℝ E E] [IsScalarTower ℝ E E] [IsCommJordan E] in
/-- The canonical inclusion preserves the order unit. -/
@[simp]
theorem inclusion_one : inclusion s (1 : GeneratedBySet s) = 1 := rfl

omit [SMulCommClass ℝ E E] [IsScalarTower ℝ E E] [IsCommJordan E] in
/-- The canonical inclusion preserves the Jordan product. -/
@[simp]
theorem inclusion_mul (x y : GeneratedBySet s) :
    inclusion s (x * y) = inclusion s x * inclusion s y := rfl

end GeneratedBySet

/-- The existing power-span model is exactly the universal Jordan submodule generated by one
observable.  Thus single-observable CFC and later two-generator work share one closure notion,
rather than maintaining competing generated-algebra semantics. -/
theorem generatedBySet_singleton_eq_generatedByOne (a : E) :
    generatedBySet ({a} : Set E) = generatedByOne a := by
  apply le_antisymm
  · apply generatedBySet_le
    · intro x hx
      rw [Set.mem_singleton_iff] at hx
      rw [hx]
      exact self_mem_generatedByOne a
    · constructor
      · exact one_mem_generatedByOne a
      · intro x y hx hy
        exact mul_mem_generatedByOne a hx hy
  · apply Submodule.span_le.mpr
    rintro x ⟨n, rfl⟩
    induction n with
    | zero => simpa using one_mem_generatedBySet ({a} : Set E)
    | succ n ih =>
        rw [jpow_succ]
        apply mul_mem_generatedBySet ({a} : Set E)
        · exact subset_generatedBySet ({a} : Set E) (by simp)
        · exact ih

/-- The two-observable generated Jordan fragment, the carrier for the future formal
Shirshov--Cohn/specialness theorem.  No associative structure is asserted here. -/
abbrev generatedByTwo (a b : E) : Submodule ℝ E := generatedBySet ({a, b} : Set E)

/-- The two-observable generated Jordan fragment as an actual unital Jordan algebra. -/
abbrev GeneratedByTwo (a b : E) : Type _ := GeneratedBySet ({a, b} : Set E)

omit [SMulCommClass ℝ E E] [IsScalarTower ℝ E E] [IsCommJordan E] in
theorem left_mem_generatedByTwo (a b : E) : a ∈ generatedByTwo a b :=
  subset_generatedBySet ({a, b} : Set E) (by simp)

omit [SMulCommClass ℝ E E] [IsScalarTower ℝ E E] [IsCommJordan E] in
theorem right_mem_generatedByTwo (a b : E) : b ∈ generatedByTwo a b :=
  subset_generatedBySet ({a, b} : Set E) (by simp)

omit [SMulCommClass ℝ E E] [IsScalarTower ℝ E E] [IsCommJordan E] in
/-- The two-observable generated fragment is independent of the order in which its generators
are named. -/
theorem generatedByTwo_comm (a b : E) : generatedByTwo a b = generatedByTwo b a := by
  have hset : ({a, b} : Set E) = {b, a} := by
    ext x
    simp [or_comm]
  rw [generatedByTwo, hset]

end JordanAlgebra
