/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import PhyslibAlpha.AlgebraicFramework.JordanOrderUnit.Power.Associative

/-!

# Quadratic representations on one-generated Jordan algebras

Power-associativity makes the action of `U` on powers completely explicit.  These formulas are
pure Jordan algebra: they require neither an order nor a norm.  They form the computational base
for the deeper quadratic identities and, later, positivity of `U` in a JB-algebra.

The general fundamental formula `U_(U_a b) = U_a U_b U_a` is intentionally not postulated here;
it will be added only with a proof from the Jordan identity.

-/

@[expose] public section

namespace JordanAlgebra

variable {E : Type*} [NonAssocCommRing E] [Module ℝ E] [SMulCommClass ℝ E E]
  [IsCommJordan E]

open scoped JordanAlgebra

/-! ## Quadratic action on powers -/

/-- The quadratic representation is ordinary degree doubling on the associative algebra
generated by one element:
`U_(a^[m]) (a^[n]) = a^[2*m+n]`.

The exponent is written `2*m+n` to make the two copies of the outer power contributed by
`U` visible. -/
theorem quadRep_jpow_jpow (a : E) (m n : ℕ) :
    U (a ^[m]) (a ^[n]) = a ^[2 * m + n] := by
  rw [quadRep_apply]
  have h₁ : a ^[m] * (a ^[m] * a ^[n]) = a ^[m + (m + n)] := by
    rw [pow_add, pow_add]
  have h₂ : (a ^[m]) ^[2] * a ^[n] = a ^[m + m + n] := by
    rw [jpow_two, pow_add, pow_add]
  rw [h₁, h₂]
  have hdegree₁ : m + (m + n) = 2 * m + n := by omega
  have hdegree₂ : m + m + n = 2 * m + n := by omega
  rw [hdegree₁, hdegree₂]
  module

/-- A single outer factor raises the degree of a power by two. -/
theorem quadRep_jpow (a : E) (n : ℕ) : U a (a ^[n]) = a ^[n + 2] := by
  simpa [jpow_one, Nat.add_comm] using quadRep_jpow_jpow a 1 n

/-- The quadratic representation of a power at the order unit is its even power. -/
theorem quadRep_jpow_one (a : E) (m : ℕ) : U (a ^[m]) (1 : E) = a ^[2 * m] := by
  simpa using quadRep_jpow_jpow a m 0

/-- Quadratic representations compose additively on powers of a common element. -/
theorem quadRep_jpow_comp_jpow (a : E) (m n k : ℕ) :
    U (a ^[m]) (U (a ^[n]) (a ^[k])) = a ^[2 * m + 2 * n + k] := by
  rw [quadRep_jpow_jpow a n k, quadRep_jpow_jpow a m (2 * n + k)]
  congr 1
  omega

end JordanAlgebra
