/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import PhyslibAlpha.AlgebraicFramework.JordanOrderUnit.Power.GeneratedByOne

/-!

# `J[a]` is a commutative associative unital algebra

## i. Overview

This is the payoff of `Power/Associative.lean` and `Power/GeneratedByOne.lean`: the subalgebra
`J[a] = generatedByOne a`, equipped with the Jordan product `∘` restricted to it
(`mul_mem_generatedByOne` shows this restriction lands back in `J[a]`), is a genuine commutative
**associative** unital `ℝ`-algebra. Associativity is not assumed — it is *proved*, by expanding
any three elements of `J[a]` into finite linear combinations of powers of `a` and reducing to
`pow_add`'s monomial identity `a^{[m]} \circ a^{[n]} = a^{[m+n]}` (itself associative on the nose,
since `ℕ`-addition is). This is exactly the classical reduction the module docstring of
`Power/Associative.lean` describes:
$$ C(\sigma(a), \mathbb R) \xrightarrow{\text{CFC}} J[a] \xrightarrow{\iota} E, $$
and this file is what makes the left-hand associative algebra `J[a]` an honest object mathlib's
ordinary `CommRing`/`Algebra ℝ` machinery applies to, rather than needing any bespoke
non-associative functional calculus.

`J[a]` is packaged as a `Submodule ℝ E` (from `GeneratedByOne.lean`) rather than a fresh type: the
`Subtype`/coercion API this gives for free (`Submodule.subtype`, `AddSubmonoid`, ...) is exactly
what is needed, and it keeps the inclusion `ι : J[a] → E` (the second arrow above) definitionally
trivial rather than something to construct.

The power-associativity theorem in `Power/Associative.lean` is proved from the polarized Jordan
identity, so the associative ring structure produced here is unconditional.

## ii. Key definitions and results

- `JordanAlgebra.GeneratedByOne` : the subtype packaging of `generatedByOne a`
- `JordanAlgebra.GeneratedByOne.instCommRing` : the associative commutative ring structure
- `JordanAlgebra.GeneratedByOne.instAlgebra` : the `ℝ`-algebra structure

## iii. Table of contents

- A. The carrier type and its multiplication
- B. The commutative ring structure
- C. The `ℝ`-algebra structure and inclusion

-/

@[expose] public section

namespace JordanAlgebra

variable {E : Type*} [NonAssocCommRing E] [Module ℝ E] [SMulCommClass ℝ E E]
  [IsScalarTower ℝ E E] [IsCommJordan E] (a : E)

open scoped JordanAlgebra

/-! ## A. The carrier type and its multiplication -/

/-- The subalgebra generated by `1` and `a`, as its own type (the subtype of `generatedByOne a`).
This is what carries the associative `CommRing`/`Algebra ℝ` instances below; the ambient `E` itself
is generally *not* associative, so those instances cannot live on `E`. -/
abbrev GeneratedByOne (a : E) : Type _ := generatedByOne a

namespace GeneratedByOne

instance : Mul (GeneratedByOne a) where
  mul x y := ⟨(x : E) * (y : E), mul_mem_generatedByOne a x.2 y.2⟩

@[simp] theorem val_mul (x y : GeneratedByOne a) : ((x * y : GeneratedByOne a) : E) = (x:E)*(y:E) :=
  rfl

instance : One (GeneratedByOne a) := ⟨⟨1, one_mem_generatedByOne a⟩⟩

omit [SMulCommClass ℝ E E] [IsScalarTower ℝ E E] [IsCommJordan E] in
@[simp] theorem val_one : ((1 : GeneratedByOne a) : E) = 1 := rfl

/-! ## B. The commutative ring structure -/

theorem mul_assoc (x y z : GeneratedByOne a) : x * y * z = x * (y * z) := by
  obtain ⟨x, hx⟩ := x
  obtain ⟨y, hy⟩ := y
  obtain ⟨z, hz⟩ := z
  apply Subtype.ext
  show (x*y)*z = x*(y*z)
  induction hx using Submodule.span_induction with
  | mem x hx =>
      obtain ⟨i, rfl⟩ := hx
      induction hy using Submodule.span_induction with
      | mem y hy =>
          obtain ⟨j, rfl⟩ := hy
          induction hz using Submodule.span_induction with
          | mem z hz =>
              obtain ⟨k, rfl⟩ := hz
              rw [pow_add, pow_add, pow_add, pow_add, Nat.add_assoc]
          | zero => simp
          | add _ _ _ _ h1 h2 => simp [mul_add, h1, h2]
          | smul c _ _ h => simp [mul_smul_comm, h]
      | zero => simp
      | add _ _ _ _ h1 h2 => simp [mul_add, add_mul, h1, h2]
      | smul c _ _ h => simp [mul_smul_comm, smul_mul_assoc, h]
  | zero => simp
  | add _ _ _ _ h1 h2 => simp [add_mul, h1, h2]
  | smul c _ _ h => simp [smul_mul_assoc, h]

theorem mul_comm (x y : GeneratedByOne a) : x * y = y * x :=
  Subtype.ext (_root_.mul_comm (x:E) (y:E))

theorem one_mul (x : GeneratedByOne a) : (1 : GeneratedByOne a) * x = x :=
  Subtype.ext (_root_.one_mul (x:E))

theorem mul_one (x : GeneratedByOne a) : x * (1 : GeneratedByOne a) = x :=
  Subtype.ext (_root_.mul_one (x:E))

theorem left_distrib (x y z : GeneratedByOne a) : x * (y + z) = x * y + x * z :=
  Subtype.ext (mul_add (x:E) (y:E) (z:E))

theorem right_distrib (x y z : GeneratedByOne a) : (x + y) * z = x * z + y * z :=
  Subtype.ext (add_mul (x:E) (y:E) (z:E))

/-- `J[a]`, the subalgebra generated by `1` and `a`, is a genuine commutative **associative**
ring: the reduction promised in the module docstrings of `Power/Associative.lean` and this file. -/
instance instCommRing : CommRing (GeneratedByOne a) where
  __ := (inferInstance : AddCommGroup (GeneratedByOne a))
  mul := (· * ·)
  mul_assoc := mul_assoc a
  one := 1
  one_mul := one_mul a
  mul_one := mul_one a
  left_distrib := left_distrib a
  right_distrib := right_distrib a
  mul_comm := mul_comm a
  zero_mul x := Subtype.ext (by simp)
  mul_zero x := Subtype.ext (by simp)

/-! ## C. The `ℝ`-algebra structure and inclusion -/

/-- The inclusion `J[a] ↪ E`, the second arrow of
`C(σ(a), ℝ) → J[a] → E`. Just the submodule coercion, definitionally trivial. -/
def inclusion : GeneratedByOne a → E := Subtype.val

omit [SMulCommClass ℝ E E] [IsScalarTower ℝ E E] [IsCommJordan E] in
@[simp] theorem inclusion_apply (x : GeneratedByOne a) : inclusion a x = (x : E) := rfl

omit [SMulCommClass ℝ E E] [IsScalarTower ℝ E E] [IsCommJordan E] in
theorem inclusion_injective : Function.Injective (inclusion a) := Subtype.val_injective

/-- `J[a]` is an `ℝ`-algebra: scalars act via the ambient `Module ℝ E` structure (already
compatible with `∘` on `E`, hence with the restricted product on `J[a]`), and the algebra map is
just `c ↦ c • 1`. -/
noncomputable instance instAlgebra : Algebra ℝ (GeneratedByOne a) where
  algebraMap :=
    { toFun := fun c => ⟨c • (1 : E), (generatedByOne a).smul_mem c (one_mem_generatedByOne a)⟩
      map_one' := Subtype.ext (one_smul ℝ 1)
      map_mul' := fun c d => Subtype.ext (by
        show (c * d) • (1:E) = (c • (1:E)) * (d • (1:E))
        rw [mul_smul_comm, smul_mul_assoc, _root_.one_mul, smul_smul,
          _root_.mul_comm c d])
      map_zero' := Subtype.ext (by simp)
      map_add' := fun c d => Subtype.ext (by simp [add_smul]) }
  commutes' c x := mul_comm a _ x
  smul c x := ⟨c • (x:E), (generatedByOne a).smul_mem c x.2⟩
  smul_def' c x := Subtype.ext (by
    show c • (x:E) = (c • (1:E)) * (x:E)
    rw [smul_mul_assoc, _root_.one_mul])

end GeneratedByOne

end JordanAlgebra
