/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import PhyslibAlpha.AlgebraicFramework.HilbertSpace.Unbounded.BoundedIntegralAlgebra

/-!

# The strongly continuous unitary group generated by a real spectral measure

Given `μS : WOTSpectralMeasure ℝ H`, exponentiating the bounded multiplier `x ↦ exp(itx)` against
`μS` (via `boundedIntegral`, `BoundedIntegral.lean`) produces, for each real `t`, a unitary
`expIntegral μS t = exp(itT) : H →WOT[ℂ] H` — "the unitary group generated by `μS`'s self-adjoint
operator", without ever needing to construct the (generally unbounded) operator `T` itself. The
group law `expIntegral μS (t + s) = expIntegral μS t * expIntegral μS s` follows from
`boundedIntegral_mul` and `exp(i(t+s)x) = exp(itx)·exp(isx)`; strong continuity in `t` follows
from the vector-state norm-square identity (`boundedIntegral_norm_sq_eq_integral`) and dominated
convergence.

This packages exactly the representation-level half of Stone's theorem — "a (bounded, exponential)
spectral integral gives rise to a strongly continuous one-parameter unitary group" — as
`StrongUnitaryOneParameterGroup` and `expUnitaryGroup`. The converse direction (every strongly
continuous one-parameter unitary group arises this way, from the spectral measure of its
generator) is the remaining content of Stone's theorem; it needs the unbounded spectral theorem
itself to produce the generator's spectral measure in the first place, and is not built here.

## Main definitions

- `expIntegral` : `exp(itT)`, defined directly from `μS` via `boundedIntegral`.
- `expUnitaryGroup` : the resulting `StrongUnitaryOneParameterGroup`.

-/

@[expose] public section

noncomputable section

open scoped Topology InnerProductSpace Function
open ContinuousLinearMap ContinuousLinearMapWOT MeasureTheory Set

namespace QuantumMechanics

namespace WOTSpectralMeasure

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-! ## A. The exponential multiplier -/

/-- The exponential multiplier `x ↦ exp(itx)`, at real time `t`. -/
def expFunction (t : ℝ) : ℝ → ℂ :=
  fun x => Complex.exp ((t * x : ℝ) * Complex.I)

lemma expFunction_measurable (t : ℝ) : Measurable (expFunction t) := by
  change Measurable (fun x : ℝ => Complex.exp ((t * x : ℝ) * Complex.I))
  fun_prop

lemma expFunction_bounded (t : ℝ) : ∃ C, ∀ x, ‖expFunction t x‖ ≤ C := by
  refine ⟨1, fun x => ?_⟩
  exact (Complex.norm_exp_ofReal_mul_I (t * x)).le

lemma expFunction_modulus (t : ℝ) : ∀ x, ‖expFunction t x‖ = 1 := by
  intro x
  exact Complex.norm_exp_ofReal_mul_I (t * x)

lemma expFunction_neg_eq_star (t : ℝ) : expFunction (-t) = star (expFunction t) := by
  funext x
  change Complex.exp ((((-t) * x : ℝ) : ℂ) * Complex.I) =
    starRingEnd ℂ (Complex.exp (((t * x : ℝ) : ℂ) * Complex.I))
  rw [← Complex.exp_conj]
  congr 1
  simp

lemma expFunction_diff_bounded (t s : ℝ) :
    ∃ C, ∀ x, ‖expFunction t x - expFunction s x‖ ≤ C := by
  refine ⟨2, fun x => ?_⟩
  calc
    ‖expFunction t x - expFunction s x‖ ≤
        ‖expFunction t x‖ + ‖expFunction s x‖ := norm_sub_le _ _
    _ = 2 := by rw [expFunction_modulus, expFunction_modulus]; norm_num

lemma expFunction_add (t s : ℝ) : expFunction (t + s) = expFunction t * expFunction s := by
  funext x
  change Complex.exp ((((t + s) * x : ℝ) : ℂ) * Complex.I) =
    Complex.exp (((t * x : ℝ) : ℂ) * Complex.I) *
      Complex.exp (((s * x : ℝ) : ℂ) * Complex.I)
  have harg : (((t + s) * x : ℝ) : ℂ) * Complex.I =
      ((t * x : ℝ) : ℂ) * Complex.I + ((s * x : ℝ) : ℂ) * Complex.I := by
    push_cast
    ring
  rw [harg, Complex.exp_add]

/-! ## B. The unitary group and its strong continuity -/

/-- The unitary group generated by `μS`'s self-adjoint operator: `expIntegral μS t = exp(itT)`. -/
noncomputable def expIntegral (μS : WOTSpectralMeasure ℝ H) (t : ℝ) : H →WOT[ℂ] H :=
  boundedIntegral μS (expFunction t) (expFunction_measurable t) (expFunction_bounded t)

lemma expIntegral_add (μS : WOTSpectralMeasure ℝ H) (t s : ℝ) :
    expIntegral μS (t + s) = expIntegral μS t * expIntegral μS s := by
  change boundedIntegral μS (expFunction (t + s)) (expFunction_measurable (t + s))
      (expFunction_bounded (t + s)) =
    boundedIntegral μS (expFunction t) (expFunction_measurable t) (expFunction_bounded t) *
      boundedIntegral μS (expFunction s) (expFunction_measurable s) (expFunction_bounded s)
  have h := boundedIntegral_mul μS (expFunction_measurable t) (expFunction_measurable s)
    (expFunction_bounded t) (expFunction_bounded s)
  rw [← h]
  apply boundedIntegral_congr μS (expFunction_measurable (t + s))
    ((expFunction_measurable t).mul (expFunction_measurable s))
    (expFunction_bounded (t + s))
    (by
      rcases expFunction_bounded t with ⟨Ct, hCt⟩
      rcases expFunction_bounded s with ⟨Cs, hCs⟩
      refine ⟨Ct * Cs, fun x => ?_⟩
      simp only [Pi.mul_apply, norm_mul]
      exact mul_le_mul (hCt x) (hCs x) (norm_nonneg _) (by
        exact (norm_nonneg (expFunction t 0)).trans (hCt 0)))
    (by
      intro x
      exact congrFun (expFunction_add t s) x)

lemma expIntegral_zero (μS : WOTSpectralMeasure ℝ H) :
    expIntegral μS 0 = (1 : H →WOT[ℂ] H) := by
  change boundedIntegral μS (expFunction 0) (expFunction_measurable 0)
      (expFunction_bounded 0) = (1 : H →WOT[ℂ] H)
  calc
    boundedIntegral μS (expFunction 0) (expFunction_measurable 0)
        (expFunction_bounded 0) =
        boundedIntegral μS (fun _ : ℝ => (1 : ℂ)) measurable_const
          (⟨1, by simp⟩) := by
      apply boundedIntegral_congr μS (expFunction_measurable 0) measurable_const
        (expFunction_bounded 0) (⟨1, by simp⟩)
      intro x
      simp [expFunction]
    _ = 1 := by rw [boundedIntegral_const]; simp

lemma expIntegral_neg_mul (μS : WOTSpectralMeasure ℝ H) (t : ℝ) :
    expIntegral μS (-t) * expIntegral μS t = (1 : H →WOT[ℂ] H) := by
  calc
    expIntegral μS (-t) * expIntegral μS t = expIntegral μS (-t + t) :=
      (expIntegral_add μS (-t) t).symm
    _ = expIntegral μS 0 := by rw [neg_add_cancel]
    _ = 1 := expIntegral_zero μS

lemma expIntegral_mul_neg (μS : WOTSpectralMeasure ℝ H) (t : ℝ) :
    expIntegral μS t * expIntegral μS (-t) = (1 : H →WOT[ℂ] H) := by
  calc
    expIntegral μS t * expIntegral μS (-t) = expIntegral μS (t + -t) :=
      (expIntegral_add μS t (-t)).symm
    _ = expIntegral μS 0 := by rw [add_neg_cancel]
    _ = 1 := expIntegral_zero μS

lemma expIntegral_star (μS : WOTSpectralMeasure ℝ H) (t : ℝ) :
    star (expIntegral μS t) = expIntegral μS (-t) := by
  have h := boundedIntegral_star μS (expFunction_measurable t) (expFunction_bounded t)
  calc
    star (expIntegral μS t) =
        boundedIntegral μS (fun x => star (expFunction t x))
          (continuous_star.measurable.comp (expFunction_measurable t))
          (by
            rcases expFunction_bounded t with ⟨C, hC⟩
            exact ⟨C, fun x => by simpa using hC x⟩) := by
      simpa only [expIntegral] using h.symm
    _ = expIntegral μS (-t) := by
      apply boundedIntegral_congr μS
        (continuous_star.measurable.comp (expFunction_measurable t))
        (expFunction_measurable (-t))
        (by
          rcases expFunction_bounded t with ⟨C, hC⟩
          exact ⟨C, fun x => by simpa using hC x⟩)
        (expFunction_bounded (-t))
      intro x
      exact congrFun (expFunction_neg_eq_star t).symm x

lemma expIntegral_mem_unitary (μS : WOTSpectralMeasure ℝ H) (t : ℝ) :
    expIntegral μS t ∈ unitary (H →WOT[ℂ] H) := by
  let U : (H →WOT[ℂ] H)ˣ :=
    { val := expIntegral μS t
      inv := expIntegral μS (-t)
      val_inv := expIntegral_mul_neg μS t
      inv_val := expIntegral_neg_mul μS t }
  apply IsUnit.mem_unitary_of_star_mul_self ⟨U, rfl⟩
  rw [expIntegral_star]
  exact expIntegral_neg_mul μS t

@[nolint unusedArguments]
lemma expIntegral_sub_eq_boundedIntegral_diff [Nonempty H] (μS : WOTSpectralMeasure ℝ H)
    (t s : ℝ) (x : H) :
    expIntegral μS t x - expIntegral μS s x =
    boundedIntegral μS (fun z => expFunction t z - expFunction s z)
        ((expFunction_measurable t).sub (expFunction_measurable s))
        (expFunction_diff_bounded t s) x := by
  have h := boundedIntegral_sub μS (expFunction_measurable t) (expFunction_measurable s)
    (expFunction_bounded t) (expFunction_bounded s)
  have hx := congrArg (fun A : H →WOT[ℂ] H => A x) h
  change (boundedIntegral μS (expFunction t) (expFunction_measurable t)
      (expFunction_bounded t) x -
    boundedIntegral μS (expFunction s) (expFunction_measurable s)
      (expFunction_bounded s) x) =
    boundedIntegral μS (fun z => expFunction t z - expFunction s z)
      ((expFunction_measurable t).sub (expFunction_measurable s))
      (expFunction_diff_bounded t s) x
  exact hx.symm

lemma expIntegral_continuous (μS : WOTSpectralMeasure ℝ H) (x : H) :
    Continuous (fun t => expIntegral μS t x) := by
  rw [continuous_iff_continuousAt]
  intro t₀
  have hdiffNormSq : Filter.Tendsto
      (fun t => ENNReal.ofReal
        (‖expIntegral μS t x - expIntegral μS t₀ x‖ ^ 2)) (𝓝 t₀) (𝓝 0) := by
    let μ : Measure ℝ := μS.diagonalMeasure x
    let F : ℝ → ℝ → ENNReal := fun t z =>
      ENNReal.ofReal (‖expFunction t z - expFunction t₀ z‖ ^ 2)
    let F₀ : ℝ → ENNReal := fun _ => 0
    have hFmeas : ∀ t, Measurable (F t) := by
      intro t
      change Measurable (fun z => ENNReal.ofReal
        (‖expFunction t z - expFunction t₀ z‖ ^ 2))
      exact ENNReal.continuous_ofReal.measurable.comp
        (((expFunction_measurable t).sub (expFunction_measurable t₀)).norm.pow_const 2)
    have hbound : ∀ᶠ t in 𝓝 t₀, ∀ᵐ z ∂μ, F t z ≤ ENNReal.ofReal 4 := by
      filter_upwards [] with t
      filter_upwards [] with z
      dsimp [F]
      apply ENNReal.ofReal_le_ofReal
      have hnorm : ‖expFunction t z - expFunction t₀ z‖ ≤ 2 := by
        calc
          ‖expFunction t z - expFunction t₀ z‖ ≤
              ‖expFunction t z‖ + ‖expFunction t₀ z‖ := norm_sub_le _ _
          _ = 2 := by rw [expFunction_modulus, expFunction_modulus]; norm_num
      have hsq := (sq_le_sq₀ (norm_nonneg _) (by norm_num : (0 : ℝ) ≤ 2)).mpr hnorm
      norm_num at hsq ⊢
      exact hsq
    have hfin : (∫⁻ z, ENNReal.ofReal 4 ∂μ) ≠ (⊤ : ENNReal) := by
      rw [lintegral_const, μS.diagonalMeasure_univ]
      exact ENNReal.mul_ne_top ENNReal.ofReal_ne_top ENNReal.ofReal_ne_top
    have hlim : ∀ᵐ z ∂μ, Filter.Tendsto (fun t => F t z) (𝓝 t₀) (𝓝 (F₀ z)) := by
      filter_upwards [] with z
      have hcont : Continuous (fun t : ℝ => expFunction t z) := by
        unfold expFunction
        fun_prop
      have hdiff : Filter.Tendsto
          (fun t => expFunction t z - expFunction t₀ z) (𝓝 t₀) (𝓝 0) := by
        convert hcont.continuousAt.tendsto.sub
          (tendsto_const_nhds :
            Filter.Tendsto (fun _ : ℝ => expFunction t₀ z) (𝓝 t₀) (𝓝 (expFunction t₀ z))) using 1
        simp
      have hnorm : Filter.Tendsto
          (fun t => ‖expFunction t z - expFunction t₀ z‖ ^ 2) (𝓝 t₀) (𝓝 (0 ^ 2)) := by
        convert (continuous_norm.pow 2).continuousAt.tendsto.comp hdiff using 1
        · rfl
        · simp
      change Filter.Tendsto
        (fun t => ENNReal.ofReal (‖expFunction t z - expFunction t₀ z‖ ^ 2))
        (𝓝 t₀) (𝓝 0)
      have hout := ENNReal.continuous_ofReal.continuousAt.tendsto.comp hnorm
      convert hout using 1
      · funext t
        rfl
      · simp
    have hlintegral : Filter.Tendsto
        (fun t => ∫⁻ z, F t z ∂μ) (𝓝 t₀) (𝓝 (∫⁻ z, F₀ z ∂μ)) :=
      MeasureTheory.tendsto_lintegral_filter_of_dominated_convergence
        (fun _ : ℝ => ENNReal.ofReal 4)
        (by filter_upwards [] with t; exact hFmeas t) hbound hfin hlim
    have hlintegral0 : Filter.Tendsto
        (fun t => ∫⁻ z, F t z ∂μ) (𝓝 t₀) (𝓝 0) := by
      simpa [F₀] using hlintegral
    have hnormsq : ∀ t, ENNReal.ofReal
        (‖expIntegral μS t x - expIntegral μS t₀ x‖ ^ 2) = ∫⁻ z, F t z ∂μ := by
      intro t
      rw [expIntegral_sub_eq_boundedIntegral_diff]
      simpa [F, μ] using
        (boundedIntegral_norm_sq μS (f := fun z => expFunction t z - expFunction t₀ z)
          ((expFunction_measurable t).sub (expFunction_measurable t₀))
          (expFunction_diff_bounded t t₀) x)
    exact hlintegral0.congr' (Filter.Eventually.of_forall fun t => (hnormsq t).symm)
  apply Metric.tendsto_nhds.2
  intro ε hε
  have hεsq : 0 < ε ^ 2 := sq_pos_of_pos hε
  have hevent : ∀ᶠ t in 𝓝 t₀,
      ENNReal.ofReal (‖expIntegral μS t x - expIntegral μS t₀ x‖ ^ 2) <
        ENNReal.ofReal (ε ^ 2) := by
    exact hdiffNormSq.eventually
      (Iio_mem_nhds (ENNReal.ofReal_pos.mpr hεsq))
  filter_upwards [hevent] with t ht
  rw [dist_eq_norm]
  apply (sq_lt_sq₀ (norm_nonneg _) hε.le).mp
  exact (ENNReal.ofReal_lt_ofReal_iff hεsq).mp ht

/-- A strongly continuous one-parameter group of unitary bounded operators.

The continuity is stated in the strong operator sense, pointwise on vectors. This is the natural
representation-level output of the bounded spectral integral; no unbounded generator is needed
in this interface. -/
structure StrongUnitaryOneParameterGroup
    (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H] where
  /-- The unitary at each real time. -/
  toFun : ℝ → H →WOT[ℂ] H
  mem_unitary : ∀ t, toFun t ∈ unitary (H →WOT[ℂ] H)
  map_zero : toFun 0 = 1
  map_add : ∀ t s, toFun (t + s) = toFun t * toFun s
  strong_continuous : ∀ x, Continuous (fun t => toFun t x)

namespace StrongUnitaryOneParameterGroup

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

instance : CoeFun (StrongUnitaryOneParameterGroup H)
    (fun _ => ℝ → H →WOT[ℂ] H) := ⟨StrongUnitaryOneParameterGroup.toFun⟩

@[simp]
lemma zero (G : StrongUnitaryOneParameterGroup H) : G 0 = 1 := G.map_zero

lemma add (G : StrongUnitaryOneParameterGroup H) (t s : ℝ) : G (t + s) = G t * G s :=
  G.map_add t s

lemma unitary (G : StrongUnitaryOneParameterGroup H) (t : ℝ) : G t ∈ unitary (H →WOT[ℂ] H) :=
  G.mem_unitary t

lemma continuous_apply (G : StrongUnitaryOneParameterGroup H) (x : H) :
    Continuous (fun t => G t x) := G.strong_continuous x

end StrongUnitaryOneParameterGroup

/-- The unitary group obtained by exponentiating a bounded real spectral integral. -/
noncomputable def expUnitaryGroup (μS : WOTSpectralMeasure ℝ H) :
    StrongUnitaryOneParameterGroup H where
  toFun := expIntegral μS
  mem_unitary := expIntegral_mem_unitary μS
  map_zero := expIntegral_zero μS
  map_add := expIntegral_add μS
  strong_continuous := expIntegral_continuous μS

end WOTSpectralMeasure

end QuantumMechanics

end
