/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import PhyslibAlpha.AlgebraicFramework.HilbertSpace.Dynamics.Automorphism

/-!

# Hamiltonian dynamics

A bounded Hamiltonian `H` determines

    U_H(t) = exp(-itH/ℏ)

and the automorphism flow

    αₜ(a) = U_H(t) a U_H(t)⋆.

This is the special case of `UnitaryOneParameterGroup.toAutomorphism`/`hasDerivAt_toAutomorphism`/
`toAutomorphism_unique` (`HilbertSpace/Dynamics/Automorphism.lean`) where the generating unitary
group is `unitaryEvolution ℏ H`, so the flow is the unique solution of

    dαₜ(a)/dt = -(i/ℏ) [H, αₜ(a)],
    α₀ = id.

Shifting `H` by a real multiple of the identity changes `U_H(t)` only by a scalar phase and
therefore leaves the automorphism flow unchanged. For `H →L[ℂ] H` this is the only ambiguity.

-/

@[expose] public section

open scoped ComplexOrder

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- Needed for `NormedSpace.map_exp` at `H →L[ℂ] H`. -/
noncomputable local instance : NormedAlgebra ℚ (H →L[ℂ] H) :=
  .restrictScalars ℚ ℂ (H →L[ℂ] H)

namespace UnitaryOneParameterGroup

omit [CompleteSpace H] in
/-- A real scalar multiple on `H →L[ℂ] H` agrees with the corresponding complex scalar multiple. -/
private lemma real_smul_eq_complex_smul (r : ℝ) (x : H →L[ℂ] H) : r • x = (r : ℂ) • x := by
  have h' : (r : ℂ) = algebraMap ℝ ℂ r := by norm_cast
  rw [h', IsScalarTower.algebraMap_smul]

/-! ## Unitary evolution -/

/-- The unitary evolution `U_H(t) = exp(-itH/ℏ)` generated by `H`. -/
noncomputable def unitaryEvolution
    (ℏ : ℝ) (Hm : Observable (H →L[ℂ] H)) :
    UnitaryOneParameterGroup H :=
  (UnitaryOneParameterGroup.stoneEquiv).symm (ℏ⁻¹ • Hm)

/-- The generator of `unitaryEvolution` is `ℏ⁻¹ • H`. -/
@[simp]
lemma unitaryEvolution_generator
    (ℏ : ℝ) (Hm : Observable (H →L[ℂ] H)) :
    (unitaryEvolution ℏ Hm).generator =
      (ℏ⁻¹ : ℝ) • (Hm : H →L[ℂ] H) := by
  simp [unitaryEvolution, UnitaryOneParameterGroup.stoneEquiv]

/-- The closed form `U_H(t) = exp(-itH/ℏ)`. -/
lemma unitaryEvolution_apply
    (ℏ : ℝ) (Hm : Observable (H →L[ℂ] H)) (t : ℝ) :
    unitaryEvolution ℏ Hm t =
      NormedSpace.exp
        ((-(t : ℂ) * Complex.I) •
          ((ℏ⁻¹ : ℝ) • (Hm : H →L[ℂ] H))) := by
  rw [UnitaryOneParameterGroup.apply_eq_exp_generator]
  rw [unitaryEvolution_generator]

/-! ## Hamiltonian flow -/

/-- The automorphism flow induced by the unitary evolution generated by `H`. -/
noncomputable def hamiltonianFlow
    (ℏ : ℝ) (Hm : Observable (H →L[ℂ] H)) :
    AutomorphismGroup (H →L[ℂ] H) :=
  toAutomorphism (unitaryEvolution ℏ Hm)

/-- Unfolds `hamiltonianFlow` to `a ↦ U(t) a U(t)⋆`. -/
@[simp]
lemma hamiltonianFlow_apply
    (ℏ : ℝ) (Hm : Observable (H →L[ℂ] H)) (t : ℝ) (a : H →L[ℂ] H) :
    (hamiltonianFlow ℏ Hm).toFun t a =
      unitaryEvolution ℏ Hm t * a * star (unitaryEvolution ℏ Hm t) := by
  simp [hamiltonianFlow]

/-! ## Equivariance under star automorphisms

Changing the representation by `β` conjugates the flow generated by `β(H)` by `β`. -/

/-- Conjugating the generating unitary by `β` amounts to applying `β` pointwise. -/
lemma unitaryEvolution_map (ℏ : ℝ) (β : (H →L[ℂ] H) ≃⋆ₐ[ℂ] (H →L[ℂ] H))
    (Hm : Observable (H →L[ℂ] H)) (t : ℝ) :
    unitaryEvolution ℏ (β.observable Hm) t = β (unitaryEvolution ℏ Hm t) := by
  have hcont : Continuous β := (NonUnitalStarAlgHom.isometry β β.injective).continuous
  -- `β` is only registered as `ℂ`-linear, so move the real scalar `ℏ⁻¹ • _` to `ℂ` first.
  rw [unitaryEvolution_apply, unitaryEvolution_apply, real_smul_eq_complex_smul,
    real_smul_eq_complex_smul, NormedSpace.map_exp β hcont, map_smul, map_smul,
    StarAlgEquiv.observable_coe]

/-- The Hamiltonian flow is equivariant under ⋆-automorphism conjugation: `β(H)`'s flow is `H`'s
flow viewed through the change of coordinates `β`. -/
theorem hamiltonianFlow_map (ℏ : ℝ) (β : (H →L[ℂ] H) ≃⋆ₐ[ℂ] (H →L[ℂ] H))
    (Hm : Observable (H →L[ℂ] H)) :
    hamiltonianFlow ℏ (β.observable Hm) = (hamiltonianFlow ℏ Hm).conj β := by
  apply AutomorphismGroup.ext
  intro t a
  rw [AutomorphismGroup.conj_apply, hamiltonianFlow_apply, hamiltonianFlow_apply,
    unitaryEvolution_map, map_mul, map_mul, map_star, β.apply_symm_apply]

/-- The unitary specialization of `hamiltonianFlow_map`, at `β = Ad_V` for a unitary `V`. -/
lemma hamiltonianFlow_conj_unitary (ℏ : ℝ) (V : unitary (H →L[ℂ] H))
    (Hm : Observable (H →L[ℂ] H)) :
    hamiltonianFlow ℏ ((Unitary.conjStarAlgAut ℂ (H →L[ℂ] H) V).observable Hm) =
      (hamiltonianFlow ℏ Hm).conj (Unitary.conjStarAlgAut ℂ (H →L[ℂ] H) V) :=
  hamiltonianFlow_map ℏ (Unitary.conjStarAlgAut ℂ (H →L[ℂ] H) V) Hm

/-! ## Differential characterization

A one-line specialization of the generic `UnitaryOneParameterGroup` API to
`U = unitaryEvolution ℏ H`, with generator `(i/ℏ) H`. -/

/-- The scaled Hamiltonian `(i/ℏ) H`, the generator on the right of the Heisenberg equation. -/
noncomputable def G (ℏ : ℝ) (Hm : Observable (H →L[ℂ] H)) : H →L[ℂ] H :=
  (Complex.I / (ℏ : ℂ)) • (Hm : H →L[ℂ] H)

/-- `G` is `i` times `unitaryEvolution`'s generator. -/
private lemma smul_I_generator (ℏ : ℝ) (Hm : Observable (H →L[ℂ] H)) :
    Complex.I • (unitaryEvolution ℏ Hm).generator = G ℏ Hm := by
  rw [unitaryEvolution_generator, real_smul_eq_complex_smul, smul_smul]
  congr 1
  simp [div_eq_mul_inv]

/-- The Hamiltonian flow satisfies the Heisenberg equation `d/dt αₜ(a) = ⁅αₜ(a), G⁆`. -/
theorem hasDerivAt_hamiltonianFlow (ℏ : ℝ) (Hm : Observable (H →L[ℂ] H)) (a : H →L[ℂ] H)
    (t : ℝ) :
    HasDerivAt (fun t : ℝ => (hamiltonianFlow ℏ Hm).toFun t a)
      ⁅(hamiltonianFlow ℏ Hm).toFun t a, G ℏ Hm⁆ t := by
  rw [← smul_I_generator]
  exact hasDerivAt_toAutomorphism (unitaryEvolution ℏ Hm) a t

/-- The Hamiltonian flow is the unique solution of its Heisenberg initial-value problem. -/
theorem hamiltonianFlow_unique (ℏ : ℝ) (Hm : Observable (H →L[ℂ] H))
    (α : ℝ → (H →L[ℂ] H) → H →L[ℂ] H) (hα0 : α 0 = id)
    (hα : ∀ a t, HasDerivAt (fun s : ℝ => α s a) ⁅α t a, G ℏ Hm⁆ t) :
    α = fun t a => (hamiltonianFlow ℏ Hm).toFun t a := by
  apply toAutomorphism_unique (unitaryEvolution ℏ Hm) α hα0
  intro a t
  rw [smul_I_generator]
  exact hα a t

/-! ## Hamiltonians modulo scalar shifts -/

/-- Shifting `H` by `c • 1` shifts `G` by a central term. -/
private lemma G_add_smul_one (ℏ : ℝ) (Hm : Observable (H →L[ℂ] H)) (c : ℝ) :
    G ℏ (Hm + c • 1) = G ℏ Hm + ((Complex.I / (ℏ : ℂ)) * (c : ℂ)) • (1 : H →L[ℂ] H) := by
  show (Complex.I / (ℏ : ℂ)) • ((Hm : H →L[ℂ] H) + c • (1 : H →L[ℂ] H)) =
    (Complex.I / (ℏ : ℂ)) • (Hm : H →L[ℂ] H) + ((Complex.I / (ℏ : ℂ)) * (c : ℂ)) • (1 : H →L[ℂ] H)
  rw [smul_add, real_smul_eq_complex_smul, smul_smul]

omit [CompleteSpace H] in
/-- A central element (a scalar multiple of `1`) brackets to zero with anything. -/
private lemma central_cancel (z : ℂ) (x : H →L[ℂ] H) :
    ⁅x, z • (1 : H →L[ℂ] H)⁆ = 0 := by
  simp [LieRing.of_associative_ring_bracket]

omit [CompleteSpace H] in
/-- The bracket is additive in its second argument. -/
private lemma lie_add' (x m n : H →L[ℂ] H) : ⁅x, m + n⁆ = ⁅x, m⁆ + ⁅x, n⁆ := by
  simp only [LieRing.of_associative_ring_bracket]
  noncomm_ring

/-- Scalar shifts of `H` don't change the Hamiltonian flow. -/
lemma hamiltonianFlow_add_smul_one
    (ℏ : ℝ) (Hm : Observable (H →L[ℂ] H)) (c : ℝ) :
    hamiltonianFlow ℏ (Hm + c • 1) =
      hamiltonianFlow ℏ Hm := by
  apply AutomorphismGroup.ext
  intro t a
  have huniq := hamiltonianFlow_unique ℏ Hm
    (fun t a => (hamiltonianFlow ℏ (Hm + c • 1)).toFun t a) (by ext a; simp)
    (fun a t => by
      have hd := hasDerivAt_hamiltonianFlow ℏ (Hm + c • 1) a t
      rwa [G_add_smul_one, lie_add', central_cancel, add_zero] at hd)
  exact congrFun (congrFun huniq t) a

/-- Hamiltonians differing by a real scalar multiple of the identity generate the same flow. -/
lemma hamiltonianFlow_eq_of_eq_add_smul_one
    (ℏ : ℝ) (Hm K : Observable (H →L[ℂ] H)) (c : ℝ)
    (h : Hm = K + c • 1) :
    hamiltonianFlow ℏ Hm = hamiltonianFlow ℏ K := by
  rw [h]
  exact hamiltonianFlow_add_smul_one ℏ K c

/-! ## Classification up to star-automorphism conjugation

`hamiltonianFlow_map` and `hamiltonianFlow_add_smul_one` give the easy direction: `K` generates the
`β`-conjugate of `H`'s flow whenever `K = β(H) + c • 1`. The converse needs a differential argument,
`hamiltonianFlow_eq_iff` below. -/

/-- If `K = β(H) + c • 1`, `K`'s flow is `H`'s flow viewed through `β`. -/
lemma hamiltonianFlow_map_add_smul_one (ℏ : ℝ) (β : (H →L[ℂ] H) ≃⋆ₐ[ℂ] (H →L[ℂ] H))
    (Hm K : Observable (H →L[ℂ] H)) (c : ℝ) (h : K = β.observable Hm + c • 1) :
    hamiltonianFlow ℏ K = (hamiltonianFlow ℏ Hm).conj β := by
  rw [h, hamiltonianFlow_add_smul_one, hamiltonianFlow_map]

/-- If `H` and `K` generate the same flow, `G ℏ H - G ℏ K` commutes with everything: equal flows
have equal derivatives at `0`, and the Heisenberg equation reads that off as a bracket. -/
private lemma comm_G_of_hamiltonianFlow_eq (ℏ : ℝ) (Hm K : Observable (H →L[ℂ] H))
    (heq : hamiltonianFlow ℏ Hm = hamiltonianFlow ℏ K) (a : H →L[ℂ] H) :
    a * (G ℏ Hm - G ℏ K) = (G ℏ Hm - G ℏ K) * a := by
  have hH := hasDerivAt_hamiltonianFlow ℏ Hm a 0
  have hK := hasDerivAt_hamiltonianFlow ℏ K a 0
  rw [(hamiltonianFlow ℏ Hm).map_zero_apply a, heq] at hH
  rw [(hamiltonianFlow ℏ K).map_zero_apply a] at hK
  have hbracket := hH.unique hK
  simp only [LieRing.of_associative_ring_bracket] at hbracket
  have hexpand : a * (G ℏ Hm - G ℏ K) - (G ℏ Hm - G ℏ K) * a
      = (a * G ℏ Hm - G ℏ Hm * a) - (a * G ℏ K - G ℏ K * a) := by noncomm_ring
  rw [hbracket, sub_self] at hexpand
  exact sub_eq_zero.mp hexpand

/-- A self-adjoint difference of self-adjoint elements that is a scalar multiple of `1` has a real
scalar: self-adjointness of `w • 1` forces `conj w = w`. -/
private lemma exists_real_of_isSelfAdjoint_sub_smul_one [Nontrivial (H →L[ℂ] H)]
    {x y : H →L[ℂ] H} (hx : IsSelfAdjoint x) (hy : IsSelfAdjoint y) {w : ℂ}
    (h : x - y = w • (1 : H →L[ℂ] H)) :
    ∃ c : ℝ, x = y + c • 1 := by
  have hself : IsSelfAdjoint (w • (1 : H →L[ℂ] H)) := h ▸ hx.sub hy
  rw [IsSelfAdjoint, star_smul, star_one] at hself
  have hwreal : (starRingEnd ℂ) w = w := smul_left_injective ℂ one_ne_zero hself
  have hwre : w = (w.re : ℂ) := Complex.ext rfl (Complex.conj_eq_iff_im.mp hwreal)
  rw [hwre, ← real_smul_eq_complex_smul] at h
  exact ⟨w.re, sub_eq_iff_eq_add'.mp h⟩

/-- Two Hamiltonians generate the same flow (at a fixed representation) exactly when they differ
by a real scalar multiple of the identity. -/
theorem hamiltonianFlow_eq_iff (ℏ : ℝ) (hℏ : ℏ ≠ 0) [Nontrivial (H →L[ℂ] H)]
    (Hm K : Observable (H →L[ℂ] H)) :
    hamiltonianFlow ℏ Hm = hamiltonianFlow ℏ K ↔ ∃ c : ℝ, Hm = K + c • 1 := by
  constructor
  · intro heq
    have hcentral : G ℏ Hm - G ℏ K ∈ Subalgebra.center ℂ (H →L[ℂ] H) :=
      Subalgebra.mem_center_iff.mpr (comm_G_of_hamiltonianFlow_eq ℏ Hm K heq)
    obtain ⟨z, hz⟩ := (Algebra.IsCentral.mem_center_iff (K := ℂ)).mp hcentral
    rw [Algebra.algebraMap_eq_smul_one] at hz
    have ha : (Complex.I / (ℏ : ℂ)) ≠ 0 := div_ne_zero Complex.I_ne_zero (by exact_mod_cast hℏ)
    have hHK : (Hm : H →L[ℂ] H) - (K : H →L[ℂ] H) =
        ((Complex.I / (ℏ : ℂ))⁻¹ * z) • (1 : H →L[ℂ] H) := by
      have hGdiff : G ℏ Hm - G ℏ K =
          (Complex.I / (ℏ : ℂ)) • ((Hm : H →L[ℂ] H) - (K : H →L[ℂ] H)) := by
        simp only [G, smul_sub]
      rw [← smul_smul]
      exact (eq_inv_smul_iff₀ ha).mpr (hGdiff.symm.trans hz)
    obtain ⟨c, hc⟩ := exists_real_of_isSelfAdjoint_sub_smul_one Hm.2 K.2 hHK
    exact ⟨c, Subtype.ext hc⟩
  · rintro ⟨c, h⟩
    exact hamiltonianFlow_eq_of_eq_add_smul_one ℏ Hm K c h

/-- Two Hamiltonians generate conjugate flows exactly when they agree up to a change of
representation `β` and a real scalar shift. -/
theorem hamiltonianFlow_conj_iff (ℏ : ℝ) (hℏ : ℏ ≠ 0) [Nontrivial (H →L[ℂ] H)]
    (β : (H →L[ℂ] H) ≃⋆ₐ[ℂ] (H →L[ℂ] H)) (Hm K : Observable (H →L[ℂ] H)) :
    hamiltonianFlow ℏ K = (hamiltonianFlow ℏ Hm).conj β ↔ ∃ c : ℝ, K = β.observable Hm + c • 1 := by
  rw [← hamiltonianFlow_map]
  exact hamiltonianFlow_eq_iff ℏ hℏ K (β.observable Hm)

/-- Two Hamiltonians generate flows related by some automorphism of `H →L[ℂ] H` exactly when one
is a unitary conjugate of the other, up to a real scalar shift. -/
theorem hamiltonianFlow_iff_exists_unitary (ℏ : ℝ) (hℏ : ℏ ≠ 0) [Nontrivial (H →L[ℂ] H)]
    (Hm K : Observable (H →L[ℂ] H)) :
    (∃ β : (H →L[ℂ] H) ≃⋆ₐ[ℂ] (H →L[ℂ] H), hamiltonianFlow ℏ K = (hamiltonianFlow ℏ Hm).conj β) ↔
      ∃ (V : unitary (H →L[ℂ] H)) (c : ℝ),
        (K : H →L[ℂ] H) = (V : H →L[ℂ] H) * (Hm : H →L[ℂ] H) * star (V : H →L[ℂ] H) +
          c • 1 := by
  constructor
  · rintro ⟨β, hβ⟩
    obtain ⟨V, hV⟩ := conjStarAlgAut_surjective (H := H) β
    obtain ⟨c, hc⟩ := (hamiltonianFlow_conj_iff ℏ hℏ β Hm K).mp hβ
    refine ⟨V, c, ?_⟩
    have := congrArg (Subtype.val (p := fun x : H →L[ℂ] H => IsSelfAdjoint x)) hc
    simpa [← hV, Unitary.conjStarAlgAut_apply] using this
  · rintro ⟨V, c, hc⟩
    refine ⟨Unitary.conjStarAlgAut ℂ (H →L[ℂ] H) V, ?_⟩
    apply hamiltonianFlow_map_add_smul_one ℏ (Unitary.conjStarAlgAut ℂ (H →L[ℂ] H) V) Hm K c
    apply Subtype.ext
    simpa [Unitary.conjStarAlgAut_apply] using hc

end UnitaryOneParameterGroup
