/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import PhyslibAlpha.AlgebraicFramework.JordanOrderUnit.JB.GeneratedByOne.PosInvertibility

/-!

# Exact order in JB-algebras

The ordered-JB boundary initially assumes only that Jordan squares are positive.  The converse is
not an axiom: it is a consequence of the intrinsic one-observable analytic theory.  Every
observable belongs to its closed associative one-generator algebra, where the endpoint binomial
argument proves that positive elements are squares; coercing that witness back gives the global
JB cone theorem.

This is the first order-reconstruction result used by the later positive-root, projection, and
JBW spectral developments.  No Cstar realization is involved.

-/

@[expose] public section

namespace JBAlgebra

variable {E : Type*} [NormedJordanAlgebra E] [JBAlgebra E] [Nontrivial E] [PartialOrder E]
  [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]

/-- In an ordered JB-algebra, the positive cone is exactly the set of Jordan squares.  The
nontrivial direction is proved in the closed associative algebra generated by the positive
observable, then transported through its subtype coercion. -/
theorem nonneg_iff_exists_mul_self (a : E) :
    0 ≤ a ↔ ∃ b : E, b * b = a := by
  constructor
  · intro ha
    let x : NormedJordanAlgebra.ClosedGeneratedByOne a :=
      ⟨a, NormedJordanAlgebra.self_mem_closedGeneratedByOne a⟩
    have hx : 0 ≤ x := ha
    obtain ⟨b, hb⟩ := ClosedGeneratedByOne.exists_mul_self_of_nonneg a x hx
    refine ⟨(b : E), ?_⟩
    exact congrArg Subtype.val hb
  · rintro ⟨b, rfl⟩
    exact IsJordanOrderUnit.mul_self_nonneg b

end JBAlgebra
