/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import PhyslibAlpha.AlgebraicFramework.JordanOrderUnit.JB.GeneratedByOne.Spectrum
public import Mathlib.Topology.ContinuousMap.StoneWeierstrass
public import Mathlib.Topology.ContinuousMap.Compact
public import Mathlib.Analysis.Normed.Operator.Extend

/-!
# Intrinsic continuous functional calculus for one JB observable

This file starts from the genuinely Jordan-theoretic spectral theorem in
`GeneratedByOne.Spectrum`.  In particular, its norm comparison is not imported from a Cstar
realization: polynomial evaluation in the commutative associative algebra generated by `a` is
isometric for the sup norm on the intrinsic real spectrum.

The remaining construction extends this isometry from polynomial functions to all continuous
functions by Stone--Weierstrass and completeness.
-/

@[expose] public section

namespace NormedJordanAlgebra

variable {E : Type*} [NormedJordanAlgebra E] [JBAlgebra E]

open scoped JordanAlgebra

/-- The intrinsic spectrum of a complete Jordan observable is a compact type.  Bundling this
standard consequence of spectral compactness lets the continuous-function algebra carry its
ordinary sup norm without any auxiliary choice of a compact set. -/
noncomputable instance jordanSpectrum.compactSpace (a : E) : CompactSpace (jordanSpectrum a) :=
  isCompact_iff_compactSpace.mp (isCompact_jordanSpectrum a)

/-- Polynomial evaluation at the closed generator has exactly the sup norm of the corresponding
polynomial function on the intrinsic Jordan spectrum.  This is the isometric polynomial core of
the intrinsic continuous functional calculus. -/
theorem enorm_aeval_closedGenerator_eq_enorm_toContinuousMapOn [Nontrivial E]
    [PartialOrder E] [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E]
    [IsJBOrderUnit E] (a : E) (p : Polynomial ℝ) :
    ‖Polynomial.aeval (closedGenerator a) p‖ₑ =
      ‖p.toContinuousMapOn (jordanSpectrum a)‖ₑ := by
  rw [enorm_eq_nnnorm, norm_aeval_closedGenerator a p,
    ContinuousMap.enorm_eq_iSup_enorm, iSup_subtype]
  rfl

/-- The polynomial functions on the intrinsic spectrum are dense in its real continuous-function
algebra.  This is the approximation input for the JB continuous functional calculus. -/
theorem jordanSpectrum_polynomialFunctions_dense (a : E) :
    Dense (polynomialFunctions (jordanSpectrum a) : Set C(jordanSpectrum a, ℝ)) := by
  rw [dense_iff_closure_eq]
  have h := congrArg (fun A : Subalgebra ℝ C(jordanSpectrum a, ℝ) =>
    (A : Set C(jordanSpectrum a, ℝ)))
    (polynomialFunctions.topologicalClosure (jordanSpectrum a))
  change closure ↑(polynomialFunctions (jordanSpectrum a)) =
    ((⊤ : Subalgebra ℝ C(jordanSpectrum a, ℝ)) : Set C(jordanSpectrum a, ℝ))
  simpa only [Subalgebra.topologicalClosure_coe] using h

/-! ## The descended polynomial map -/

omit [JBAlgebra E] in
/-- Every polynomial function on the intrinsic spectrum has a polynomial representative. -/
theorem exists_polynomialRepresentative (a : E)
    (f : polynomialFunctions (jordanSpectrum a)) :
    ∃ p : Polynomial ℝ,
      Polynomial.toContinuousMapOnAlgHom (jordanSpectrum a) p = f := by
  have hf : (f : C(jordanSpectrum a, ℝ)) ∈
      (polynomialFunctions (jordanSpectrum a) : Set C(jordanSpectrum a, ℝ)) := f.property
  rw [polynomialFunctions_coe] at hf
  exact hf

/-- A chosen polynomial representative.  The choice is only an implementation device:
`aeval_closedGenerator_eq_of_toContinuousMapOn_eq` proves evaluation is independent of it. -/
noncomputable def polynomialRepresentative (a : E)
    (f : polynomialFunctions (jordanSpectrum a)) : Polynomial ℝ :=
  Classical.choose (exists_polynomialRepresentative a f)

omit [JBAlgebra E] in
theorem toContinuousMapOn_polynomialRepresentative (a : E)
    (f : polynomialFunctions (jordanSpectrum a)) :
    Polynomial.toContinuousMapOnAlgHom (jordanSpectrum a) (polynomialRepresentative a f) = f :=
  Classical.choose_spec (exists_polynomialRepresentative a f)

/-- Equality of polynomial functions on the intrinsic spectrum implies equality of their values
at the closed generator.  This is exactly the quotient step needed to descend polynomial
evaluation to `polynomialFunctions (jordanSpectrum a)`. -/
theorem aeval_closedGenerator_eq_of_toContinuousMapOn_eq [Nontrivial E]
    [PartialOrder E] [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E]
    [IsJBOrderUnit E] (a : E) {p q : Polynomial ℝ}
    (h : Polynomial.toContinuousMapOnAlgHom (jordanSpectrum a) p =
      Polynomial.toContinuousMapOnAlgHom (jordanSpectrum a) q) :
    Polynomial.aeval (closedGenerator a) p = Polynomial.aeval (closedGenerator a) q := by
  rw [← sub_eq_zero]
  apply enorm_eq_zero.mp
  rw [← map_sub, enorm_aeval_closedGenerator_eq_enorm_toContinuousMapOn a]
  have hzero : Polynomial.toContinuousMapOnAlgHom (jordanSpectrum a) (p - q) = 0 := by
    rw [map_sub, h, sub_self]
  change ‖Polynomial.toContinuousMapOnAlgHom (jordanSpectrum a) (p - q)‖ₑ = 0
  rw [hzero]
  rw [enorm_eq_nnnorm]
  simp

/-- Polynomial evaluation descended to the subspace of polynomial functions on the intrinsic
spectrum.  The preceding quotient theorem makes this independent of the chosen representative. -/
noncomputable def polynomialCfcLinearMap [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    polynomialFunctions (jordanSpectrum a) →ₗ[ℝ] ClosedGeneratedByOne a where
  toFun f := Polynomial.aeval (closedGenerator a) (polynomialRepresentative a f)
  map_add' f g := by
    rw [← map_add]
    apply aeval_closedGenerator_eq_of_toContinuousMapOn_eq a
    rw [map_add, toContinuousMapOn_polynomialRepresentative,
      toContinuousMapOn_polynomialRepresentative,
      toContinuousMapOn_polynomialRepresentative]
    rfl
  map_smul' r f := by
    rw [← map_smul]
    apply aeval_closedGenerator_eq_of_toContinuousMapOn_eq a
    rw [map_smul, toContinuousMapOn_polynomialRepresentative,
      toContinuousMapOn_polynomialRepresentative]
    rfl

/-- The descended polynomial map preserves the exact sup norm. -/
theorem enorm_polynomialCfcLinearMap [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E)
    (f : polynomialFunctions (jordanSpectrum a)) :
    ‖polynomialCfcLinearMap a f‖ₑ = ‖f‖ₑ := by
  change ‖Polynomial.aeval (closedGenerator a) (polynomialRepresentative a f)‖ₑ = ‖f‖ₑ
  rw [enorm_aeval_closedGenerator_eq_enorm_toContinuousMapOn a]
  change ‖Polynomial.toContinuousMapOnAlgHom (jordanSpectrum a)
    (polynomialRepresentative a f)‖ₑ = ‖f‖ₑ
  rw [toContinuousMapOn_polynomialRepresentative]
  rfl

/-- The polynomial calculus is a real linear isometry from polynomial functions with their
sup norm into the closed algebra generated by the observable. -/
noncomputable def polynomialCfcLinearIsometry [Nontrivial E] [PartialOrder E]
    [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (a : E) : polynomialFunctions (jordanSpectrum a) →ₗᵢ[ℝ] ClosedGeneratedByOne a where
  toLinearMap := polynomialCfcLinearMap a
  norm_map' f := by
    have h : ‖polynomialCfcLinearMap a f‖ₑ = ‖f‖ₑ :=
      enorm_polynomialCfcLinearMap a f
    exact congrArg (fun x : NNReal => (x : ℝ)) <|
      ENNReal.coe_injective (by simpa only [enorm_eq_nnnorm] using h)

/-- The descended polynomial calculus respects multiplication. -/
theorem polynomialCfcLinearMap_mul [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E)
    (f g : polynomialFunctions (jordanSpectrum a)) :
    polynomialCfcLinearMap a (f * g) = polynomialCfcLinearMap a f * polynomialCfcLinearMap a g := by
  change Polynomial.aeval (closedGenerator a) (polynomialRepresentative a (f * g)) =
    Polynomial.aeval (closedGenerator a) (polynomialRepresentative a f) *
      Polynomial.aeval (closedGenerator a) (polynomialRepresentative a g)
  rw [← Polynomial.aeval_mul]
  apply aeval_closedGenerator_eq_of_toContinuousMapOn_eq a
  rw [map_mul, toContinuousMapOn_polynomialRepresentative,
    toContinuousMapOn_polynomialRepresentative,
    toContinuousMapOn_polynomialRepresentative]
  rfl

/-! ## Completion from polynomial functions -/

/-- The canonical continuous linear extension of intrinsic polynomial evaluation.  It is defined
solely by completion along the dense polynomial functions on `jordanSpectrum a`. -/
noncomputable def jordanCfcLinear [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    C(jordanSpectrum a, ℝ) →L[ℝ] ClosedGeneratedByOne a :=
  (polynomialCfcLinearIsometry a).toContinuousLinearMap.extend
    (polynomialFunctions (jordanSpectrum a)).toSubmodule.subtypeL

private theorem denseRange_polynomialFunctions_subtype (a : E) :
    DenseRange ((polynomialFunctions (jordanSpectrum a)).toSubmodule.subtypeL :
      polynomialFunctions (jordanSpectrum a) →L[ℝ] C(jordanSpectrum a, ℝ)) := by
  rw [show ((polynomialFunctions (jordanSpectrum a)).toSubmodule.subtypeL :
    polynomialFunctions (jordanSpectrum a) → C(jordanSpectrum a, ℝ)) = Subtype.val by rfl,
    denseRange_subtype_val]
  exact jordanSpectrum_polynomialFunctions_dense a

/-- The continuous extension agrees with the descended polynomial calculus on every polynomial
function. -/
theorem jordanCfcLinear_eq_polynomialCfcLinearMap [Nontrivial E] [PartialOrder E]
    [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (a : E) (f : polynomialFunctions (jordanSpectrum a)) :
    jordanCfcLinear a f = polynomialCfcLinearMap a f := by
  exact ContinuousLinearMap.extend_eq _ (denseRange_polynomialFunctions_subtype a)
    isUniformEmbedding_subtype_val.isUniformInducing f

/-- The coordinate function, regarded as a polynomial function on the intrinsic spectrum. -/
noncomputable def jordanSpectrumCoordinatePolynomialFunction (a : E) :
    polynomialFunctions (jordanSpectrum a) :=
  ⟨Polynomial.toContinuousMapOnAlgHom (jordanSpectrum a) Polynomial.X, by
    change Polynomial.toContinuousMapOnAlgHom (jordanSpectrum a) Polynomial.X ∈
      (⊤ : Subalgebra ℝ (Polynomial ℝ)).map
        (Polynomial.toContinuousMapOnAlgHom (jordanSpectrum a))
    exact ⟨Polynomial.X, by simp, rfl⟩⟩

/-- The intrinsic continuous calculus sends the spectrum coordinate to the closed generator. -/
theorem jordanCfcLinear_coordinate [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    jordanCfcLinear a (jordanSpectrumCoordinatePolynomialFunction a) = closedGenerator a := by
  rw [jordanCfcLinear_eq_polynomialCfcLinearMap]
  change Polynomial.aeval (closedGenerator a)
    (polynomialRepresentative a (jordanSpectrumCoordinatePolynomialFunction a)) = closedGenerator a
  have h := aeval_closedGenerator_eq_of_toContinuousMapOn_eq a
    (p := polynomialRepresentative a (jordanSpectrumCoordinatePolynomialFunction a))
    (q := Polynomial.X) (by
      rw [toContinuousMapOn_polynomialRepresentative]
      rfl)
  simpa using h

/-- The continuous extension remains an isometry on all real continuous functions. -/
theorem norm_jordanCfcLinear [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E)
    (f : C(jordanSpectrum a, ℝ)) : ‖jordanCfcLinear a f‖ = ‖f‖ := by
  refine (denseRange_polynomialFunctions_subtype a).induction ?_ ?_ f
  · rintro _ ⟨g, rfl⟩
    change ‖jordanCfcLinear a g‖ = ‖g‖
    rw [jordanCfcLinear_eq_polynomialCfcLinearMap]
    exact (polynomialCfcLinearIsometry a).norm_map g
  · exact isClosed_eq ((jordanCfcLinear a).continuous.norm) continuous_norm

/-- The continuous intrinsic JB calculus as a linear isometry. -/
noncomputable def jordanCfcLinearIsometry [Nontrivial E] [PartialOrder E]
    [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (a : E) : C(jordanSpectrum a, ℝ) →ₗᵢ[ℝ] ClosedGeneratedByOne a where
  toLinearMap := jordanCfcLinear a
  norm_map' := norm_jordanCfcLinear a

/-- The continuous intrinsic calculus is multiplicative.  Both variables are reduced to
polynomial functions by density; equality is then closed by continuity of multiplication. -/
theorem jordanCfcLinear_mul [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E)
    (f g : C(jordanSpectrum a, ℝ)) :
    jordanCfcLinear a (f * g) = jordanCfcLinear a f * jordanCfcLinear a g := by
  refine (denseRange_polynomialFunctions_subtype a).induction ?_ ?_ f
  · rintro _ ⟨p, rfl⟩
    refine (denseRange_polynomialFunctions_subtype a).induction ?_ ?_ g
    · rintro _ ⟨q, rfl⟩
      let p' : polynomialFunctions (jordanSpectrum a) := ⟨p, p.property⟩
      let q' : polynomialFunctions (jordanSpectrum a) := ⟨q, q.property⟩
      change jordanCfcLinear a (↑(p' * q') : C(jordanSpectrum a, ℝ)) =
        jordanCfcLinear a p' * jordanCfcLinear a q'
      rw [jordanCfcLinear_eq_polynomialCfcLinearMap,
        jordanCfcLinear_eq_polynomialCfcLinearMap,
        jordanCfcLinear_eq_polynomialCfcLinearMap]
      exact polynomialCfcLinearMap_mul a p' q'
    · exact isClosed_eq
        ((jordanCfcLinear a).continuous.comp (continuous_const.mul continuous_id))
        ((continuous_const.mul (jordanCfcLinear a).continuous))
  · exact isClosed_eq
      ((jordanCfcLinear a).continuous.comp (continuous_id.mul continuous_const))
      ((jordanCfcLinear a).continuous.mul continuous_const)

/-- The continuous intrinsic calculus preserves the constant one function. -/
theorem jordanCfcLinear_one [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    jordanCfcLinear a (1 : C(jordanSpectrum a, ℝ)) = 1 := by
  let f : polynomialFunctions (jordanSpectrum a) := 1
  change jordanCfcLinear a f = 1
  rw [jordanCfcLinear_eq_polynomialCfcLinearMap]
  change Polynomial.aeval (closedGenerator a) (polynomialRepresentative a f) = 1
  have h := aeval_closedGenerator_eq_of_toContinuousMapOn_eq a
    (p := polynomialRepresentative a f) (q := 1) (by
      rw [toContinuousMapOn_polynomialRepresentative]
      change (1 : C(jordanSpectrum a, ℝ)) =
        Polynomial.toContinuousMapOnAlgHom (jordanSpectrum a) 1
      ext x
      simp)
  simpa using h

/-- The intrinsic continuous functional calculus as a unital real algebra homomorphism. -/
noncomputable def jordanCfcHom [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    C(jordanSpectrum a, ℝ) →ₐ[ℝ] ClosedGeneratedByOne a where
  toFun := jordanCfcLinear a
  map_zero' := (jordanCfcLinear a).map_zero
  map_add' := (jordanCfcLinear a).map_add
  map_one' := jordanCfcLinear_one a
  map_mul' := jordanCfcLinear_mul a
  commutes' r := by
    rw [Algebra.algebraMap_eq_smul_one, Algebra.algebraMap_eq_smul_one,
      map_smul, jordanCfcLinear_one]

/-- The intrinsic CFC algebra homomorphism is an isometry. -/
theorem jordanCfcHom_isometry [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    Isometry (jordanCfcHom a) :=
  (jordanCfcLinearIsometry a).isometry

/-- The intrinsic CFC sends the canonical coordinate on the spectrum to the observable. -/
theorem jordanCfcHom_id [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    jordanCfcHom a (ContinuousMap.restrict (jordanSpectrum a) (.id ℝ)) = closedGenerator a := by
  change jordanCfcLinear a (ContinuousMap.restrict (jordanSpectrum a) (.id ℝ)) = closedGenerator a
  rw [← Polynomial.toContinuousMapOn_X_eq_restrict_id]
  exact jordanCfcLinear_coordinate a

/-- Apply the intrinsic continuous functional calculus to a real continuous function on the
canonical Jordan spectrum. -/
noncomputable def jordanCfc [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E)
    (f : C(jordanSpectrum a, ℝ)) : E := (jordanCfcHom a f : ClosedGeneratedByOne a)

/-- The intrinsic JB functional calculus has exactly the sup norm. -/
theorem norm_jordanCfc [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E)
    (f : C(jordanSpectrum a, ℝ)) : ‖jordanCfc a f‖ = ‖f‖ :=
  norm_jordanCfcLinear a f

/-- The range of the intrinsic CFC is closed, because its source is complete and the calculus is
an isometry. -/
theorem isClosed_range_jordanCfcHom [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    IsClosed (Set.range (jordanCfcHom a)) :=
  (jordanCfcHom_isometry a).antilipschitz.isClosed_range
    (jordanCfcHom_isometry a).uniformContinuous

/-- The algebraic one-generator submodule included into its norm closure. -/
noncomputable def generatedByOneInClosed (a : E) :
    JordanAlgebra.generatedByOne a →ₗ[ℝ] ClosedGeneratedByOne a :=
  (JordanAlgebra.generatedByOne a).inclusion (generatedByOne_le_closedGeneratedByOne a)

omit [JBAlgebra E] in
/-- The algebraic one-generator submodule is dense in its closed generated algebra. -/
theorem denseRange_generatedByOneInClosed (a : E) :
    DenseRange (generatedByOneInClosed a) := by
  change DenseRange (Set.inclusion (generatedByOne_le_closedGeneratedByOne a))
  apply (denseRange_inclusion_iff (generatedByOne_le_closedGeneratedByOne a)).2
  intro x hx
  exact hx

omit [JBAlgebra E] in
/-- The inclusion of an algebraic Jordan power is the corresponding ordinary power in the
associative closed one-generator algebra. -/
theorem generatedByOneInClosed_jpow (a : E) (n : ℕ) :
    generatedByOneInClosed a ⟨a ^[n], JordanAlgebra.jpow_mem_generatedByOne a n⟩ =
      (closedGenerator a) ^ n := by
  apply Subtype.ext
  induction n with
  | zero => simp [generatedByOneInClosed]
  | succ n ih =>
      simpa [generatedByOneInClosed, ClosedGeneratedByOne.val_mul, pow_succ,
        JordanAlgebra.jpow_succ, mul_comm] using congrArg (fun x : E => a * x) ih

/-- Every algebraic Jordan power of the observable lies in the range of the intrinsic CFC. -/
theorem generatedByOneInClosed_jpow_mem_range_jordanCfcHom [Nontrivial E] [PartialOrder E]
    [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (a : E) (n : ℕ) :
    generatedByOneInClosed a ⟨a ^[n], JordanAlgebra.jpow_mem_generatedByOne a n⟩ ∈
      Set.range (jordanCfcHom a) := by
  refine ⟨(ContinuousMap.restrict (jordanSpectrum a) (.id ℝ)) ^ n, ?_⟩
  rw [map_pow, jordanCfcHom_id, ← generatedByOneInClosed_jpow]

/-- The whole algebraic one-generator submodule lies in the CFC range. -/
theorem generatedByOneInClosed_mem_range_jordanCfcHom [Nontrivial E] [PartialOrder E]
    [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (a : E) (x : JordanAlgebra.generatedByOne a) :
    generatedByOneInClosed a x ∈ Set.range (jordanCfcHom a) := by
  have hspan : ∀ y ∈ JordanAlgebra.generatedByOne a,
      ∃ f : C(jordanSpectrum a, ℝ), ((jordanCfcHom a f : ClosedGeneratedByOne a) : E) = y := by
    intro y hy
    induction hy using Submodule.span_induction with
    | mem y hy =>
        obtain ⟨n, rfl⟩ := hy
        obtain ⟨f, hf⟩ := generatedByOneInClosed_jpow_mem_range_jordanCfcHom a n
        exact ⟨f, congrArg (fun z : ClosedGeneratedByOne a => (z : E)) hf⟩
    | zero => exact ⟨0, by simp⟩
    | add y z hy hz ihy ihz =>
        obtain ⟨fy, hfy⟩ := ihy
        obtain ⟨fz, hfz⟩ := ihz
        exact ⟨fy + fz, by simpa [map_add] using congrArg₂ (· + ·) hfy hfz⟩
    | smul r y hy ihy =>
        obtain ⟨f, hf⟩ := ihy
        exact ⟨r • f, by simpa [map_smul] using congrArg (fun z : E => r • z) hf⟩
  obtain ⟨f, hf⟩ := hspan x x.property
  refine ⟨f, Subtype.ext ?_⟩
  exact hf

/-- The intrinsic continuous functional calculus is onto the closed one-generator JB algebra. -/
theorem jordanCfcLinear_range_eq_top [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    LinearMap.range (jordanCfcHom a).toLinearMap = ⊤ := by
  apply top_unique
  intro x hx
  have hdense : closure (Set.range (generatedByOneInClosed a)) = Set.univ :=
    dense_iff_closure_eq.mp (denseRange_generatedByOneInClosed a)
  have hxclosure : x ∈ closure (Set.range (generatedByOneInClosed a)) := by
    rw [hdense]
    trivial
  have hsubset : Set.range (generatedByOneInClosed a) ⊆ Set.range (jordanCfcHom a) := by
    rintro y ⟨z, rfl⟩
    exact generatedByOneInClosed_mem_range_jordanCfcHom a z
  exact closure_minimal hsubset (isClosed_range_jordanCfcHom a) hxclosure

/-- The range of the intrinsic CFC algebra homomorphism is the entire closed one-generator
JB algebra. -/
theorem jordanCfcHom_range_eq_top [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    (jordanCfcHom a).range = ⊤ := by
  apply top_unique
  intro x hx
  obtain ⟨f, hf⟩ := LinearMap.range_eq_top.mp (jordanCfcLinear_range_eq_top a) x
  exact ⟨f, hf⟩

/-- The intrinsic continuous functional calculus identifies the continuous real functions on the
Jordan spectrum with the closed associative algebra generated by the observable.  The algebraic
equivalence is separate from `jordanCfcHom_isometry`, which records its essential isometric
property. -/
noncomputable def jordanCfcEquiv [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    C(jordanSpectrum a, ℝ) ≃ₐ[ℝ] ClosedGeneratedByOne a :=
  AlgEquiv.ofBijective (jordanCfcHom a) ⟨(jordanCfcHom_isometry a).injective, by
    intro x
    have hx : x ∈ (jordanCfcHom a).range := by
      rw [jordanCfcHom_range_eq_top]
      trivial
    exact hx⟩

/-- The algebra equivalence supplied by the intrinsic CFC preserves the sup norm exactly. -/
theorem norm_jordanCfcEquiv_apply [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E)
    (f : C(jordanSpectrum a, ℝ)) : ‖jordanCfcEquiv a f‖ = ‖f‖ :=
  norm_jordanCfcLinear a f

/-- The pointwise CFC coordinate law. -/
theorem jordanCfc_id [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    jordanCfc a (ContinuousMap.restrict (jordanSpectrum a) (.id ℝ)) = a := by
  exact congrArg (fun x : ClosedGeneratedByOne a => (x : E)) (jordanCfcHom_id a)

/-- The pointwise CFC is additive. -/
theorem jordanCfc_add [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E)
    (f g : C(jordanSpectrum a, ℝ)) :
    jordanCfc a (f + g) = jordanCfc a f + jordanCfc a g :=
  congrArg (fun x : ClosedGeneratedByOne a => (x : E)) (map_add (jordanCfcHom a) f g)

/-- The pointwise CFC preserves subtraction. -/
theorem jordanCfc_sub [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E)
    (f g : C(jordanSpectrum a, ℝ)) :
    jordanCfc a (f - g) = jordanCfc a f - jordanCfc a g :=
  congrArg (fun x : ClosedGeneratedByOne a => (x : E)) (map_sub (jordanCfcHom a) f g)

/-- The pointwise CFC preserves zero. -/
theorem jordanCfc_zero [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    jordanCfc a (0 : C(jordanSpectrum a, ℝ)) = 0 :=
  congrArg (fun x : ClosedGeneratedByOne a => (x : E)) (map_zero (jordanCfcHom a))

/-- The pointwise CFC is multiplicative. -/
theorem jordanCfc_mul [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E)
    (f g : C(jordanSpectrum a, ℝ)) :
    jordanCfc a (f * g) = jordanCfc a f * jordanCfc a g :=
  congrArg (fun x : ClosedGeneratedByOne a => (x : E)) (map_mul (jordanCfcHom a) f g)

/-- The pointwise CFC sends constant functions to the corresponding scalar multiples of one. -/
theorem jordanCfc_const [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) (r : ℝ) :
    jordanCfc a (ContinuousMap.const (jordanSpectrum a) r) = r • (1 : E) := by
  change
    ((jordanCfcHom a (ContinuousMap.const (jordanSpectrum a) r) : ClosedGeneratedByOne a) : E) =
      r • (1 : E)
  have hconst : ContinuousMap.const (jordanSpectrum a) r = r • (1 : C(jordanSpectrum a, ℝ)) := by
    ext x
    simp
  have h : jordanCfcHom a (ContinuousMap.const (jordanSpectrum a) r) =
      r • (1 : ClosedGeneratedByOne a) := by
    rw [hconst]
    simpa only [Algebra.algebraMap_eq_smul_one] using (jordanCfcHom a).commutes r
  exact congrArg (fun x : ClosedGeneratedByOne a => (x : E)) h

/-! ## Positive square roots -/

/-- The continuous square-root function on the intrinsic spectrum of a positive observable. -/
noncomputable def jordanSpectrumSqrt (a : E) : C(jordanSpectrum a, ℝ) :=
  ⟨fun x => Real.sqrt x, Real.continuous_sqrt.comp continuous_subtype_val⟩

/-- The canonical intrinsic positive square root of a nonnegative JB observable, obtained by
applying its own continuous functional calculus to the real square-root function. -/
noncomputable def jordanSqrt [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) (_ha : 0 ≤ a) : E :=
  jordanCfc a (jordanSpectrumSqrt a)

/-- The continuous square-root function squares to the spectral coordinate for a positive
observable. -/
theorem jordanSpectrumSqrt_mul_self_eq_id [PartialOrder E]
    [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    {a : E} (ha : 0 ≤ a) : jordanSpectrumSqrt a * jordanSpectrumSqrt a =
      ContinuousMap.restrict (jordanSpectrum a) (.id ℝ) := by
  ext x
  change Real.sqrt (x : ℝ) * Real.sqrt x = x
  exact Real.mul_self_sqrt (nonneg_of_mem_jordanSpectrum ha x.property)

/-- The canonical positive square root squares to its input. -/
theorem jordanSqrt_mul_self [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) (ha : 0 ≤ a) :
    jordanSqrt a ha * jordanSqrt a ha = a := by
  unfold jordanSqrt
  rw [← jordanCfc_mul, jordanSpectrumSqrt_mul_self_eq_id ha, jordanCfc_id]

/-- The canonical square root is nonnegative.  The fourth-root function is a square root of the
square-root function, so exact cone reconstruction proves positivity without a representation. -/
theorem jordanSqrt_nonneg [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) (ha : 0 ≤ a) :
    0 ≤ jordanSqrt a ha := by
  let fourthRoot : C(jordanSpectrum a, ℝ) :=
    ⟨fun x => Real.sqrt (Real.sqrt x),
      Real.continuous_sqrt.comp (Real.continuous_sqrt.comp continuous_subtype_val)⟩
  have hfourth : jordanSqrt a ha = jordanCfc a fourthRoot * jordanCfc a fourthRoot := by
    rw [← jordanCfc_mul]
    change jordanCfc a (jordanSpectrumSqrt a) = jordanCfc a (fourthRoot * fourthRoot)
    congr 1
    ext x
    change Real.sqrt x = Real.sqrt (Real.sqrt x) * Real.sqrt (Real.sqrt x)
    exact (Real.mul_self_sqrt (Real.sqrt_nonneg x)).symm
  rw [hfourth]
  exact IsJordanOrderUnit.mul_self_nonneg _

/-! ## Absolute value and positive/negative parts -/

/-- A CFC value is positive whenever its defining function is a pointwise square. -/
theorem jordanCfc_nonneg_of_eq_mul_self [Nontrivial E] [PartialOrder E]
    [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (a : E) {f g : C(jordanSpectrum a, ℝ)} (hfg : f = g * g) : 0 ≤ jordanCfc a f := by
  rw [hfg, jordanCfc_mul]
  exact IsJordanOrderUnit.mul_self_nonneg _

/-- The intrinsic continuous calculus is positive: every pointwise nonnegative continuous
function on the canonical Jordan spectrum has a nonnegative value in the JB algebra.  The proof
uses the continuous pointwise square root and exact-cone reconstruction, without a chosen
associative realization. -/
theorem jordanCfc_nonneg [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E)
    (f : C(jordanSpectrum a, ℝ)) (hf : ∀ x, 0 ≤ f x) : 0 ≤ jordanCfc a f := by
  let root : C(jordanSpectrum a, ℝ) :=
    ⟨fun x => Real.sqrt (f x), Real.continuous_sqrt.comp f.continuous⟩
  apply jordanCfc_nonneg_of_eq_mul_self a (g := root)
  ext x
  change f x = Real.sqrt (f x) * Real.sqrt (f x)
  exact (Real.mul_self_sqrt (hf x)).symm

/-- The intrinsic continuous calculus is monotone for the pointwise order on continuous
functions. -/
theorem jordanCfc_monotone [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E)
    {f g : C(jordanSpectrum a, ℝ)} (hfg : f ≤ g) : jordanCfc a f ≤ jordanCfc a g := by
  rw [← sub_nonneg, ← jordanCfc_sub]
  exact jordanCfc_nonneg a (g - f) fun x => sub_nonneg.mpr (hfg x)

/-- The intrinsic CFC reflects positivity as well as preserving it.  A positive CFC value is a
square already in its closed generated algebra; transporting that local square witness back
through the CFC equivalence shows that the defining continuous function is pointwise a square. -/
theorem jordanCfc_nonneg_iff [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E)
    (f : C(jordanSpectrum a, ℝ)) : 0 ≤ jordanCfc a f ↔ ∀ x, 0 ≤ f x := by
  constructor
  · intro hf
    change 0 ≤ (jordanCfcHom a f : ClosedGeneratedByOne a) at hf
    obtain ⟨s, hs⟩ := JBAlgebra.ClosedGeneratedByOne.exists_mul_self_of_nonneg a
      (jordanCfcHom a f) hf
    let g : C(jordanSpectrum a, ℝ) := (jordanCfcEquiv a).symm s
    have hgs : jordanCfcHom a g = s := (jordanCfcEquiv a).apply_symm_apply s
    have hfg : f = g * g := (jordanCfcHom_isometry a).injective (by
      rw [map_mul, hgs, hs])
    intro x
    rw [hfg]
    exact mul_self_nonneg _
  · exact jordanCfc_nonneg a f

/-- The intrinsic CFC is an order embedding from pointwise-ordered continuous functions onto the
closed generated JB algebra. -/
theorem jordanCfc_le_iff [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E)
    (f g : C(jordanSpectrum a, ℝ)) : jordanCfc a f ≤ jordanCfc a g ↔ f ≤ g := by
  constructor
  · intro hfg x
    have hnonneg : 0 ≤ jordanCfc a (g - f) := by
      rw [jordanCfc_sub]
      exact sub_nonneg.mpr hfg
    exact sub_nonneg.mp ((jordanCfc_nonneg_iff a (g - f)).mp hnonneg x)
  · exact jordanCfc_monotone a

/-- The canonical CFC square root is the unique nonnegative square root lying in the closed
one-generator algebra of its input.  The remaining unrestricted uniqueness theorem is genuinely
multielement: it must show that an arbitrary positive root belongs to this algebra, or replace
that conclusion through quadratic Jordan theory. -/
theorem jordanSqrt_eq_of_mem_closedGeneratedByOne [Nontrivial E] [PartialOrder E]
    [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (a : E) (ha : 0 ≤ a) (b : ClosedGeneratedByOne a) (hb0 : 0 ≤ b)
    (hb : b * b = closedGenerator a) : jordanSqrt a ha = (b : E) := by
  let f : C(jordanSpectrum a, ℝ) := (jordanCfcEquiv a).symm b
  have hfb : jordanCfcHom a f = b := (jordanCfcEquiv a).apply_symm_apply b
  have hf0 : ∀ x, 0 ≤ f x := (jordanCfc_nonneg_iff a f).mp (by
    change 0 ≤ ((jordanCfcHom a f : ClosedGeneratedByOne a) : E)
    rw [hfb]
    exact hb0)
  have hfsq : f * f = ContinuousMap.restrict (jordanSpectrum a) (.id ℝ) :=
    (jordanCfcHom_isometry a).injective (by
      rw [map_mul, hfb, hb, jordanCfcHom_id])
  have hfsqrt : f = jordanSpectrumSqrt a := by
    ext x
    have hsq := DFunLike.congr_fun hfsq x
    change f x = Real.sqrt (x : ℝ)
    change f x * f x = (x : ℝ) at hsq
    nlinarith [hf0 x, Real.sqrt_nonneg (x : ℝ),
      Real.mul_self_sqrt (nonneg_of_mem_jordanSpectrum ha x.property)]
  unfold jordanSqrt
  change ((jordanCfcHom a (jordanSpectrumSqrt a) : ClosedGeneratedByOne a) : E) = (b : E)
  rw [← hfb, ← hfsqrt]

/-- The absolute-value function on the intrinsic spectrum. -/
noncomputable def jordanSpectrumAbs (a : E) : C(jordanSpectrum a, ℝ) :=
  ⟨fun x => |x|, continuous_abs.comp continuous_subtype_val⟩

/-- The intrinsic absolute value of a JB observable. -/
noncomputable def jordanAbs [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) : E :=
  jordanCfc a (jordanSpectrumAbs a)

/-- Absolute value squares to the square of the observable. -/
theorem jordanAbs_mul_self [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    jordanAbs a * jordanAbs a = a * a := by
  unfold jordanAbs
  rw [← jordanCfc_mul]
  have habs : jordanSpectrumAbs a * jordanSpectrumAbs a =
      (ContinuousMap.restrict (jordanSpectrum a) (.id ℝ)) *
        ContinuousMap.restrict (jordanSpectrum a) (.id ℝ) := by
    ext x
    change |(x : ℝ)| * |(x : ℝ)| = (x : ℝ) * (x : ℝ)
    simp
  rw [habs, jordanCfc_mul, jordanCfc_id]

/-- Absolute value is nonnegative, witnessed by the CFC square-root of the absolute-value
function. -/
theorem jordanAbs_nonneg [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) : 0 ≤ jordanAbs a := by
  let rootAbs : C(jordanSpectrum a, ℝ) :=
    ⟨fun x => Real.sqrt |(x : ℝ)|, Real.continuous_sqrt.comp
      (continuous_abs.comp continuous_subtype_val)⟩
  apply jordanCfc_nonneg_of_eq_mul_self a (g := rootAbs)
  ext x
  change |(x : ℝ)| = Real.sqrt |(x : ℝ)| * Real.sqrt |(x : ℝ)|
  exact (Real.mul_self_sqrt (abs_nonneg (x : ℝ))).symm

/-- The intrinsic absolute value vanishes exactly at the zero observable.  The nontrivial
direction uses the JB zero-square criterion through `|a|² = a²`. -/
theorem jordanAbs_eq_zero_iff [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    jordanAbs a = 0 ↔ a = 0 := by
  constructor
  · intro h
    apply JBAlgebra.eq_zero_of_mul_self_eq_zero
    rw [← jordanAbs_mul_self, h, zero_mul]
  · rintro rfl
    apply JBAlgebra.eq_zero_of_mul_self_eq_zero
    rw [jordanAbs_mul_self, zero_mul]

/-- Absolute value fixes every positive observable.  Positivity first confines the intrinsic
spectrum to the nonnegative real line, so the pointwise absolute-value function is the identity. -/
theorem jordanAbs_eq_self_of_nonneg [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) (ha : 0 ≤ a) :
    jordanAbs a = a := by
  unfold jordanAbs
  have habs : jordanSpectrumAbs a = ContinuousMap.restrict (jordanSpectrum a) (.id ℝ) := by
    ext x
    change |(x : ℝ)| = (x : ℝ)
    exact abs_of_nonneg (nonneg_of_mem_jordanSpectrum ha x.property)
  rw [habs, jordanCfc_id]

/-- Positivity is exactly the fixed-point condition for intrinsic absolute value. -/
theorem jordanAbs_eq_self_iff_nonneg [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    jordanAbs a = a ↔ 0 ≤ a := by
  constructor
  · intro h
    rw [← h]
    exact jordanAbs_nonneg a
  · exact jordanAbs_eq_self_of_nonneg a

/-- The positive-part function on the intrinsic spectrum. -/
noncomputable def jordanSpectrumPosPart (a : E) : C(jordanSpectrum a, ℝ) :=
  ⟨fun x => max (x : ℝ) 0, continuous_subtype_val.max continuous_const⟩

/-- The negative-part function on the intrinsic spectrum. -/
noncomputable def jordanSpectrumNegPart (a : E) : C(jordanSpectrum a, ℝ) :=
  ⟨fun x => max (-(x : ℝ)) 0, continuous_subtype_val.neg.max continuous_const⟩

/-- The positive part of an intrinsic JB observable. -/
noncomputable def jordanPosPart [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) : E :=
  jordanCfc a (jordanSpectrumPosPart a)

/-- The negative part of an intrinsic JB observable. -/
noncomputable def jordanNegPart [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) : E :=
  jordanCfc a (jordanSpectrumNegPart a)

/-- Positive parts are nonnegative. -/
theorem jordanPosPart_nonneg [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    0 ≤ jordanPosPart a := by
  let rootPos : C(jordanSpectrum a, ℝ) :=
    ⟨fun x => Real.sqrt (max (x : ℝ) 0), Real.continuous_sqrt.comp
      (continuous_subtype_val.max continuous_const)⟩
  apply jordanCfc_nonneg_of_eq_mul_self a (g := rootPos)
  ext x
  change max (x : ℝ) 0 = Real.sqrt (max (x : ℝ) 0) * Real.sqrt (max (x : ℝ) 0)
  exact (Real.mul_self_sqrt (le_max_right _ _)).symm

/-- Negative parts are nonnegative. -/
theorem jordanNegPart_nonneg [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    0 ≤ jordanNegPart a := by
  let rootNeg : C(jordanSpectrum a, ℝ) :=
    ⟨fun x => Real.sqrt (max (-(x : ℝ)) 0), Real.continuous_sqrt.comp
      (continuous_subtype_val.neg.max continuous_const)⟩
  apply jordanCfc_nonneg_of_eq_mul_self a (g := rootNeg)
  ext x
  change max (-(x : ℝ)) 0 = Real.sqrt (max (-(x : ℝ)) 0) *
    Real.sqrt (max (-(x : ℝ)) 0)
  exact (Real.mul_self_sqrt (le_max_right _ _)).symm

/-- The positive part fixes a positive observable. -/
theorem jordanPosPart_eq_self_of_nonneg [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) (ha : 0 ≤ a) :
    jordanPosPart a = a := by
  unfold jordanPosPart
  rw [show jordanSpectrumPosPart a = ContinuousMap.restrict (jordanSpectrum a) (.id ℝ) by
    ext x
    change max (x : ℝ) 0 = (x : ℝ)
    exact max_eq_left (nonneg_of_mem_jordanSpectrum ha x.property), jordanCfc_id]

/-- The negative part of a positive observable vanishes. -/
theorem jordanNegPart_eq_zero_of_nonneg [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) (ha : 0 ≤ a) :
    jordanNegPart a = 0 := by
  unfold jordanNegPart
  rw [show jordanSpectrumNegPart a = 0 by
    ext x
    change max (-(x : ℝ)) 0 = 0
    exact max_eq_right (neg_nonpos.mpr (nonneg_of_mem_jordanSpectrum ha x.property)),
    jordanCfc_zero]

/-- The positive and negative parts reconstruct the observable. -/
theorem jordanPosPart_sub_jordanNegPart [Nontrivial E] [PartialOrder E]
    [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (a : E) : jordanPosPart a - jordanNegPart a = a := by
  unfold jordanPosPart jordanNegPart
  rw [← jordanCfc_sub]
  have hparts : jordanSpectrumPosPart a - jordanSpectrumNegPart a =
      ContinuousMap.restrict (jordanSpectrum a) (.id ℝ) := by
    ext x
    change max (x : ℝ) 0 - max (-(x : ℝ)) 0 = (x : ℝ)
    by_cases hx : 0 ≤ (x : ℝ)
    · rw [max_eq_left hx, max_eq_right (neg_nonpos.mpr hx)]
      ring
    · have hx' : (x : ℝ) ≤ 0 := le_of_not_ge hx
      rw [max_eq_right hx', max_eq_left (neg_nonneg.mpr hx')]
      ring
  rw [hparts, jordanCfc_id]

/-- Positivity is exactly the vanishing of the intrinsic negative part. -/
theorem jordanNegPart_eq_zero_iff_nonneg [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    jordanNegPart a = 0 ↔ 0 ≤ a := by
  constructor
  · intro h
    have hparts := jordanPosPart_sub_jordanNegPart a
    have hpos : jordanPosPart a = a := by simpa [h] using hparts
    rw [← hpos]
    exact jordanPosPart_nonneg a
  · exact jordanNegPart_eq_zero_of_nonneg a

/-- Nonpositivity is exactly the vanishing of the intrinsic positive part.  The reverse direction
uses the exact CFC order equivalence to turn `a ≤ 0` into the pointwise spectral inequality
`x ≤ 0`. -/
theorem jordanPosPart_eq_zero_iff_nonpos [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    jordanPosPart a = 0 ↔ a ≤ 0 := by
  constructor
  · intro h
    have hparts := jordanPosPart_sub_jordanNegPart a
    have ha : a = -jordanNegPart a := by simpa [h] using hparts.symm
    rw [ha]
    exact neg_nonpos.mpr (jordanNegPart_nonneg a)
  · intro ha
    have hCfc : jordanCfc a (ContinuousMap.restrict (jordanSpectrum a) (.id ℝ)) ≤
        jordanCfc a 0 := by
      rw [jordanCfc_id, jordanCfc_zero]
      exact ha
    have hpoint := (jordanCfc_le_iff a _ _).mp hCfc
    unfold jordanPosPart
    rw [show jordanSpectrumPosPart a = 0 by
      ext x
      change max (x : ℝ) 0 = 0
      exact max_eq_right (hpoint x), jordanCfc_zero]

/-- Absolute value is the sum of the positive and negative parts.  Together with
`jordanPosPart_sub_jordanNegPart`, this is the intrinsic one-observable Jordan decomposition. -/
theorem jordanAbs_eq_jordanPosPart_add_jordanNegPart [Nontrivial E] [PartialOrder E]
    [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (a : E) : jordanAbs a = jordanPosPart a + jordanNegPart a := by
  unfold jordanAbs jordanPosPart jordanNegPart
  rw [← jordanCfc_add]
  congr 1
  ext x
  change |(x : ℝ)| = max (x : ℝ) 0 + max (-(x : ℝ)) 0
  by_cases hx : 0 ≤ (x : ℝ)
  · rw [abs_of_nonneg hx, max_eq_left hx, max_eq_right (neg_nonpos.mpr hx)]
    ring
  · have hx' : (x : ℝ) ≤ 0 := le_of_not_ge hx
    rw [abs_of_nonpos hx', max_eq_right hx', max_eq_left (neg_nonneg.mpr hx')]
    ring

/-- The positive part is bounded by the intrinsic absolute value. -/
theorem jordanPosPart_le_jordanAbs [Nontrivial E] [PartialOrder E]
    [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (a : E) : jordanPosPart a ≤ jordanAbs a := by
  rw [jordanAbs_eq_jordanPosPart_add_jordanNegPart]
  exact le_add_of_nonneg_right (jordanNegPart_nonneg a)

/-- The negative part is bounded by the intrinsic absolute value. -/
theorem jordanNegPart_le_jordanAbs [Nontrivial E] [PartialOrder E]
    [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (a : E) : jordanNegPart a ≤ jordanAbs a := by
  rw [jordanAbs_eq_jordanPosPart_add_jordanNegPart]
  exact le_add_of_nonneg_left (jordanPosPart_nonneg a)

/-- An observable is bounded above by its intrinsic absolute value. -/
theorem le_jordanAbs [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    a ≤ jordanAbs a := by
  calc
    a = jordanPosPart a - jordanNegPart a := (jordanPosPart_sub_jordanNegPart a).symm
    _ = jordanPosPart a + -jordanNegPart a := sub_eq_add_neg _ _
    _ ≤ jordanPosPart a + jordanNegPart a :=
      add_le_add_right (neg_le_self (jordanNegPart_nonneg a)) _
    _ = jordanAbs a := (jordanAbs_eq_jordanPosPart_add_jordanNegPart a).symm

/-- The negative of an observable is bounded above by its intrinsic absolute value. -/
theorem neg_le_jordanAbs [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    -a ≤ jordanAbs a := by
  calc
    -a = -(jordanPosPart a - jordanNegPart a) := by
      rw [jordanPosPart_sub_jordanNegPart]
    _ = jordanNegPart a - jordanPosPart a := neg_sub _ _
    _ = jordanNegPart a + -jordanPosPart a := sub_eq_add_neg _ _
    _ ≤ jordanNegPart a + jordanPosPart a :=
      add_le_add_right (neg_le_self (jordanPosPart_nonneg a)) _
    _ = jordanAbs a := by
      rw [add_comm, (jordanAbs_eq_jordanPosPart_add_jordanNegPart a).symm]

/-- Positive and negative parts are Jordan-orthogonal. -/
theorem jordanPosPart_jordanOrthogonal_jordanNegPart [Nontrivial E] [PartialOrder E]
    [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (a : E) : JordanAlgebra.JordanOrthogonal (jordanPosPart a) (jordanNegPart a) := by
  unfold JordanAlgebra.JordanOrthogonal jordanPosPart jordanNegPart
  rw [← jordanCfc_mul]
  have horth : jordanSpectrumPosPart a * jordanSpectrumNegPart a = 0 := by
    ext x
    change max (x : ℝ) 0 * max (-(x : ℝ)) 0 = 0
    by_cases hx : 0 ≤ (x : ℝ)
    · rw [max_eq_right (neg_nonpos.mpr hx), mul_zero]
    · have hx' : (x : ℝ) ≤ 0 := le_of_not_ge hx
      rw [max_eq_right hx', zero_mul]
  rw [horth, jordanCfc_zero]

end NormedJordanAlgebra
