/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import PhyslibAlpha.AlgebraicFramework.JordanOrderUnit.Power.Ring
public import PhyslibAlpha.AlgebraicFramework.JordanOrderUnit.JB.Dynamics

/-!

# The closed subalgebra generated by a single element: `C_J(a)`

## i. Overview

Step 2 of `JB/GENERATED_SUBALGEBRA_ROADMAP.md`: `C_J(a) := \overline{J[a]}`, the norm-closure of
the subalgebra generated by `1` and `a` (`Power/GeneratedByOne.lean`). Continuity of the Jordan
product (`JB/Dynamics.lean`'s `isBoundedBilinearMap_mul`, itself just `norm_mul_le'` repackaged)
is exactly what lets the closure of a subalgebra remain a subalgebra: this is the standard
topological
argument "a continuous binary operation closed on a set is closed on the set's closure", via
`image_closure_subset_closure_image` and `closure_prod_eq`, not anything Jordan-specific.

Because `NormedJordanAlgebra` bundles coherent algebraic and normed data and `JBAlgebra` includes
completeness, this construction is abstract in an arbitrary JB-algebra. `C_J(a)` is a closed subset
of a complete space and is therefore complete.

## ii. Key definitions and results

- `NormedJordanAlgebra.closedGeneratedByOne`
- `NormedJordanAlgebra.mul_mem_closedGeneratedByOne`
- `NormedJordanAlgebra.isClosed_closedGeneratedByOne`
- `NormedJordanAlgebra.isComplete_closedGeneratedByOne`
- `NormedJordanAlgebra.assoc_of_mem_closedGeneratedByOne`
- `NormedJordanAlgebra.ClosedGeneratedByOne`

## iii. Table of contents

- A. The closure
- B. Closure under the Jordan product
- C. Completeness
- D. The bundled commutative normed algebra

-/

@[expose] public section

namespace NormedJordanAlgebra

variable {E : Type*} [NormedJordanAlgebra E]

open scoped JordanAlgebra

/-! ## A. The closure -/

/-- `C_J(a) := \overline{J[a]}`, the norm-closure of the subalgebra generated by `1` and `a`. -/
noncomputable def closedGeneratedByOne (a : E) : Submodule ℝ E :=
  (JordanAlgebra.generatedByOne a).topologicalClosure

theorem generatedByOne_le_closedGeneratedByOne (a : E) :
    JordanAlgebra.generatedByOne a ≤ closedGeneratedByOne a :=
  Submodule.le_topologicalClosure _

theorem one_mem_closedGeneratedByOne (a : E) :
    (1 : E) ∈ closedGeneratedByOne a :=
  generatedByOne_le_closedGeneratedByOne a (JordanAlgebra.one_mem_generatedByOne a)

theorem self_mem_closedGeneratedByOne (a : E) : a ∈ closedGeneratedByOne a :=
  generatedByOne_le_closedGeneratedByOne a (JordanAlgebra.self_mem_generatedByOne a)

/-! ## B. Closure under the Jordan product -/

/-- **The topological half of the reduction.** `C_J(a)` is closed under the Jordan product: a
continuous binary operation (`isBoundedBilinearMap_mul.continuous`) that is closed on `J[a]`
(`IsJordanOrderUnit.mul_mem_generatedByOne`) remains closed on `J[a]`'s closure. -/
theorem mul_mem_closedGeneratedByOne {a x y : E}
    (hx : x ∈ closedGeneratedByOne a) (hy : y ∈ closedGeneratedByOne a) :
    x * y ∈ closedGeneratedByOne a := by
  let S : Set E := JordanAlgebra.generatedByOne a
  have hclosed : IsClosed (closure S) := isClosed_closure
  have hleft : ∀ u ∈ S, u * y ∈ closure S := by
    intro u hu
    apply (closure_minimal ?_ (hclosed.preimage (NormedJordanAlgebra.continuous_mul_left u))) hy
    intro v hv
    exact subset_closure (JordanAlgebra.mul_mem_generatedByOne a hu hv)
  have hfinal : x * y ∈ closure S := by
    apply (closure_minimal hleft (hclosed.preimage (NormedJordanAlgebra.continuous_mul_right y))) hx
  show x * y ∈ (closedGeneratedByOne a : Set E)
  rw [closedGeneratedByOne, Submodule.topologicalClosure_coe]
  exact hfinal

/-- Associativity extends from `J[a]` to its closure. The proof extends the polynomial identity
successively in the third, second, and first variables, using continuity of multiplication. -/
theorem assoc_of_mem_closedGeneratedByOne (a : E) {x y z : E}
    (hx : x ∈ closedGeneratedByOne a) (hy : y ∈ closedGeneratedByOne a)
    (hz : z ∈ closedGeneratedByOne a) : (x * y) * z = x * (y * z) := by
  let S : Set E := JordanAlgebra.generatedByOne a
  have hx' : x ∈ closure S := by
    change x ∈ closure (JordanAlgebra.generatedByOne a : Set E) at hx
    simpa only [S] using hx
  have hy' : y ∈ closure S := by
    change y ∈ closure (JordanAlgebra.generatedByOne a : Set E) at hy
    simpa only [S] using hy
  have hz' : z ∈ closure S := by
    change z ∈ closure (JordanAlgebra.generatedByOne a : Set E) at hz
    simpa only [S] using hz
  have hbase {u v w : E} (hu : u ∈ S) (hv : v ∈ S) (hw : w ∈ S) :
      (u * v) * w = u * (v * w) := by
    let u' : JordanAlgebra.GeneratedByOne a := ⟨u, hu⟩
    let v' : JordanAlgebra.GeneratedByOne a := ⟨v, hv⟩
    let w' : JordanAlgebra.GeneratedByOne a := ⟨w, hw⟩
    exact congrArg Subtype.val (JordanAlgebra.GeneratedByOne.mul_assoc a u' v' w')
  have hclose_z {u v : E} (hu : u ∈ S) (hv : v ∈ S) :
      ∀ z ∈ closure S, (u * v) * z = u * (v * z) := by
    exact Set.EqOn.closure (fun _ hw => hbase hu hv hw)
      (continuous_mul_left (u * v))
      ((continuous_mul_left u).comp (continuous_mul_left v))
  have hclose_y {u z : E} (hu : u ∈ S) (hz : z ∈ closure S) :
      ∀ y ∈ closure S, (u * y) * z = u * (y * z) := by
    exact Set.EqOn.closure (fun _ hv => hclose_z hu hv z hz)
      ((continuous_mul_right z).comp (continuous_mul_left u))
      ((continuous_mul_left u).comp (continuous_mul_right z))
  exact Set.EqOn.closure (fun _ hu => hclose_y hu hz' y hy')
    ((continuous_mul_right z).comp (continuous_mul_right y))
    (continuous_mul_right (y * z)) hx'

/-! ## C. Completeness -/

/-- `C_J(a)` is closed, being a topological closure. -/
theorem isClosed_closedGeneratedByOne (a : E) :
    IsClosed (closedGeneratedByOne a : Set E) :=
  Submodule.isClosed_topologicalClosure _

variable [CompleteSpace E] in
/-- `C_J(a)` is complete whenever its ambient normed Jordan algebra is complete. -/
theorem isComplete_closedGeneratedByOne (a : E) :
    IsComplete (closedGeneratedByOne a : Set E) :=
  (isClosed_closedGeneratedByOne a).isComplete

/-! ## D. The bundled commutative normed algebra -/

/-- The norm-closed Jordan subalgebra generated by `1` and `a`, regarded as its own type. Although
the ambient multiplication need not be associative, its restriction to this subtype is. -/
abbrev ClosedGeneratedByOne (a : E) : Type _ := closedGeneratedByOne a

namespace ClosedGeneratedByOne

variable (a : E)

noncomputable instance : Mul (ClosedGeneratedByOne a) where
  mul x y := ⟨(x : E) * (y : E), mul_mem_closedGeneratedByOne x.2 y.2⟩

@[simp]
theorem val_mul (x y : ClosedGeneratedByOne a) :
    ((x * y : ClosedGeneratedByOne a) : E) = (x : E) * (y : E) := rfl

noncomputable instance : One (ClosedGeneratedByOne a) := ⟨⟨1, one_mem_closedGeneratedByOne a⟩⟩

@[simp]
theorem val_one : ((1 : ClosedGeneratedByOne a) : E) = 1 := rfl

/-- The closed one-generator algebra is a commutative associative ring. -/
noncomputable instance instCommRing : CommRing (ClosedGeneratedByOne a) where
  __ := (inferInstance : AddCommGroup (ClosedGeneratedByOne a))
  mul := (· * ·)
  mul_assoc x y z := Subtype.ext (assoc_of_mem_closedGeneratedByOne a x.2 y.2 z.2)
  one := 1
  one_mul x := Subtype.ext (_root_.one_mul (x : E))
  mul_one x := Subtype.ext (_root_.mul_one (x : E))
  left_distrib x y z := Subtype.ext (mul_add (x : E) (y : E) (z : E))
  right_distrib x y z := Subtype.ext (add_mul (x : E) (y : E) (z : E))
  mul_comm x y := Subtype.ext (_root_.mul_comm (x : E) (y : E))
  zero_mul x := Subtype.ext (by simp)
  mul_zero x := Subtype.ext (by simp)

/-- The closed one-generator algebra is an algebra over the real scalars inherited from `E`. -/
noncomputable instance instAlgebra : Algebra ℝ (ClosedGeneratedByOne a) where
  algebraMap :=
    { toFun := fun c => ⟨c • (1 : E), (closedGeneratedByOne a).smul_mem c
          (one_mem_closedGeneratedByOne a)⟩
      map_one' := Subtype.ext (one_smul ℝ 1)
      map_mul' := fun c d => Subtype.ext (by
        show (c * d) • (1 : E) = (c • (1 : E)) * (d • (1 : E))
        rw [mul_smul_comm, smul_mul_assoc, _root_.one_mul, smul_smul, _root_.mul_comm c d])
      map_zero' := Subtype.ext (by simp)
      map_add' := fun c d => Subtype.ext (by simp [add_smul]) }
  commutes' c x := Subtype.ext (_root_.mul_comm (c • (1 : E)) (x : E))
  smul c x := ⟨c • (x : E), (closedGeneratedByOne a).smul_mem c x.2⟩
  smul_def' c x := Subtype.ext (by
    show c • (x : E) = (c • (1 : E)) * (x : E)
    rw [smul_mul_assoc, _root_.one_mul])

/-- The inherited norm is submultiplicative on the closed generated algebra. -/
noncomputable instance instNormedRing : NormedRing (ClosedGeneratedByOne a) where
  __ : NormedAddCommGroup (ClosedGeneratedByOne a) := inferInstance
  __ : Ring (ClosedGeneratedByOne a) := inferInstance
  norm_mul_le x y := NormedJordanAlgebra.norm_mul_le (x : E) (y : E)

/-- The real algebra structure is compatible with the inherited norm. -/
noncomputable instance instNormedAlgebra : NormedAlgebra ℝ (ClosedGeneratedByOne a) where
  __ := instAlgebra a
  norm_smul_le r x := by simpa using norm_smul_le r (x : E)

/-- If `E` is complete, its closed generated subalgebra is complete. -/
noncomputable instance instCompleteSpace [CompleteSpace E] :
    CompleteSpace (ClosedGeneratedByOne a) :=
  (isClosed_closedGeneratedByOne a).completeSpace_coe

/-- Ordinary ring powers inside any closed one-generator algebra coerce to the ambient Jordan
power of the underlying element. This holds for `x` in the closed algebra generated by *any*
element `a`, not only for the canonical generator itself: both sides are computed by the same
recursive multiplication, so the identity does not depend on which enveloping closed algebra `x`
happens to be regarded as living in. This ambient-independence is exactly what lets a single
polynomial identity be transported between two different closed one-generator algebras sharing a
common element, which is the mechanism used for square-root uniqueness. -/
theorem pow_val (x : ClosedGeneratedByOne a) (n : ℕ) :
    ((x ^ n : ClosedGeneratedByOne a) : E) = (x : E) ^[n] := by
  induction n with
  | zero => simp [JordanAlgebra.jpow_zero]
  | succ n ih =>
      rw [pow_succ, val_mul, ih, JordanAlgebra.jpow_succ, _root_.mul_comm]

end ClosedGeneratedByOne

end NormedJordanAlgebra
