/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import PhyslibAlpha.AlgebraicFramework.JordanOrderUnit.JB.GeneratedByOne.Closed

/-!
# The inherited JB structure on a closed one-generator algebra

The closed algebra generated by one element is not merely a complete commutative normed algebra.
It inherits the ambient order, order unit, square positivity, and JB square-norm law.  This is the
proper abstract input for the real Gelfand theorem needed by the Jordan continuous functional
calculus: it retains the order information that distinguishes a formally real JB algebra from an
arbitrary real uniform Banach algebra.
-/

@[expose] public section

namespace JBAlgebra

variable {E : Type*} [NormedJordanAlgebra E] [JBAlgebra E]

open NormedJordanAlgebra

namespace ClosedGeneratedByOne

variable (a : E)

/-- The closed one-generator algebra inherits its ambient normed Jordan structure.  Associativity
is already supplied by `Closed.lean`; the remaining fields are restrictions of the ambient data. -/
noncomputable instance instNormedJordanAlgebra : NormedJordanAlgebra (ClosedGeneratedByOne a) where
  __ := NormedJordanAlgebra.ClosedGeneratedByOne.instCommRing a
  __ := (inferInstance : Norm (ClosedGeneratedByOne a))
  __ := (inferInstance : MetricSpace (ClosedGeneratedByOne a))
  __ := (inferInstance : Module ℝ (ClosedGeneratedByOne a))
  dist_eq x y := by
    change dist (x : E) (y : E) = ‖-(x : E) + (y : E)‖
    exact NormedJordanAlgebra.dist_eq (x : E) (y : E)
  norm_smul_le r x := by
    change ‖r • (x : E)‖ ≤ ‖r‖ * ‖(x : E)‖
    exact NormedJordanAlgebra.norm_smul_le r (x : E)
  smul_comm r x y := by
    apply Subtype.ext
    exact NormedJordanAlgebra.smul_comm r (x : E) (y : E)
  smul_assoc r x y := by
    apply Subtype.ext
    exact NormedJordanAlgebra.smul_assoc r (x : E) (y : E)
  jordan_identity x y := by
    exact mul_assoc x y (x * x)
  norm_mul_le x y := by
    change ‖(x : E) * (y : E)‖ ≤ ‖(x : E)‖ * ‖(y : E)‖
    exact NormedJordanAlgebra.norm_mul_le (x : E) (y : E)

/-- A nontrivial ambient algebra gives a nontrivial closed generated algebra, since it contains the
same unit. -/
noncomputable instance instNontrivial [Nontrivial E] : Nontrivial (ClosedGeneratedByOne a) where
  exists_pair_ne := by
    refine ⟨(0 : ClosedGeneratedByOne a), (1 : ClosedGeneratedByOne a), ?_⟩
    intro h
    have : (0 : E) = 1 := congrArg (fun x : ClosedGeneratedByOne a => (x : E)) h
    exact zero_ne_one this

/-- The inherited unit has norm one, as required by the Banach-algebra spectrum estimates. -/
noncomputable instance instNormOneClass [Nontrivial E] : NormOneClass (ClosedGeneratedByOne a) where
  norm_one := by
    have hsq : ‖(1 : E)‖ = ‖(1 : E)‖ ^ 2 := by
      rw [← JBAlgebra.norm_mul_self, one_mul]
    have hpos : 0 < ‖(1 : E)‖ := norm_pos_iff.mpr one_ne_zero
    have hfac : ‖(1 : E)‖ * (‖(1 : E)‖ - 1) = 0 := by
      nlinarith [hsq]
    rcases mul_eq_zero.mp hfac with hzero | hone
    · exact False.elim (ne_of_gt hpos hzero)
    · exact sub_eq_zero.mp hone

/-- The closed one-generator algebra is again a JB-algebra. The complete-space instance is the
closed-subspace instance established in `Closed.lean`; the two norm laws are inherited verbatim. -/
noncomputable instance instJBAlgebra : JBAlgebra (ClosedGeneratedByOne a) where
  norm_mul_self x := by
    change ‖(x : E) * (x : E)‖ = ‖(x : E)‖ ^ 2
    exact JBAlgebra.norm_mul_self (x : E)
  norm_mul_self_le_add x y := by
    change ‖(x : E) * (x : E)‖ ≤ ‖(x : E) * (x : E) + (y : E) * (y : E)‖
    exact JBAlgebra.norm_mul_self_le_add (x : E) (y : E)

section Ordered

variable [PartialOrder E] [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E]
  [PosSMulMono ℝ E] [IsJBOrderUnit E]

/-- Positive real scalars preserve the inherited order. -/
noncomputable instance instPosSMulMono : PosSMulMono ℝ (ClosedGeneratedByOne a) where
  smul_le_smul_of_nonneg_left {r} hr {x y} hxy := by
    change r • (x : E) ≤ r • (y : E)
    exact smul_le_smul_of_nonneg_left hxy hr

/-- The ambient order unit remains an order unit after restricting to the closed generated
subalgebra: each ambient bound is itself a scalar multiple of the same unit and hence lies in the
subalgebra. -/
noncomputable instance instIsOrderUnit : IsOrderUnit (ClosedGeneratedByOne a) where
  one_nonneg := by
    change (0 : E) ≤ 1
    exact IsOrderUnit.one_nonneg
  exists_nsmul_one_le x := by
    obtain ⟨n, hn⟩ := IsOrderUnit.exists_nsmul_one_le (x : E)
    refine ⟨n, ?_⟩
    change (x : E) ≤ n • (1 : E)
    exact hn

/-- Archimedeanness restricts along the closed generated subalgebra. -/
noncomputable instance instIsArchimedeanOrderUnit :
    IsArchimedeanOrderUnit (ClosedGeneratedByOne a) where
  le_zero_of_forall_pos_smul_one_le x hx := by
    change (x : E) ≤ 0
    apply IsArchimedeanOrderUnit.le_zero_of_forall_pos_smul_one_le (x : E)
    intro ε hε
    exact hx ε hε

/-- Square positivity restricts to the closed generated subalgebra. -/
noncomputable instance instIsJordanOrderUnit : IsJordanOrderUnit (ClosedGeneratedByOne a) where
  mul_self_nonneg x := by
    change (0 : E) ≤ (x : E) * (x : E)
    exact IsJordanOrderUnit.mul_self_nonneg (x : E)

/-- Exact norm/order compatibility is inherited by the closed one-generator algebra. -/
noncomputable instance instIsJBOrderUnit : IsJBOrderUnit (ClosedGeneratedByOne a) where
  norm_eq_orderUnitNorm x := by
    change ‖(x : E)‖ = IsArchimedeanOrderUnit.orderUnitNorm x
    rw [IsJBOrderUnit.norm_eq_orderUnitNorm (x : E)]
    congr 1

end Ordered

end ClosedGeneratedByOne

end JBAlgebra
