/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import PhyslibAlpha.AlgebraicFramework.JordanOrderUnit.JB.GeneratedByOne.Uniform
public import Mathlib.Combinatorics.Enumerative.Catalan.Basic
public import Mathlib.RingTheory.PowerSeries.Binomial

/-!
# Positive invertibility in a closed one-generator JB algebra

This is the analytic entry point for the intrinsic JB spectral theorem.  Everything in this file
lives in the commutative associative algebra `ClosedGeneratedByOne a`; no Cstar realization or
functional-calculus API is used.

The first lemma packages the geometric-series inverse in the form needed by order arguments.  The
next development will prove that a strict order lower bound supplies its norm hypothesis, and then
add the endpoint-valid binomial square-root series needed for the converse positive-unit result.
-/

@[expose] public section

namespace JBAlgebra

variable {E : Type*} [NormedJordanAlgebra E] [JBAlgebra E]

open NormedJordanAlgebra
open scoped Topology

namespace ClosedGeneratedByOne

variable (a : E)

/-- The intrinsic half-binomial candidate for `sqrt (1 - z)` in the closed associative algebra
generated by one JB observable. Its endpoint convergence is established by
`summable_norm_half_binomial`. -/
noncomputable def halfBinomialSqrt (z : ClosedGeneratedByOne a) : ClosedGeneratedByOne a :=
  ∑' n : ℕ, Ring.choose (1 / 2 : ℝ) n • (-z) ^ n

/-- The formal coefficient identity for the binomial square-root series.  Evaluation at `-z`
will give the algebraic identity `sqrt (1 - z)^2 = 1 - z`; the remaining analytic work is to
justify that endpoint evaluation in the complete generated-one algebra. -/
theorem binomial_half_series_sq :
    (PowerSeries.binomialSeries ℝ (1 / 2 : ℝ)) ^ 2 = 1 + PowerSeries.X := by
  rw [pow_two, ← PowerSeries.binomialSeries_add]
  norm_num
  simpa using (PowerSeries.binomialSeries_nat (R := ℝ) (A := ℝ) 1)

/-- The scalar telescoping identity behind endpoint summability of the half-binomial series. -/
theorem catalan_weight_telescopes (n : ℕ) :
    (catalan n : ℝ) / 4 ^ n =
      2 * ((Nat.centralBinom n : ℝ) / 4 ^ n -
        (Nat.centralBinom (n + 1) : ℝ) / 4 ^ (n + 1)) := by
  have hc : ((n + 1 : ℕ) : ℝ) * catalan n = Nat.centralBinom n := by
    exact_mod_cast succ_mul_catalan_eq_centralBinom n
  have hs : ((n + 1 : ℕ) : ℝ) * Nat.centralBinom (n + 1) =
      2 * (2 * n + 1 : ℕ) * Nat.centralBinom n := by
    exact_mod_cast Nat.succ_mul_centralBinom_succ n
  push_cast at hc hs
  have hn : (n : ℝ) + 1 ≠ 0 := by positivity
  have hs' : (Nat.centralBinom (n + 1) : ℝ) =
      2 * (2 * (n : ℝ) + 1) * catalan n := by
    apply (mul_left_cancel₀ hn)
    calc
      ((n : ℝ) + 1) * Nat.centralBinom (n + 1) =
          2 * (2 * (n : ℝ) + 1) * Nat.centralBinom n := hs
      _ = ((n : ℝ) + 1) * (2 * (2 * (n : ℝ) + 1) * catalan n) := by
        rw [← hc]
        ring
  rw [pow_succ]
  field_simp
  rw [hs', ← hc]
  ring

/-- The finite Catalan partial sums telescope, giving the uniform endpoint bound. -/
theorem sum_range_catalan_weight (N : ℕ) :
    ∑ n ∈ Finset.range N, (catalan n : ℝ) / 4 ^ n =
      2 * (1 - (Nat.centralBinom N : ℝ) / 4 ^ N) := by
  calc
    ∑ n ∈ Finset.range N, (catalan n : ℝ) / 4 ^ n =
        ∑ n ∈ Finset.range N, 2 * ((Nat.centralBinom n : ℝ) / 4 ^ n -
          (Nat.centralBinom (n + 1) : ℝ) / 4 ^ (n + 1)) := by
            apply Finset.sum_congr rfl
            intro n _
            exact catalan_weight_telescopes n
    _ = 2 * ∑ n ∈ Finset.range N, ((Nat.centralBinom n : ℝ) / 4 ^ n -
          (Nat.centralBinom (n + 1) : ℝ) / 4 ^ (n + 1)) := by rw [Finset.mul_sum]
    _ = 2 * (1 - (Nat.centralBinom N : ℝ) / 4 ^ N) := by
      induction N with
      | zero => norm_num
      | succ N ih =>
          rw [Finset.sum_range_succ, mul_add, ih]
          ring

/-- The Catalan weights at `1/4` are summable. -/
theorem summable_catalan_weight : Summable (fun n : ℕ ↦ (catalan n : ℝ) / 4 ^ n) := by
  apply summable_of_sum_range_le (c := 2)
  · intro n
    positivity
  · intro N
    rw [sum_range_catalan_weight]
    have hnonneg : 0 ≤ (Nat.centralBinom N : ℝ) / 4 ^ N := by positivity
    linarith

/-- Generalized binomial coefficients satisfy their usual one-step recurrence over the reals. -/
theorem choose_succ_recurrence (a : ℝ) (n : ℕ) :
    Ring.choose a (n + 1) = Ring.choose a n * (a - n) / (n + 1) := by
  rw [Ring.choose_eq_smul, Ring.choose_eq_smul]
  simp only [smul_eq_mul, descPochhammer_succ_right, Polynomial.smeval_mul,
    Polynomial.smeval_sub, Polynomial.smeval_X, Polynomial.smeval_natCast,
    Nat.factorial_succ, Nat.cast_mul, Nat.cast_add, Nat.cast_one]
  field_simp
  ring

/-- The Catalan successor recurrence in the real form matched to generalized binomial ratios. -/
theorem catalan_succ_recurrence (n : ℕ) :
    (catalan (n + 1) : ℝ) =
      2 * (2 * (n : ℝ) + 1) * catalan n / (n + 2) := by
  have hc : ((n + 1 : ℕ) : ℝ) * catalan n = Nat.centralBinom n := by
    exact_mod_cast succ_mul_catalan_eq_centralBinom n
  have hs : ((n + 1 : ℕ) : ℝ) * Nat.centralBinom (n + 1) =
      2 * (2 * n + 1 : ℕ) * Nat.centralBinom n := by
    exact_mod_cast Nat.succ_mul_centralBinom_succ n
  have hc' : ((n + 2 : ℕ) : ℝ) * catalan (n + 1) = Nat.centralBinom (n + 1) := by
    simpa [Nat.add_assoc] using
      (show (((n + 1) + 1 : ℕ) : ℝ) * catalan (n + 1) = Nat.centralBinom (n + 1) from
        (by exact_mod_cast succ_mul_catalan_eq_centralBinom (n + 1)))
  push_cast at hc hs hc'
  have hn : (n : ℝ) + 1 ≠ 0 := by positivity
  have hcentral : (Nat.centralBinom (n + 1) : ℝ) =
      2 * (2 * (n : ℝ) + 1) * catalan n := by
    apply (mul_left_cancel₀ hn)
    calc
      ((n : ℝ) + 1) * Nat.centralBinom (n + 1) =
          2 * (2 * (n : ℝ) + 1) * Nat.centralBinom n := hs
      _ = ((n : ℝ) + 1) * (2 * (2 * (n : ℝ) + 1) * catalan n) := by
        rw [← hc]
        ring
  rw [hcentral] at hc'
  field_simp
  nlinarith

/-- The exact signed half-binomial/Catalan identity.  Taking absolute values will provide the
scalar majorant for the endpoint binomial square-root series. -/
theorem choose_half_succ_eq_catalan (n : ℕ) :
    Ring.choose (1 / 2 : ℝ) (n + 1) =
      (-1 : ℝ) ^ n * (catalan n : ℝ) / (2 * 4 ^ n) := by
  induction n with
  | zero => norm_num [Ring.choose_one_right, catalan_zero]
  | succ n ih =>
      rw [show n + 1 + 1 = (n + 1) + 1 by omega,
        choose_succ_recurrence, ih, catalan_succ_recurrence, pow_succ]
      push_cast
      field_simp
      ring

/-- The absolute half-binomial coefficients are the Catalan endpoint weights. -/
theorem abs_choose_half_succ_eq_catalan (n : ℕ) :
    |Ring.choose (1 / 2 : ℝ) (n + 1)| = (catalan n : ℝ) / (2 * 4 ^ n) := by
  have hcat : 0 ≤ (catalan n : ℝ) := by positivity
  rw [choose_half_succ_eq_catalan, abs_div, abs_mul, abs_pow]
  norm_num [abs_of_nonneg hcat]

/-- The half-binomial coefficients are absolutely summable at the endpoint. -/
theorem summable_abs_choose_half : Summable (fun n : ℕ ↦ |Ring.choose (1 / 2 : ℝ) n|) := by
  apply (summable_nat_add_iff 1).mp
  have h := (summable_catalan_weight.mul_left (1 / 2 : ℝ))
  refine h.congr ?_
  intro n
  rw [abs_choose_half_succ_eq_catalan]
  ring

/-- The endpoint half-binomial series is absolutely summable in every closed one-generator JB
algebra on the closed unit ball. -/
theorem summable_norm_half_binomial [Nontrivial E] (z : ClosedGeneratedByOne a) (hz : ‖z‖ ≤ 1) :
    Summable (fun n : ℕ ↦ ‖Ring.choose (1 / 2 : ℝ) n • (-z) ^ n‖) := by
  apply summable_abs_choose_half.of_nonneg_of_le (fun n ↦ norm_nonneg _)
  intro n
  have hzneg : ‖-z‖ ≤ 1 := by simpa using hz
  calc
    ‖Ring.choose (1 / 2 : ℝ) n • (-z) ^ n‖ =
        |Ring.choose (1 / 2 : ℝ) n| * ‖(-z) ^ n‖ := by rw [norm_smul, Real.norm_eq_abs]
    _ ≤ |Ring.choose (1 / 2 : ℝ) n| * ‖-z‖ ^ n :=
      mul_le_mul_of_nonneg_left (norm_pow_le _ _) (abs_nonneg _)
    _ ≤ |Ring.choose (1 / 2 : ℝ) n| * 1 :=
      mul_le_mul_of_nonneg_left (pow_le_one₀ (norm_nonneg _) hzneg) (abs_nonneg _)
    _ = |Ring.choose (1 / 2 : ℝ) n| := mul_one _

/-- The defining series for `halfBinomialSqrt` is summable on the closed unit ball. -/
theorem halfBinomialSqrt_summable [Nontrivial E] (z : ClosedGeneratedByOne a) (hz : ‖z‖ ≤ 1) :
    Summable (fun n : ℕ ↦ Ring.choose (1 / 2 : ℝ) n • (-z) ^ n) :=
  (summable_norm_half_binomial a z hz).of_norm

omit [JBAlgebra E] in
/-- The `n`th Cauchy-product coefficient of the evaluated half-binomial series.  This is the
formal binomial identity transported to the associative algebra generated by the single Jordan
element `a`. -/
theorem halfBinomialSqrt_antidiagonal (z : ClosedGeneratedByOne a) (n : ℕ) :
    ∑ kl ∈ Finset.antidiagonal n,
      (Ring.choose (1 / 2 : ℝ) kl.1 • (-z) ^ kl.1) *
        (Ring.choose (1 / 2 : ℝ) kl.2 • (-z) ^ kl.2) =
      ((if n = 0 then (1 : ℝ) else 0) + if n = 1 then 1 else 0) • (-z) ^ n := by
  have hcoeff := congrArg (fun p : PowerSeries ℝ ↦ p.coeff n) binomial_half_series_sq
  have hscalar :
      ∑ kl ∈ Finset.antidiagonal n,
        Ring.choose (1 / 2 : ℝ) kl.1 * Ring.choose (1 / 2 : ℝ) kl.2 =
        (if n = 0 then (1 : ℝ) else 0) + if n = 1 then 1 else 0 := by
    simpa only [pow_two, PowerSeries.coeff_mul, PowerSeries.binomialSeries_coeff,
      smul_eq_mul, mul_one, map_add, PowerSeries.coeff_one, PowerSeries.coeff_X] using hcoeff
  calc
    ∑ kl ∈ Finset.antidiagonal n,
        (Ring.choose (1 / 2 : ℝ) kl.1 • (-z) ^ kl.1) *
          (Ring.choose (1 / 2 : ℝ) kl.2 • (-z) ^ kl.2) =
        ∑ kl ∈ Finset.antidiagonal n,
          (Ring.choose (1 / 2 : ℝ) kl.1 * Ring.choose (1 / 2 : ℝ) kl.2) •
            ((-z) ^ kl.1 * (-z) ^ kl.2) := by
          apply Finset.sum_congr rfl
          intro kl _
          rw [smul_mul_assoc, mul_smul_comm, ← smul_smul]
    _ = ∑ kl ∈ Finset.antidiagonal n,
          (Ring.choose (1 / 2 : ℝ) kl.1 * Ring.choose (1 / 2 : ℝ) kl.2) • (-z) ^ n := by
          apply Finset.sum_congr rfl
          intro kl hkl
          rw [Finset.mem_antidiagonal] at hkl
          rw [← hkl, pow_add]
    _ = (∑ kl ∈ Finset.antidiagonal n,
          Ring.choose (1 / 2 : ℝ) kl.1 * Ring.choose (1 / 2 : ℝ) kl.2) • (-z) ^ n := by
          rw [Finset.sum_smul]
    _ = _ := by rw [hscalar]

/-- The endpoint-valid intrinsic binomial square-root identity.  Absolute convergence, proved
from the Catalan majorant above, licenses the Cauchy product; the formal coefficient calculation
then collapses that product to `1 - z`. -/
theorem halfBinomialSqrt_mul_self [Nontrivial E] (z : ClosedGeneratedByOne a) (hz : ‖z‖ ≤ 1) :
    halfBinomialSqrt a z * halfBinomialSqrt a z = 1 - z := by
  unfold halfBinomialSqrt
  rw [tsum_mul_tsum_eq_tsum_sum_antidiagonal_of_summable_norm
    (summable_norm_half_binomial a z hz) (summable_norm_half_binomial a z hz)]
  simp_rw [halfBinomialSqrt_antidiagonal a z]
  rw [tsum_eq_sum (s := ({0, 1} : Finset ℕ))]
  · norm_num [sub_eq_add_neg]
  · intro n hn
    simp only [Finset.mem_insert, Finset.mem_singleton] at hn
    have hn0 : n ≠ 0 := fun h ↦ hn (Or.inl h)
    have hn1 : n ≠ 1 := fun h ↦ hn (Or.inr h)
    simp [hn0, hn1]

/-- Local exact-cone direction: every nonnegative element of the closed associative algebra
generated by one JB element is a square.  This is the intrinsic endpoint square-root argument;
no representation or pre-existing functional calculus is involved. -/
theorem exists_mul_self_of_nonneg [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (y : ClosedGeneratedByOne a) (hy : 0 ≤ y) : ∃ s : ClosedGeneratedByOne a, s * s = y := by
  let M : ℝ := ‖y‖ + 1
  have hM : 0 < M := by
    dsimp [M]
    positivity
  have hMne : M ≠ 0 := ne_of_gt hM
  have hy_norm : ‖y‖ < M := by
    dsimp [M]
    linarith [norm_nonneg y]
  have hy_upper : y ≤ M • (1 : ClosedGeneratedByOne a) :=
    (JBAlgebra.norm_le_iff_order_bounds (x := y) (r := M) hM.le).mp hy_norm.le |>.2
  let z : ClosedGeneratedByOne a := 1 - M⁻¹ • y
  have hscaled : M⁻¹ • y ≤ (1 : ClosedGeneratedByOne a) := by
    have := smul_le_smul_of_nonneg_left hy_upper (inv_pos.mpr hM).le
    simpa [smul_smul, hMne] using this
  have hz_nonneg : 0 ≤ z := sub_nonneg.mpr hscaled
  have hz_upper : z ≤ (1 : ClosedGeneratedByOne a) := by
    dsimp [z]
    exact sub_le_self _ (smul_nonneg (inv_pos.mpr hM).le hy)
  have hz_lower : -(1 : ClosedGeneratedByOne a) ≤ z := by
    calc
      -(1 : ClosedGeneratedByOne a) ≤ 0 := neg_nonpos.mpr IsOrderUnit.one_nonneg
      _ ≤ z := hz_nonneg
  have hz_norm : ‖z‖ ≤ 1 :=
    (JBAlgebra.norm_le_iff_order_bounds (x := z) (r := 1) zero_le_one).mpr
      ⟨by simpa using hz_lower, by simpa using hz_upper⟩
  let r : ClosedGeneratedByOne a := halfBinomialSqrt a z
  refine ⟨Real.sqrt M • r, ?_⟩
  calc
    (Real.sqrt M • r) * (Real.sqrt M • r) = (Real.sqrt M * Real.sqrt M) • (r * r) := by
      rw [smul_mul_assoc, mul_smul_comm, ← smul_smul]
    _ = M • (r * r) := by rw [Real.mul_self_sqrt hM.le]
    _ = M • (1 - z) := by rw [show r * r = 1 - z by exact halfBinomialSqrt_mul_self a z hz_norm]
    _ = y := by
      simp [z, smul_smul, hMne]

/-- The local exact-cone theorem for a closed one-generator ordered JB algebra. -/
theorem nonneg_iff_exists_mul_self [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (y : ClosedGeneratedByOne a) : 0 ≤ y ↔ ∃ s : ClosedGeneratedByOne a, s * s = y := by
  constructor
  · exact exists_mul_self_of_nonneg a y
  · rintro ⟨s, rfl⟩
    exact IsJordanOrderUnit.mul_self_nonneg s

/-- A nonnegative unit lies in the order interior.  The proof first reconstructs squares from
the local exact cone, and then transfers the order bound for its positive inverse through the
commutative one-generator algebra. -/
theorem exists_pos_smul_one_le_of_isUnit_of_nonneg [Nontrivial E] [PartialOrder E]
    [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    {y : ClosedGeneratedByOne a} (hy : IsUnit y) (hy_nonneg : 0 ≤ y) :
    ∃ ε : ℝ, 0 < ε ∧ ε • (1 : ClosedGeneratedByOne a) ≤ y := by
  obtain ⟨s, hs⟩ := exists_mul_self_of_nonneg a y hy_nonneg
  have hs_unit : IsUnit s := by
    apply isUnit_mul_self_iff.mp
    simpa [hs] using hy
  let v : ClosedGeneratedByOne a := ↑(hs_unit.unit⁻¹)
  let t : ClosedGeneratedByOne a := v * v
  have ht_nonneg : 0 ≤ t := IsJordanOrderUnit.mul_self_nonneg v
  have ht_mul : t * y = 1 := by
    rw [← hs]
    calc
      (v * v) * (s * s) = (v * s) * (v * s) := by ring
      _ = 1 := by rw [show v * s = 1 by exact IsUnit.val_inv_mul hs_unit]; simp
  let M : ℝ := ‖t‖ + 1
  have hM : 0 < M := by
    dsimp [M]
    positivity
  have hMne : M ≠ 0 := ne_of_gt hM
  have ht_upper : t ≤ M • (1 : ClosedGeneratedByOne a) :=
    (JBAlgebra.norm_le_iff_order_bounds (x := t) (r := M) hM.le).mp (by
      dsimp [M]
      linarith [norm_nonneg t]) |>.2
  obtain ⟨q, hq⟩ := exists_mul_self_of_nonneg a (M • (1 : ClosedGeneratedByOne a) - t)
    (sub_nonneg.mpr ht_upper)
  have hmy_nonneg : 0 ≤ M • y - 1 := by
    calc
      M • y - 1 = (M • (1 : ClosedGeneratedByOne a) - t) * y := by
        rw [sub_mul, smul_mul_assoc, ht_mul]
        simp
      _ = (q * s) * (q * s) := by rw [← hq, ← hs]; ring
      _ ≥ 0 := IsJordanOrderUnit.mul_self_nonneg (q * s)
  refine ⟨M⁻¹, inv_pos.mpr hM, ?_⟩
  have hmy : (1 : ClosedGeneratedByOne a) ≤ M • y := sub_nonneg.mp hmy_nonneg
  have := smul_le_smul_of_nonneg_left hmy (inv_pos.mpr hM).le
  simpa [smul_smul, hMne] using this

/-- At the two norm endpoints of a one-generator JB observable, at least one order-positive
element is on the boundary of the cone.  This is the cone-boundary core of real spectrality. -/
theorem not_isUnit_norm_smul_one_sub_and_add [Nontrivial E] [PartialOrder E]
    [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (x : ClosedGeneratedByOne a) :
    ¬ (IsUnit (‖x‖ • (1 : ClosedGeneratedByOne a) - x) ∧
      IsUnit (‖x‖ • (1 : ClosedGeneratedByOne a) + x)) := by
  intro hunit
  have hbounds :=
    (JBAlgebra.norm_le_iff_order_bounds (x := x) (r := ‖x‖) (norm_nonneg x)).mp le_rfl
  have hplus_nonneg : 0 ≤ ‖x‖ • (1 : ClosedGeneratedByOne a) - x :=
    sub_nonneg.mpr hbounds.2
  have hminus_nonneg : 0 ≤ ‖x‖ • (1 : ClosedGeneratedByOne a) + x := by
    have hneg : -x ≤ ‖x‖ • (1 : ClosedGeneratedByOne a) := by
      simpa using neg_le_neg hbounds.1
    simpa [sub_eq_add_neg] using sub_nonneg.mpr hneg
  obtain ⟨εp, hεp, hp⟩ :=
    exists_pos_smul_one_le_of_isUnit_of_nonneg a hunit.1 hplus_nonneg
  obtain ⟨εm, hεm, hm⟩ :=
    exists_pos_smul_one_le_of_isUnit_of_nonneg a hunit.2 hminus_nonneg
  have hr : 0 < ‖x‖ := by
    by_contra hnr
    have hr0 : ‖x‖ = 0 := le_antisymm (le_of_not_gt hnr) (norm_nonneg x)
    have hx0 : x = 0 := norm_eq_zero.mp hr0
    exact (not_isUnit_zero : ¬ IsUnit (0 : ClosedGeneratedByOne a))
      (by simpa [hr0, hx0] using hunit.1)
  let δ : ℝ := min (‖x‖ / 2) (min εp εm)
  have hδ : 0 < δ := lt_min (by linarith) (lt_min hεp hεm)
  have hδhalf : δ ≤ ‖x‖ / 2 := min_le_left _ _
  have hδp : δ ≤ εp := le_trans (min_le_right _ _) (min_le_left _ _)
  have hδm : δ ≤ εm := le_trans (min_le_right _ _) (min_le_right _ _)
  have hnonneg : 0 ≤ ‖x‖ - δ := by linarith
  have hupperp : x ≤ (‖x‖ - εp) • (1 : ClosedGeneratedByOne a) := by
    calc
      x = ‖x‖ • (1 : ClosedGeneratedByOne a) -
          (‖x‖ • (1 : ClosedGeneratedByOne a) - x) := by abel
      _ ≤ ‖x‖ • (1 : ClosedGeneratedByOne a) - εp • (1 : ClosedGeneratedByOne a) :=
        sub_le_sub_left hp _
      _ = (‖x‖ - εp) • (1 : ClosedGeneratedByOne a) := by rw [sub_smul]
  have hupper : x ≤ (‖x‖ - δ) • (1 : ClosedGeneratedByOne a) :=
    hupperp.trans <| smul_le_smul_of_nonneg_right (sub_le_sub_left hδp _) IsOrderUnit.one_nonneg
  have hlowerm : -((‖x‖ - εm) • (1 : ClosedGeneratedByOne a)) ≤ x := by
    calc
      -((‖x‖ - εm) • (1 : ClosedGeneratedByOne a)) =
          εm • (1 : ClosedGeneratedByOne a) - ‖x‖ • (1 : ClosedGeneratedByOne a) := by module
      _ ≤ x := (sub_le_iff_le_add).mpr (by simpa [add_comm] using hm)
  have hscalar : -(‖x‖ - δ) ≤ -(‖x‖ - εm) :=
    neg_le_neg (sub_le_sub_left hδm _)
  have hlower : -((‖x‖ - δ) • (1 : ClosedGeneratedByOne a)) ≤ x := by
    calc
      -((‖x‖ - δ) • (1 : ClosedGeneratedByOne a)) =
          (-(‖x‖ - δ)) • (1 : ClosedGeneratedByOne a) := by rw [neg_smul]
      _ ≤ (-(‖x‖ - εm)) • (1 : ClosedGeneratedByOne a) :=
        smul_le_smul_of_nonneg_right hscalar IsOrderUnit.one_nonneg
      _ = -((‖x‖ - εm) • (1 : ClosedGeneratedByOne a)) := by rw [neg_smul]
      _ ≤ x := hlowerm
  have hnorm : ‖x‖ ≤ ‖x‖ - δ :=
    (JBAlgebra.norm_le_iff_order_bounds (x := x) (r := ‖x‖ - δ) hnonneg).mpr
      ⟨by simpa using hlower, hupper⟩
  linarith

omit [JBAlgebra E] in
/-- The completion step for the endpoint binomial construction: if partial square roots converge
and their squares converge to the target, the limit is an actual square root. -/
theorem exists_mul_self_of_tendsto_square {y : ClosedGeneratedByOne a}
    (s : ℕ → ClosedGeneratedByOne a) {r : ClosedGeneratedByOne a}
    (hs : Filter.Tendsto s Filter.atTop (𝓝 r))
    (hys : Filter.Tendsto (fun n ↦ s n * s n) Filter.atTop (𝓝 y)) :
    ∃ r : ClosedGeneratedByOne a, r * r = y := by
  refine ⟨r, ?_⟩
  exact tendsto_nhds_unique (hs.mul hs) hys

/-- An element in the closed one-generator algebra is invertible whenever its distance from the
unit is strictly below one.  This is the geometric-series step in the strict-positive-implies-unit
direction of the intrinsic JB spectral argument. -/
theorem isUnit_of_norm_one_sub_lt (y : ClosedGeneratedByOne a) (hy : ‖1 - y‖ < 1) : IsUnit y := by
  have hunit : IsUnit (1 - (1 - y)) := isUnit_one_sub_of_norm_lt_one hy
  simpa using hunit

/-- A strict order lower bound makes an element of a closed one-generator ordered JB algebra a
unit.  The proof is intrinsic: rescale into the open unit ball using the B1 norm/order theorem,
then use the geometric series for `1 - z`. -/
theorem isUnit_of_strictly_positive [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    {y : ClosedGeneratedByOne a} {ε : ℝ} (hε : 0 < ε) (hy : ε • (1 : ClosedGeneratedByOne a) ≤ y) :
    IsUnit y := by
  let M : ℝ := ‖y‖ + ε + 1
  have hM : 0 < M := by
    dsimp [M]
    positivity
  have hMne : M ≠ 0 := ne_of_gt hM
  have hyMnorm : ‖y‖ < M := by
    dsimp [M]
    linarith [norm_nonneg y, hε]
  have hyM : y ≤ M • (1 : ClosedGeneratedByOne a) :=
    (JBAlgebra.norm_le_iff_order_bounds (x := y) (r := M) hM.le).mp hyMnorm.le |>.2
  have hinvM : 0 ≤ M⁻¹ := (inv_pos.mpr hM).le
  have hscaled_lower := smul_le_smul_of_nonneg_left hy hinvM
  have hscaled_lower' : (ε / M) • (1 : ClosedGeneratedByOne a) ≤ M⁻¹ • y := by
    simpa [div_eq_mul_inv, smul_smul, mul_comm, mul_left_comm] using hscaled_lower
  have hscaled_upper := smul_le_smul_of_nonneg_left hyM hinvM
  have hscaled_upper' : M⁻¹ • y ≤ (1 : ClosedGeneratedByOne a) := by
    simpa [smul_smul, hMne] using hscaled_upper
  let z : ClosedGeneratedByOne a := 1 - M⁻¹ • y
  have hz_nonneg : 0 ≤ z := sub_nonneg.mpr hscaled_upper'
  have hz_upper : z ≤ (1 - ε / M) • (1 : ClosedGeneratedByOne a) := by
    simpa [z, sub_smul] using sub_le_sub_left hscaled_lower' 1
  have hεM : ε / M < 1 := by
    apply (div_lt_one₀ hM).mpr
    dsimp [M]
    linarith [norm_nonneg (y : E), hε]
  have hc_nonneg : 0 ≤ 1 - ε / M := (sub_pos.mpr hεM).le
  have hz_lower : -((1 - ε / M) • (1 : ClosedGeneratedByOne a)) ≤ z := by
    calc
      -((1 - ε / M) • (1 : ClosedGeneratedByOne a)) ≤ 0 :=
        neg_nonpos.mpr (smul_nonneg hc_nonneg IsOrderUnit.one_nonneg)
      _ ≤ z := hz_nonneg
  have hz_norm : ‖z‖ < 1 :=
    lt_of_le_of_lt
      ((JBAlgebra.norm_le_iff_order_bounds (x := z) (r := 1 - ε / M) hc_nonneg).mpr
        ⟨hz_lower, hz_upper⟩) (sub_lt_self 1 (div_pos hε hM))
  have hunit : IsUnit (1 - z) := isUnit_one_sub_of_norm_lt_one hz_norm
  have hscaled_unit : IsUnit (M • (1 - z)) := by
    simpa using IsUnit.smul (Units.mk0 M hMne) hunit
  have hy_eq : M • (1 - z) = y := by
    simp [z, smul_smul, hMne]
  exact hy_eq ▸ hscaled_unit

/-- The order interior of the local positive cone is exactly its positive unit locus.  This is
the form of B2 used by the cone-boundary proof of the real JB spectral theorem. -/
theorem isUnit_iff_mem_interior_positiveCone [Nontrivial E] [PartialOrder E]
    [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    {y : ClosedGeneratedByOne a} (hy : 0 ≤ y) :
    IsUnit y ↔ ∃ ε : ℝ, 0 < ε ∧ ε • (1 : ClosedGeneratedByOne a) ≤ y := by
  constructor
  · exact fun hu ↦ exists_pos_smul_one_le_of_isUnit_of_nonneg a hu hy
  · rintro ⟨ε, hε, hεy⟩
    exact isUnit_of_strictly_positive a hε hεy

/-- A completed square with nonzero scalar remainder is a unit.  This is the local real-quadratic
lemma needed for reverse polynomial spectral mapping: irreducible real quadratic factors evaluate
to strictly positive units in the generated-one algebra. -/
theorem isUnit_mul_self_sub_smul_one_add_sq_smul_one [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (x : ClosedGeneratedByOne a) (c d : ℝ) (hd : d ≠ 0) :
    IsUnit ((x - c • (1 : ClosedGeneratedByOne a)) * (x - c • (1 : ClosedGeneratedByOne a)) +
      d ^ 2 • (1 : ClosedGeneratedByOne a)) := by
  apply isUnit_of_strictly_positive a (sq_pos_of_ne_zero hd)
  exact le_add_of_nonneg_left (IsJordanOrderUnit.mul_self_nonneg _)

/-- Polynomial-evaluation form of the completed-square unit lemma. -/
theorem isUnit_aeval_completed_square [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (x : ClosedGeneratedByOne a) (c d : ℝ) (hd : d ≠ 0) :
    IsUnit (Polynomial.aeval x ((Polynomial.X - Polynomial.C c) ^ 2 + Polynomial.C (d ^ 2))) := by
  simpa [map_add, map_pow, map_sub, Polynomial.aeval_X, Polynomial.aeval_C,
    Algebra.algebraMap_eq_smul_one, pow_two, ← smul_smul] using
    isUnit_mul_self_sub_smul_one_add_sq_smul_one a x c d hd

/-- If a unit is presented as a Jordan square, it has a positive inverse witness.  This is the
algebraic half of the positive-unit direction; the endpoint square-root construction will supply
the square witness for an arbitrary positive element. -/
theorem exists_nonneg_inverse_of_mul_self_isUnit [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    {s : ClosedGeneratedByOne a} (hs : IsUnit (s * s)) :
    ∃ t : ClosedGeneratedByOne a, 0 ≤ t ∧ t * (s * s) = 1 := by
  have hus : IsUnit s := isUnit_mul_self_iff.mp hs
  let v : ClosedGeneratedByOne a := ↑(hus.unit⁻¹)
  refine ⟨v * v, IsJordanOrderUnit.mul_self_nonneg v, ?_⟩
  calc
    (v * v) * (s * s) = (v * s) * (v * s) := by ring
    _ = 1 := by rw [show v * s = 1 by exact IsUnit.val_inv_mul hus]; simp

end ClosedGeneratedByOne

end JBAlgebra
