/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import PhyslibAlpha.AlgebraicFramework.JordanOrderUnit.JB.GeneratedByOne.Closed
public import PhyslibAlpha.AlgebraicFramework.JordanOrderUnit.JB.GeneratedByOne.Inherited
public import PhyslibAlpha.AlgebraicFramework.JordanOrderUnit.JB.GeneratedByOne.PosInvertibility
public import Mathlib.Analysis.Normed.Algebra.Spectrum
public import Mathlib.Analysis.Polynomial.Factorization

/-!

# The canonical spectrum of one Jordan element

## i. Overview

The closed subalgebra generated by one element is an ordinary commutative associative normed real
algebra. Its usual algebraic spectrum therefore gives a canonical spectrum for that Jordan
element—there is no arbitrary set parameter and no dependence on a chosen Cstar realization.

This is the sound domain for the eventual continuous functional calculus. The map from continuous
functions is intentionally not postulated here: its construction requires the JB spectral theorem.

## ii. Key definitions and results

- `NormedJordanAlgebra.closedGenerator`
- `NormedJordanAlgebra.jordanSpectrum`
- `NormedJordanAlgebra.isCompact_jordanSpectrum`

## iii. Table of contents

- A. The generator in its closed algebra
- B. The canonical spectrum

-/

@[expose] public section

namespace NormedJordanAlgebra

variable {E : Type*} [NormedJordanAlgebra E]

/-! ## A. The generator in its closed algebra -/

/-- The element `a`, bundled as an element of its own closed generated subalgebra. -/
noncomputable def closedGenerator (a : E) : ClosedGeneratedByOne a :=
  ⟨a, self_mem_closedGeneratedByOne a⟩

@[simp]
theorem closedGenerator_val (a : E) : ((closedGenerator a : ClosedGeneratedByOne a) : E) = a :=
  rfl

/-! ## B. The canonical spectrum -/

/-- The canonical real spectrum of a Jordan element: its ordinary spectrum inside the closed
commutative associative algebra generated by that element. -/
noncomputable def jordanSpectrum (a : E) : Set ℝ :=
  spectrum ℝ (closedGenerator a)

/-- The canonical spectrum of the zero observable is the singleton `{0}`. -/
theorem jordanSpectrum_zero [Nontrivial E] : jordanSpectrum (0 : E) = ({0} : Set ℝ) := by
  let : Nontrivial (ClosedGeneratedByOne (0 : E)) :=
    { exists_pair_ne := by
        refine ⟨(0 : ClosedGeneratedByOne (0 : E)), (1 : ClosedGeneratedByOne (0 : E)), ?_⟩
        intro h
        exact zero_ne_one (congrArg (fun x : ClosedGeneratedByOne (0 : E) => (x : E)) h) }
  change spectrum ℝ (0 : ClosedGeneratedByOne (0 : E)) = ({0} : Set ℝ)
  exact spectrum.zero_eq (𝕜 := ℝ) (A := ClosedGeneratedByOne (0 : E))

/-- Scalar multiples of the order unit have the expected singleton canonical spectrum. -/
theorem jordanSpectrum_smul_one [Nontrivial E] (r : ℝ) :
    jordanSpectrum (r • (1 : E)) = ({r} : Set ℝ) := by
  let : Nontrivial (ClosedGeneratedByOne (r • (1 : E))) :=
    { exists_pair_ne := by
        refine ⟨(0 : ClosedGeneratedByOne (r • (1 : E))),
          (1 : ClosedGeneratedByOne (r • (1 : E))), ?_⟩
        intro h
        exact zero_ne_one (congrArg
          (fun x : ClosedGeneratedByOne (r • (1 : E)) => (x : E)) h) }
  change spectrum ℝ (r • (1 : ClosedGeneratedByOne (r • (1 : E)))) = ({r} : Set ℝ)
  rw [← Algebra.algebraMap_eq_smul_one]
  exact spectrum.scalar_eq r

/-- Polynomial spectral mapping is exact on scalar-unit observables. -/
theorem jordanSpectrum_polynomial_smul_one [Nontrivial E] (r : ℝ) (p : Polynomial ℝ) :
    (fun x => p.eval x) '' jordanSpectrum (r • (1 : E)) = ({p.eval r} : Set ℝ) := by
  rw [jordanSpectrum_smul_one r, Set.image_singleton]

/-- The canonical Jordan spectrum is compact. -/
theorem isCompact_jordanSpectrum [CompleteSpace E] (a : E) : IsCompact (jordanSpectrum a) :=
  spectrum.isCompact (closedGenerator a)

/-- The algebraic half of polynomial spectral mapping for the canonical Jordan spectrum.  This
direction is available over the real field without a JB spectral theorem; the reverse inclusion
and the resulting norm identity require the nonempty real JB spectrum argument recorded in the
CFC audit. -/
theorem jordanSpectrum_aeval_subset (a : E) (p : Polynomial ℝ) :
    (fun x => p.eval x) '' jordanSpectrum a ⊆
      spectrum ℝ (Polynomial.aeval (closedGenerator a) p) := by
  exact spectrum.subset_polynomial_aeval (closedGenerator a) p

/-- The algebraic transport step for reverse real polynomial spectral mapping.  If, after
subtracting a scalar value, all factors except one linear factor evaluate to units, then a
spectral value of the polynomial evaluation is already a spectral value of the generator. -/
theorem mem_spectrum_of_aeval_factor (a : E) (x : ClosedGeneratedByOne a)
    (p q r : Polynomial ℝ) (l μ : ℝ)
    (hfactor : p - Polynomial.C μ = q * (Polynomial.X - Polynomial.C l) * r)
    (hq : IsUnit (Polynomial.aeval x q)) (hr : IsUnit (Polynomial.aeval x r))
    (hμ : μ ∈ spectrum ℝ (Polynomial.aeval x p)) : l ∈ spectrum ℝ x := by
  rw [spectrum.mem_iff]
  intro hlin
  have hlinear : IsUnit (Polynomial.aeval x (Polynomial.X - Polynomial.C l)) := by
    have : IsUnit (-(Polynomial.aeval x (Polynomial.X - Polynomial.C l))) := by
      simpa [map_sub, Polynomial.aeval_X, Polynomial.aeval_C,
        Algebra.algebraMap_eq_smul_one, sub_eq_add_neg, add_comm] using hlin
    exact (IsUnit.neg_iff _).mp this
  have hprod : IsUnit (Polynomial.aeval x (p - Polynomial.C μ)) := by
    rw [hfactor, Polynomial.aeval_mul, Polynomial.aeval_mul]
    exact IsUnit.mul (IsUnit.mul hq hlinear) hr
  have hsub : IsUnit (Polynomial.aeval x p - (algebraMap ℝ (ClosedGeneratedByOne a)) μ) := by
    simpa [map_sub, Polynomial.aeval_C] using hprod
  have hres : IsUnit ((algebraMap ℝ (ClosedGeneratedByOne a)) μ - Polynomial.aeval x p) := by
    simpa [sub_eq_add_neg, add_comm] using hsub.neg
  exact (spectrum.mem_iff.mp hμ) hres

/-- Every monic irreducible real quadratic evaluates to a unit in the closed one-generator
ordered JB algebra.  Its no-real-root property forces the remainder in its completed-square form
to be strictly positive, so B2 applies directly. -/
theorem isUnit_aeval_of_irreducible_monic_degree_two [JBAlgebra E] [PartialOrder E]
    [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (a : E) (x : ClosedGeneratedByOne a) (q : Polynomial ℝ)
    (hq : Polynomial.IsMonicOfDegree q 2) (hirr : Irreducible q) :
    IsUnit (Polynomial.aeval x q) := by
  obtain ⟨b, c, hqform⟩ := Polynomial.isMonicOfDegree_two_iff'.mp hq
  let e : ℝ := c - b ^ 2 / 4
  have he : 0 < e := by
    by_contra hne
    have hle : e ≤ 0 := le_of_not_gt hne
    have hrad : 0 ≤ b ^ 2 / 4 - c := by dsimp [e] at hle; linarith
    have hroot : q.IsRoot (b / 2 + Real.sqrt (b ^ 2 / 4 - c)) := by
      change Polynomial.eval (b / 2 + Real.sqrt (b ^ 2 / 4 - c)) q = 0
      rw [hqform]
      simp only [Polynomial.eval_add, Polynomial.eval_sub, Polynomial.eval_pow,
        Polynomial.eval_C, Polynomial.eval_X, Polynomial.eval_mul]
      nlinarith [Real.sq_sqrt hrad]
    exact (hirr.not_isRoot_of_natDegree_ne_one (by simp [hq.natDegree_eq]) hroot)
  let d : ℝ := Real.sqrt e
  have hd : d ≠ 0 := ne_of_gt (by dsimp [d]; exact Real.sqrt_pos.2 he)
  have hlinear : Polynomial.C (b / 2) * 2 = Polynomial.C b := by
    change Polynomial.C (b / 2) * Polynomial.C 2 = Polynomial.C b
    rw [← Polynomial.C_mul]
    congr 1
    field_simp
  have hconstant : Polynomial.C (b / 2) ^ 2 = Polynomial.C (b ^ 2 / 4) := by
    rw [← Polynomial.C_pow]
    congr 1
    field_simp
    ring
  have hqcompleted : q = (Polynomial.X - Polynomial.C (b / 2)) ^ 2 + Polynomial.C (d ^ 2) := by
    rw [hqform]
    dsimp [d]
    rw [Real.sq_sqrt he.le]
    dsimp [e]
    rw [Polynomial.C_sub, ← hlinear, ← hconstant]
    ring
  rw [hqcompleted]
  exact JBAlgebra.ClosedGeneratedByOne.isUnit_aeval_completed_square a x (b / 2) d hd

/-- A nonunit evaluation of a monic linear polynomial directly exposes its real spectral root. -/
theorem exists_mem_spectrum_of_not_isUnit_aeval_monic_degree_one (a : E)
    (x : ClosedGeneratedByOne a) (q : Polynomial ℝ)
    (hq : Polynomial.IsMonicOfDegree q 1) (hnu : ¬ IsUnit (Polynomial.aeval x q)) :
    ∃ l : ℝ, l ∈ spectrum ℝ x ∧ q.eval l = 0 := by
  obtain ⟨c, hqform⟩ := Polynomial.isMonicOfDegree_one_iff.mp hq
  refine ⟨-c, ?_, ?_⟩
  · rw [spectrum.mem_iff]
    intro hunit
    apply hnu
    have hneg : IsUnit (-(Polynomial.aeval x (Polynomial.X + Polynomial.C c))) := by
      simpa [Polynomial.aeval_X, Polynomial.aeval_C, Algebra.algebraMap_eq_smul_one,
        sub_eq_add_neg, add_comm] using hunit
    simpa [hqform] using (IsUnit.neg_iff _).mp hneg
  · rw [hqform]
    simp

/-- A nonunit value of a monic real polynomial has a real spectral root.  The proof is strong
induction on degree: a monic irreducible factor has degree one or two; B4's quadratic theorem
rules out the second case, while the first supplies the spectral root. -/
theorem exists_mem_spectrum_of_not_isUnit_aeval_monic [JBAlgebra E]
    [PartialOrder E] [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E]
    [IsJBOrderUnit E] (a : E) (x : ClosedGeneratedByOne a) (f : Polynomial ℝ)
    (hf : f.Monic) (hnu : ¬ IsUnit (Polynomial.aeval x f)) :
    ∃ l : ℝ, l ∈ spectrum ℝ x ∧ f.eval l = 0 := by
  let P : ℕ → Prop := fun n ↦ ∀ g : Polynomial ℝ, g.natDegree = n → g.Monic →
    ¬ IsUnit (Polynomial.aeval x g) → ∃ l : ℝ, l ∈ spectrum ℝ x ∧ g.eval l = 0
  have hP : ∀ n, P n := by
    intro n
    induction n using Nat.strong_induction_on with
    | h n ih =>
      intro g hgn hg hgnu
      have hfnunit : ¬ IsUnit g := by
        intro hfu
        exact hgnu (hfu.map (Polynomial.aeval x))
      obtain ⟨q, hqmonic, hqirr, r, hfr⟩ := Polynomial.exists_monic_irreducible_factor g hfnunit
      have hfrmonic : r.Monic := hqmonic.of_mul_monic_left (hfr ▸ hg)
      have hqpos : 0 < q.natDegree := hqirr.natDegree_pos
      have hqle : q.natDegree ≤ 2 := hqirr.natDegree_le_two
      have hqcases : q.natDegree = 1 ∨ q.natDegree = 2 := by omega
      have hrlt : r.natDegree < n := by
        calc
          r.natDegree < q.natDegree + r.natDegree := Nat.lt_add_of_pos_left hqpos
          _ = g.natDegree := by rw [hfr, hqmonic.natDegree_mul' hfrmonic.ne_zero]
          _ = n := hgn
      have hprod : ¬ (IsUnit (Polynomial.aeval x q) ∧ IsUnit (Polynomial.aeval x r)) := by
        rintro ⟨hqu, hru⟩
        apply hgnu
        rw [hfr, Polynomial.aeval_mul]
        exact hqu.mul hru
      rcases hqcases with hqone | hqtwo
      · have hqdeg : Polynomial.IsMonicOfDegree q 1 := ⟨hqone, hqmonic⟩
        by_cases hqu : IsUnit (Polynomial.aeval x q)
        · have hrunu : ¬ IsUnit (Polynomial.aeval x r) := fun hru ↦ hprod ⟨hqu, hru⟩
          obtain ⟨l, hlspec, hrl⟩ := ih r.natDegree hrlt r rfl hfrmonic hrunu
          refine ⟨l, hlspec, ?_⟩
          rw [hfr, Polynomial.eval_mul, hrl, mul_zero]
        · obtain ⟨l, hlspec, hql⟩ :=
            exists_mem_spectrum_of_not_isUnit_aeval_monic_degree_one a x q hqdeg hqu
          refine ⟨l, hlspec, ?_⟩
          rw [hfr, Polynomial.eval_mul, hql, zero_mul]
      · have hqdeg : Polynomial.IsMonicOfDegree q 2 := ⟨hqtwo, hqmonic⟩
        have hqu : IsUnit (Polynomial.aeval x q) :=
          isUnit_aeval_of_irreducible_monic_degree_two a x q hqdeg hqirr
        have hrunu : ¬ IsUnit (Polynomial.aeval x r) := fun hru ↦ hprod ⟨hqu, hru⟩
        obtain ⟨l, hlspec, hrl⟩ := ih r.natDegree hrlt r rfl hfrmonic hrunu
        refine ⟨l, hlspec, ?_⟩
        rw [hfr, Polynomial.eval_mul, hrl, mul_zero]
  exact hP f.natDegree f rfl hf hnu

end NormedJordanAlgebra

namespace JBAlgebra

variable {E : Type*} [NormedJordanAlgebra E] [JBAlgebra E]

open NormedJordanAlgebra

namespace ClosedGeneratedByOne

variable (a : E)

/-- The intrinsic real JB spectral endpoint theorem.  The two order-norm endpoints cannot both
be units by the local exact-cone/interior argument, so one of their scalars is in the ordinary
real spectrum of the commutative algebra generated by `a`. -/
theorem norm_or_neg_norm_mem_spectrum [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (x : ClosedGeneratedByOne a) :
    ‖x‖ ∈ spectrum ℝ x ∨ -‖x‖ ∈ spectrum ℝ x := by
  by_cases hp : IsUnit (‖x‖ • (1 : ClosedGeneratedByOne a) - x)
  · right
    rw [spectrum.mem_iff]
    intro hm
    apply not_isUnit_norm_smul_one_sub_and_add a x
    refine ⟨hp, ?_⟩
    have hm' : IsUnit (-(‖x‖ • (1 : ClosedGeneratedByOne a) + x)) := by
      simpa [Algebra.algebraMap_eq_smul_one, smul_add, sub_eq_add_neg, add_comm, add_left_comm,
        add_assoc] using hm
    exact (IsUnit.neg_iff _).mp hm'
  · left
    rw [spectrum.mem_iff]
    simpa [Algebra.algebraMap_eq_smul_one] using hp

/-- In a closed one-generator ordered JB algebra, the real spectral radius is exactly the JB
norm.  The generic upper bound is met by one of the two real norm endpoints. -/
theorem jordanSpectralRadius_eq_norm [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (x : ClosedGeneratedByOne a) : spectralRadius ℝ x = (‖x‖₊ : ENNReal) := by
  apply le_antisymm
  · exact spectralRadius_le_norm a x
  · rcases norm_or_neg_norm_mem_spectrum a x with hx | hx
    · calc
        (‖x‖₊ : ENNReal) = ‖(‖x‖ : ℝ)‖₊ := by rw [nnnorm_norm]
        _ ≤ spectralRadius ℝ x := le_iSup₂ (α := ENNReal) (‖x‖ : ℝ) hx
    · calc
        (‖x‖₊ : ENNReal) = ‖(-‖x‖ : ℝ)‖₊ := by simp only [nnnorm_neg, nnnorm_norm]
        _ ≤ spectralRadius ℝ x := le_iSup₂ (α := ENNReal) (-‖x‖ : ℝ) hx

end ClosedGeneratedByOne

end JBAlgebra

namespace NormedJordanAlgebra

variable {E : Type*} [NormedJordanAlgebra E] [JBAlgebra E]

/-- The canonical real spectrum of every ordered JB observable is nonempty. -/
theorem jordanSpectrum_nonempty [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] (a : E) :
    (jordanSpectrum a).Nonempty := by
  rcases JBAlgebra.ClosedGeneratedByOne.norm_or_neg_norm_mem_spectrum a (closedGenerator a)
    with h | h
  · exact ⟨‖closedGenerator a‖, h⟩
  · exact ⟨-‖closedGenerator a‖, h⟩

/-- The canonical real spectrum of a positive JB observable is nonnegative.  A negative scalar
is excluded intrinsically because subtracting it is a strictly positive element of the closed
one-generator algebra, hence a unit. -/
theorem nonneg_of_mem_jordanSpectrum [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E] {a : E} (ha : 0 ≤ a)
    {r : ℝ} (hr : r ∈ jordanSpectrum a) : 0 ≤ r := by
  by_contra hrnonneg
  have hrneg : r < 0 := lt_of_not_ge hrnonneg
  have hgenerator : 0 ≤ closedGenerator a := ha
  have hbound : (-r) • (1 : ClosedGeneratedByOne a) ≤ closedGenerator a -
      r • (1 : ClosedGeneratedByOne a) := by
    rw [sub_eq_add_neg, ← neg_smul]
    exact le_add_of_nonneg_left hgenerator
  have hunit : IsUnit (closedGenerator a - r • (1 : ClosedGeneratedByOne a)) :=
    JBAlgebra.ClosedGeneratedByOne.isUnit_of_strictly_positive a (neg_pos.mpr hrneg) hbound
  change r ∈ spectrum ℝ (closedGenerator a) at hr
  rw [spectrum.mem_iff] at hr
  apply hr
  simpa [Algebra.algebraMap_eq_smul_one, sub_eq_add_neg, add_comm] using hunit.neg

/-- The reverse real polynomial spectral-mapping direction in the generated-one JB algebra. -/
theorem exists_mem_spectrum_of_mem_spectrum_aeval [Nontrivial E] [PartialOrder E]
    [IsOrderedAddMonoid E] [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (a : E) (x : ClosedGeneratedByOne a) (p : Polynomial ℝ) (μ : ℝ)
    (hμ : μ ∈ spectrum ℝ (Polynomial.aeval x p)) :
    ∃ l : ℝ, l ∈ spectrum ℝ x ∧ p.eval l = μ := by
  let f : Polynomial ℝ := p - Polynomial.C μ
  have hfnu : ¬ IsUnit (Polynomial.aeval x f) := by
    intro hfu
    apply (spectrum.mem_iff.mp hμ)
    have hsub : IsUnit (Polynomial.aeval x p - (algebraMap ℝ (ClosedGeneratedByOne a)) μ) := by
      simpa [f, map_sub, Polynomial.aeval_C] using hfu
    simpa [sub_eq_add_neg, add_comm] using hsub.neg
  by_cases hfzero : f = 0
  · obtain hx | hx := JBAlgebra.ClosedGeneratedByOne.norm_or_neg_norm_mem_spectrum a x
    · refine ⟨‖x‖, hx, ?_⟩
      have hzeroeval : f.eval ‖x‖ = 0 := by simpa using congrArg (Polynomial.eval ‖x‖) hfzero
      exact sub_eq_zero.mp (by simpa [f, Polynomial.eval_sub, Polynomial.eval_C] using hzeroeval)
    · refine ⟨-‖x‖, hx, ?_⟩
      have hzeroeval : f.eval (-‖x‖ : ℝ) = 0 :=
        by simpa using congrArg (Polynomial.eval (-‖x‖ : ℝ)) hfzero
      exact sub_eq_zero.mp (by simpa [f, Polynomial.eval_sub, Polynomial.eval_C] using hzeroeval)
  · let g : Polynomial ℝ := f * Polynomial.C f.leadingCoeff⁻¹
    have hgmonic : g.Monic := Polynomial.monic_mul_leadingCoeff_inv hfzero
    have hgnu : ¬ IsUnit (Polynomial.aeval x g) := by
      intro hgu
      apply hfnu
      have hprod : IsUnit (Polynomial.aeval x f *
          (algebraMap ℝ (ClosedGeneratedByOne a)) f.leadingCoeff⁻¹) := by
        simpa [g, Polynomial.aeval_mul, Polynomial.aeval_C] using hgu
      exact (IsUnit.mul_iff.mp hprod).1
    obtain ⟨l, hlspec, hgl⟩ :=
      exists_mem_spectrum_of_not_isUnit_aeval_monic a x g hgmonic hgnu
    have hinv : f.leadingCoeff⁻¹ ≠ 0 := inv_ne_zero (Polynomial.leadingCoeff_ne_zero.mpr hfzero)
    have hfl : f.eval l = 0 := by
      have hprod : f.eval l * f.leadingCoeff⁻¹ = 0 := by
        simpa [g, Polynomial.eval_mul, Polynomial.eval_C] using hgl
      exact (mul_eq_zero.mp hprod).resolve_right hinv
    refine ⟨l, hlspec, ?_⟩
    exact sub_eq_zero.mp (by simpa [f, Polynomial.eval_sub, Polynomial.eval_C] using hfl)

/-- Exact real polynomial spectral mapping for the canonical spectrum of a JB observable. -/
theorem jordanSpectrum_aeval [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (a : E) (p : Polynomial ℝ) :
    (fun t ↦ p.eval t) '' jordanSpectrum a =
      spectrum ℝ (Polynomial.aeval (closedGenerator a) p) := by
  apply Set.Subset.antisymm
  · exact jordanSpectrum_aeval_subset a p
  · intro μ hμ
    obtain ⟨l, hl, hpl⟩ :=
      exists_mem_spectrum_of_mem_spectrum_aeval a (closedGenerator a) p μ hμ
    exact ⟨l, hl, hpl⟩

/-- The JB norm of polynomial evaluation is the real spectral supremum of the corresponding
restricted polynomial.  This is the order-theoretic isometry statement prior to bundling the
continuous polynomial function in B5. -/
theorem nnnorm_aeval_closedGenerator [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (a : E) (p : Polynomial ℝ) :
    (‖Polynomial.aeval (closedGenerator a) p‖₊ : ENNReal) =
      ⨆ l ∈ jordanSpectrum a, (‖p.eval l‖₊ : ENNReal) := by
  rw [← JBAlgebra.ClosedGeneratedByOne.jordanSpectralRadius_eq_norm a
    (Polynomial.aeval (closedGenerator a) p)]
  unfold spectralRadius
  rw [← jordanSpectrum_aeval a p, iSup_image]

/-- Norm form of the polynomial-evaluation isometry, expressed in `ℝ≥0∞` so that the spectral
supremum is total. -/
theorem norm_aeval_closedGenerator [Nontrivial E] [PartialOrder E] [IsOrderedAddMonoid E]
    [IsArchimedeanOrderUnit E] [PosSMulMono ℝ E] [IsJBOrderUnit E]
    (a : E) (p : Polynomial ℝ) :
    (‖Polynomial.aeval (closedGenerator a) p‖₊ : ENNReal) =
      ⨆ l ∈ jordanSpectrum a, (‖p.eval l‖₊ : ENNReal) := by
  exact nnnorm_aeval_closedGenerator a p

end NormedJordanAlgebra
