/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import PhyslibAlpha.AlgebraicFramework.JordanOrderUnit.JB.GeneratedByOne.Inherited
public import Mathlib.Analysis.Normed.Algebra.Spectrum

/-!

# Uniform norm on the closed algebra generated by one JB element

The closed algebra generated by one element is more than a commutative real Banach algebra.  The
JB square axiom restricts to it, so its norm is uniform: `‖x²‖ = ‖x‖²`.  Iteration along powers of
two is the analytic input needed to identify norm and spectral radius once real-spectrum
nonemptiness is established.

This layer deliberately stops before asserting spectrum nonemptiness.  That statement is false
for general real Banach algebras and must be proved from the JB-specific uniform/order structure.

-/

@[expose] public section

namespace JBAlgebra

variable {E : Type*} [NormedJordanAlgebra E] [JBAlgebra E]

open NormedJordanAlgebra
open scoped ENNReal NNReal

namespace ClosedGeneratedByOne

variable (a : E)

/-! ## Uniform square norm -/

/-- The JB square axiom restricts to the closed algebra generated by one element. -/
lemma norm_mul_self (x : ClosedGeneratedByOne a) : ‖x * x‖ = ‖x‖ ^ 2 := by
  exact JBAlgebra.norm_mul_self x

/-- The generic Banach-algebra spectral-radius bound, specialized to the closed JB generator.  The
reverse inequality is the genuinely JB-specific spectral theorem and is intentionally not folded
into this generic estimate. -/
lemma spectralRadius_le_norm [Nontrivial E] (x : ClosedGeneratedByOne a) :
    spectralRadius ℝ x ≤ (‖x‖₊ : ℝ≥0∞) := by
  exact spectrum.spectralRadius_le_nnnorm x

/-- Along powers of two, the closed one-generator algebra has a uniform norm. -/
lemma norm_pow_two_pow (x : ClosedGeneratedByOne a) (n : ℕ) :
    ‖x ^ (2 ^ n)‖ = ‖x‖ ^ (2 ^ n) := by
  induction n with
  | zero => simp
  | succ n ih =>
      calc
        ‖x ^ (2 ^ (n + 1))‖ = ‖(x ^ (2 ^ n)) * (x ^ (2 ^ n))‖ := by
          rw [pow_succ, pow_mul, pow_two]
        _ = ‖x ^ (2 ^ n)‖ ^ 2 := norm_mul_self a _
        _ = (‖x‖ ^ (2 ^ n)) ^ 2 := by rw [ih]
        _ = ‖x‖ ^ (2 ^ (n + 1)) := by
          rw [← pow_mul, pow_succ]

end ClosedGeneratedByOne

end JBAlgebra
