/-
Copyright (c) 2026 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.QFT.Factorization.Convolution.Properties
/-!

# Collinear convolution kernels

The general integral operator `convolveAt K f x = ∫_{[0,1]} K x z * f z dz` of
`Physlib.QFT.Factorization.Convolution.Basic` becomes the *collinear* (Mellin) convolution of
collinear factorization,
```
(C ⊗ f) (x) = ∫_x^1 (dz / z) * C (x / z) * f z,
```
exactly when the kernel has the scaling form `K x z = z⁻¹ * C (x / z)` on the support `x ≤ z`,
`0 < z`, and vanishes elsewhere. This module isolates that class of kernels.

`convolveAt` is deliberately *not* redefined: the general operator is needed for kernels that do
not scale (DVCS convolutions, detector response matrices), and every linearity lemma already
proved for `convolveAt` applies verbatim to the collinear specialization.

## Conventions

- The support condition is `x ≤ z` together with `0 < z`; the `z⁻¹` Jacobian is part of the
  kernel, not of the measure. This is the convention in which the Mellin transform factorizes
  (see `Physlib.QFT.Factorization.Convolution.Mellin`): the substitution `x = z * u` in the
  transform consumes exactly this `z⁻¹`.
- The kernel is an honest function `ℝ → ℝ → ℝ`, so only *integrable* coefficient functions are
  described. Physical splitting kernels carry `1 / (1 - z)` endpoint singularities regulated by
  plus-distributions; those are not objects of type `ℝ → ℝ` and are out of scope here. A
  distributional kernel type is a separate development.

## Table of contents

- A. The collinear kernel
- B. Values and support
- C. Linearity in the coefficient function
- D. The convolution in collinear form

-/

@[expose] public section

noncomputable section

namespace Physlib
namespace QFT
namespace Factorization
namespace Convolution

/-!

## A. The collinear kernel

-/

/-- The collinear (scaling) kernel generated by a coefficient function `C`:
`collinearKernel C x z = z⁻¹ * C (x / z)` on the physical support `x ≤ z` and `0 < z`, and `0`
elsewhere. The factor `z⁻¹` is the Jacobian of the collinear convolution
`(C ⊗ f) (x) = ∫_x^1 (dz / z) * C (x / z) * f z`. -/
def collinearKernel (C : ℝ → ℝ) : Kernel :=
  fun x z => if x ≤ z ∧ 0 < z then z⁻¹ * C (x / z) else 0

/-- A kernel `K` is collinear with coefficient function `C` when it agrees pointwise with
`collinearKernel C`. Stated as a predicate so that downstream files can quantify over "the
kernel has scaling form" without committing to a particular representative. -/
def IsCollinearKernel (K : Kernel) (C : ℝ → ℝ) : Prop :=
  ∀ x z, K x z = collinearKernel C x z

/-- The collinear kernel of `C` is collinear with coefficient function `C`. -/
lemma isCollinearKernel_collinearKernel (C : ℝ → ℝ) :
    IsCollinearKernel (collinearKernel C) C := fun _ _ => rfl

/-!

## B. Values and support

-/

/-- Defining equation of `collinearKernel`. -/
lemma collinearKernel_apply (C : ℝ → ℝ) (x z : ℝ) :
    collinearKernel C x z = if x ≤ z ∧ 0 < z then z⁻¹ * C (x / z) else 0 := rfl

/-- Inside the physical region `0 < z`, `x ≤ z` the collinear kernel is `z⁻¹ * C (x / z)`. -/
lemma collinearKernel_of_mem (C : ℝ → ℝ) {x z : ℝ} (hz : 0 < z) (hxz : x ≤ z) :
    collinearKernel C x z = z⁻¹ * C (x / z) := by
  rw [collinearKernel_apply, if_pos ⟨hxz, hz⟩]

/-- The collinear kernel vanishes above the diagonal: no momentum fraction larger than `z` can
be reached from a parton of fraction `z`. -/
lemma collinearKernel_of_lt (C : ℝ → ℝ) {x z : ℝ} (hzx : z < x) :
    collinearKernel C x z = 0 := by
  refine (collinearKernel_apply C x z).trans (if_neg ?_)
  exact fun h => absurd h.1 (not_le.mpr hzx)

/-- The collinear kernel vanishes for non-positive `z`. -/
lemma collinearKernel_of_nonpos (C : ℝ → ℝ) {x z : ℝ} (hz : z ≤ 0) :
    collinearKernel C x z = 0 := by
  refine (collinearKernel_apply C x z).trans (if_neg ?_)
  exact fun h => absurd h.2 (not_lt.mpr hz)

/-!

## C. Linearity in the coefficient function

-/

/-- The collinear kernel of the zero coefficient function is the zero kernel. -/
lemma collinearKernel_zero : collinearKernel (fun _ => 0) = fun _ _ => (0 : ℝ) := by
  funext x z
  simp [collinearKernel]

/-- The collinear kernel is additive in its coefficient function. -/
lemma collinearKernel_add (C₁ C₂ : ℝ → ℝ) (x z : ℝ) :
    collinearKernel (fun u => C₁ u + C₂ u) x z
      = collinearKernel C₁ x z + collinearKernel C₂ x z := by
  simp only [collinearKernel]
  split_ifs with h
  · rw [mul_add]
  · rw [add_zero]

/-- The collinear kernel is homogeneous in its coefficient function. -/
lemma collinearKernel_const_mul (c : ℝ) (C : ℝ → ℝ) (x z : ℝ) :
    collinearKernel (fun u => c * C u) x z = c * collinearKernel C x z := by
  simp only [collinearKernel]
  split_ifs with h
  · ring
  · rw [mul_zero]

/-!

## D. The convolution in collinear form

-/

/-- The convolution may be taken over `(0,1]` rather than `[0,1]`: the endpoint `0` is a null
set for the Lebesgue measure. Stated for a general kernel because it is the form in which the
Mellin transform, whose `x ^ (N - 1)` weight is singular at `0`, consumes the convolution. -/
lemma convolveAt_eq_integral_Ioc (K : Kernel) (f : ℝ → ℝ) (x : ℝ) :
    convolveAt K f x = ∫ z in Set.Ioc (0 : ℝ) 1, integrand K f x z := by
  rw [convolveAt]
  -- TODO(task/e1-mellin-convolution): discharge with the `[NoAtoms μ]` lemma stating that the
  -- integral over `Icc a b` equals the integral over `Ioc a b` (Lebesgue measure has no atoms,
  -- so the endpoint `{0}` is null). In mathlib this is `integral_Icc_eq_integral_Ioc`, but the
  -- namespace could NOT be confirmed at this pin — no mathlib source is available in this
  -- checkout (no `.lake`), so whether it is `MeasureTheory.integral_Icc_eq_integral_Ioc` or
  -- root-namespaced is unverified. Left as `sorry` rather than asserting an unchecked name.
  sorry

/-- Explicit collinear form of the convolution:
`(C ⊗ f) (x) = ∫_{(0,1]} 1_{x ≤ z} * z⁻¹ * C (x / z) * f z dz`, i.e. `∫_x^1 (dz / z) C (x / z) f z`
once the indicator is absorbed into the domain. -/
lemma convolveAt_collinearKernel_eq (C f : ℝ → ℝ) (x : ℝ) :
    convolveAt (collinearKernel C) f x
      = ∫ z in Set.Ioc (0 : ℝ) 1, if x ≤ z then z⁻¹ * C (x / z) * f z else 0 := by
  rw [convolveAt_eq_integral_Ioc]
  -- TODO(task/e1-mellin-convolution): congruence of set integrals under pointwise equality on
  -- the domain. Intended proof, once the lemma name is confirmed against the pin:
  --   refine <setIntegral_congr_fun> measurableSet_Ioc (fun z hz => ?_)
  --   simp only [integrand, collinearKernel, hz.1, and_true, ite_mul, zero_mul]
  -- The name could NOT be confirmed here (no mathlib source in this checkout); mathlib has
  -- variously called it `setIntegral_congr_fun` / `setIntegral_congr` / `set_integral_congr`,
  -- with differing argument order. Left as `sorry` rather than asserting an unchecked name.
  sorry

/-- Outside the physical region the collinear convolution vanishes: for `1 < x` there is no
`z ∈ (0,1]` with `x ≤ z`. -/
lemma convolveAt_collinearKernel_eq_zero_of_one_lt (C f : ℝ → ℝ) {x : ℝ} (hx : 1 < x) :
    convolveAt (collinearKernel C) f x = 0 := by
  rw [convolveAt_eq_integral_Ioc]
  have h : (∫ z in Set.Ioc (0 : ℝ) 1, integrand (collinearKernel C) f x z)
      = ∫ _z in Set.Ioc (0 : ℝ) 1, (0 : ℝ) := by
    -- TODO(task/e1-mellin-convolution): same unconfirmed set-integral congruence lemma as in
    -- `convolveAt_collinearKernel_eq` above. Intended proof:
    --   refine <setIntegral_congr_fun> measurableSet_Ioc (fun z hz => ?_)
    --   rw [integrand, collinearKernel_of_lt C (lt_of_le_of_lt hz.2 hx), zero_mul]
    sorry
  rw [h, MeasureTheory.integral_zero]

/-- A kernel of collinear form may be replaced by the canonical representative inside the
convolution, so that all collinear results apply to it. -/
lemma IsCollinearKernel.convolveAt_eq {K : Kernel} {C : ℝ → ℝ}
    (h : IsCollinearKernel K C) (f : ℝ → ℝ) (x : ℝ) :
    convolveAt K f x = convolveAt (collinearKernel C) f x :=
  convolveAt_eq_of_kernel_eq K (collinearKernel C) f x h

/-- The collinear convolution of the zero coefficient function vanishes. -/
lemma convolveAt_collinearKernel_zero (f : ℝ → ℝ) (x : ℝ) :
    convolveAt (collinearKernel (fun _ => 0)) f x = 0 := by
  rw [collinearKernel_zero]
  exact convolveAt_zero_kernel f x

end Convolution
end Factorization
end QFT
end Physlib
