/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license and described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import Mathlib.Algebra.FreeAlgebra
public import Mathlib.Algebra.Symmetrized
public import PhyslibAlpha.AlgebraicFramework.JordanOrderUnit.FreeJordanTwo
public import PhyslibAlpha.AlgebraicFramework.JordanOrderUnit.Power.Generated

/-!
# The free special Jordan algebra on two generators

Let `A₂ = FreeAlgebra ℝ (Fin 2)`.  Mathlib's `SymAlg A₂` is its normalized Jordanization,
with product `x ∘ y = (xy + yx)/2`.  The free special Jordan algebra on two generators is the
Jordan fragment of that symmetrization generated by the two canonical free-associative letters.

This is only the concrete special side of Shirshov--Cohn.  It deliberately does not claim that
the abstract free Jordan algebra maps injectively here (Shirshov), nor that every quotient remains
special (Cohn); those are the two distinct hard theorems to be formalized above this object.
-/

@[expose] public section

namespace JordanAlgebra

/-- The free associative real algebra on two noncommuting letters. -/
abbrev FreeAssocTwo := FreeAlgebra ℝ (Fin 2)

/-- The normalized symmetrized product on the real free associative algebra uses division by two.
This is available because the free algebra has characteristic zero. -/
noncomputable instance : Invertible (2 : FreeAssocTwo) :=
  let u : FreeAssocTwoˣ :=
    Units.map (algebraMap ℝ FreeAssocTwo) (Units.mk0 (2 : ℝ) (by norm_num))
  IsUnit.invertible ⟨u, by
    change algebraMap ℝ FreeAssocTwo (2 : ℝ) = (2 : FreeAssocTwo)
    exact map_natCast (algebraMap ℝ FreeAssocTwo) 2⟩

/-- Mathlib supplies the symmetrized non-associative ring and commutativity separately; package
them into the ordinary carrier class used by the generated-subalgebra API. -/
noncomputable instance : NonAssocCommRing (SymAlg FreeAssocTwo) :=
  { SymAlg.nonAssocSemiring, SymAlg.addCommGroup with
    mul_comm := SymAlg.mul_comm }

noncomputable instance (priority := 2000) : SMul (SymAlg FreeAssocTwo) (SymAlg FreeAssocTwo) where
  smul := (· * ·)

noncomputable instance :
    IsScalarTower ℝ (SymAlg FreeAssocTwo) (SymAlg FreeAssocTwo) where
  smul_assoc r x y := by
    rw [smul_eq_mul, smul_eq_mul]
    apply SymAlg.unsym_injective
    rw [SymAlg.unsym_mul, SymAlg.unsym_smul, SymAlg.unsym_smul, SymAlg.unsym_mul,
      Algebra.smul_mul_assoc, Algebra.mul_smul_comm, ← smul_add, mul_smul_comm]

noncomputable instance :
    SMulCommClass ℝ (SymAlg FreeAssocTwo) (SymAlg FreeAssocTwo) where
  smul_comm r x y := by
    rw [smul_eq_mul, smul_eq_mul]
    apply SymAlg.unsym_injective
    rw [SymAlg.unsym_smul, SymAlg.unsym_mul, SymAlg.unsym_mul, SymAlg.unsym_smul,
      Algebra.mul_smul_comm, Algebra.smul_mul_assoc, ← smul_add, Algebra.mul_smul_comm]


/-- The first canonical generator in the Jordanization of `FreeAssocTwo`. -/
def freeSpecialX : SymAlg FreeAssocTwo := SymAlg.sym (FreeAlgebra.ι ℝ 0)

/-- The second canonical generator in the Jordanization of `FreeAssocTwo`. -/
def freeSpecialY : SymAlg FreeAssocTwo := SymAlg.sym (FreeAlgebra.ι ℝ 1)

/-- The carrier submodule of the free special Jordan algebra on two generators. -/
noncomputable abbrev freeSpecialJordanTwo : Submodule ℝ (SymAlg FreeAssocTwo) :=
  generatedByTwo freeSpecialX freeSpecialY

/-- The free special Jordan algebra on two generators as its own unital real Jordan algebra. -/
noncomputable abbrev FreeSpecialJordanTwo : Type _ := GeneratedByTwo freeSpecialX freeSpecialY

/-- The first free special generator belongs to its generated Jordan fragment. -/
theorem freeSpecialX_mem : freeSpecialX ∈ freeSpecialJordanTwo :=
  left_mem_generatedByTwo freeSpecialX freeSpecialY

/-- The second free special generator belongs to its generated Jordan fragment. -/
theorem freeSpecialY_mem : freeSpecialY ∈ freeSpecialJordanTwo :=
  right_mem_generatedByTwo freeSpecialX freeSpecialY

/-- The two canonical letters as elements of the free special Jordan algebra. -/
noncomputable def freeSpecialGenerators : Fin 2 → FreeSpecialJordanTwo :=
  Fin.cases ⟨freeSpecialX, freeSpecialX_mem⟩ fun _ => ⟨freeSpecialY, freeSpecialY_mem⟩

/-- The canonical homomorphism from the abstract free Jordan algebra to its special model.
Shirshov's theorem is precisely the still-unproved assertion that this map is injective. -/
noncomputable def freeJordanToSpecial : JordanHom FreeJordanTwo FreeSpecialJordanTwo :=
  FreeJordanTwo.lift freeSpecialGenerators

@[simp]
theorem freeJordanToSpecial_x : freeJordanToSpecial FreeJordanTwo.x = freeSpecialGenerators 0 :=
  FreeJordanTwo.lift_x freeSpecialGenerators

@[simp]
theorem freeJordanToSpecial_y : freeJordanToSpecial FreeJordanTwo.y = freeSpecialGenerators 1 :=
  FreeJordanTwo.lift_y freeSpecialGenerators

end JordanAlgebra
