/-
Copyright (c) 2026 Tom Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Diem
-/
module

public import Mathlib.Algebra.Lie.OfAssociative
public import Mathlib.Tactic.NoncommRing
public import Mathlib.LinearAlgebra.Matrix.StdBasis
public import Mathlib.Data.Matrix.Basis
public import Physlib.Mathematics.KroneckerDelta.Basic
/-!

# Ladder systems

## i. Overview

A `LadderSystem K V d` packages `d` pairs of creation and annihilation endomorphisms of a
`K`-vector space `V` satisfying the canonical commutation relations. The definition abstracts the
algebraic structure shared by bosonic systems independently of a particular representation. The
bilinears `E i j := acᵢaⱼ` satisfy the `gl(d)` commutation relations and define a `gl(d)`-module
structure on `V` via `toGlHom`.

- `Basic.lean` : this file -- the structure itself, the `gl(d)`-module structure it generates, and
    the number operator.
- `Vacuum.lean` : a vacuum state, the creation-operator words built over it, and the excitation-
    number sector they span, bundled as a `gl(d)` Lie submodule.
- `OccupationBasis.lean` : the occupation-number states form a basis of each fixed-
    excitation-number sector, with an explicit dimension formula.
- `SymmetricPower.lean` : that sector is linearly isomorphic to `Sym^n(K^d)`.

The harmonic-oscillator instance is defined in
`QuantumMechanics/HarmonicOscillator/LadderOperators.lean`.

## ii. Key results

Definitions:
- `LadderSystem.E` : the `gl(d)` bilinears `E i j := acᵢaⱼ`.
- `LadderSystem.toGlHom` : the `gl(d)`-representation on `V` generated by a ladder system.
- `LadderSystem.N` : the number operator for mode `i`, `Nᵢ ≔ Eᵢᵢ`.

Theorems:
- `LadderSystem.lie_E` : `E` satisfies the defining relations of `gl(d)`.
- `LadderSystem.lie_N_a`, `LadderSystem.lie_N_ac` : `[Nᵢ, aⱼ] = -δᵢⱼaᵢ` and
    `[Nᵢ, acⱼ] = δᵢⱼacᵢ`.
- `LadderSystem.lie_N_N` : the number operators commute among themselves, `[Nᵢ, Nⱼ] = 0`.
- `LadderSystem.lie_totalN_E` : the *total* number operator `∑ᵢNᵢ` is central in `gl(d)` --
    it commutes with every generator `E i j`, not just the diagonal ones. This is what makes an
    isotropic Hamiltonian (a function of `∑ᵢNᵢ` alone) compatible with the full `gl(d)`-module
    structure on `vacuumSpan`, not just individually with each `Nᵢ`.

## iii. Table of contents

- A. The `LadderSystem` structure
- B. The `gl(d)`-module structure
- C. The number operator
  - C.1. Commutation relations
  - C.2. The total number operator

## iv. References

* None.
-/

@[expose] public section

open Module (Basis)
open KroneckerDelta

/-!

## A. The `LadderSystem` structure

-/

attribute [local instance 100] LieRing.ofAssociativeRing

variable {K : Type*} [Field K]

section BracketLinearMaps

variable (L : Type*) [LieRing L] [LieAlgebra K L]

/-- Bracketing on the right by a fixed element, as a `K`-linear self-map. -/
def bracketRight (y : L) : L →ₗ[K] L where
  toFun x := ⁅x, y⁆
  map_add' a c := add_lie a c y
  map_smul' c a := smul_lie c a y

/-- Bracketing on the left by a fixed element, as a `K`-linear self-map. -/
def bracketLeft (x : L) : L →ₗ[K] L where
  toFun y := ⁅x, y⁆
  map_add' := lie_add x
  map_smul' c a := lie_smul c x a

end BracketLinearMaps

variable {L L' : Type*} [LieRing L] [LieAlgebra K L] [LieRing L'] [LieAlgebra K L']
variable {ι : Type*}

/-- A `K`-linear map agreeing with the bracket on basis pairs agrees with the bracket
everywhere. -/
theorem LinearMap.lie_apply_eq_of_lie_basis_eq (b : Basis ι K L) (f : L →ₗ[K] L')
    (h : ∀ i j, f ⁅b i, b j⁆ = ⁅f (b i), f (b j)⁆) (x y : L) :
    f ⁅x, y⁆ = ⁅f x, f y⁆ := by
  have step1 : ∀ j : ι,
      f.comp (bracketRight L (b j)) = (bracketRight L' (f (b j))).comp f := by
    intro j
    apply b.ext
    intro i
    change f ⁅b i, b j⁆ = ⁅f (b i), f (b j)⁆
    exact h i j
  have step2 : f.comp (bracketLeft L x) = (bracketLeft L' (f x)).comp f := by
    apply b.ext
    intro j
    have hx := DFunLike.congr_fun (step1 j) x
    change f ⁅x, b j⁆ = ⁅f x, f (b j)⁆ at hx
    exact hx
  exact DFunLike.congr_fun step2 y

/-- Same, from a spanning set rather than a basis (`LinearMap.ext_on` in place of `Basis.ext`) —
for generators that span but aren't worth packaging as an indexed basis. -/
theorem LinearMap.lie_apply_eq_of_lie_span_eq {s : Set L} (hs : Submodule.span K s = ⊤)
    (f : L →ₗ[K] L') (h : ∀ x ∈ s, ∀ y ∈ s, f ⁅x, y⁆ = ⁅f x, f y⁆) (x y : L) :
    f ⁅x, y⁆ = ⁅f x, f y⁆ := by
  have step1 : ∀ z ∈ s,
      f.comp (bracketRight L z) = (bracketRight L' (f z)).comp f := by
    intro z hz
    apply LinearMap.ext_on hs
    intro w hw
    change f ⁅w, z⁆ = ⁅f w, f z⁆
    exact h w hw z hz
  have step2 : f.comp (bracketLeft L x) = (bracketLeft L' (f x)).comp f := by
    apply LinearMap.ext_on hs
    intro z hz
    have hx := DFunLike.congr_fun (step1 z hz) x
    change f ⁅x, z⁆ = ⁅f x, f z⁆ at hx
    exact hx
  exact DFunLike.congr_fun step2 y


/-- A system of `d` independent ladder pairs on a `K`-vector space `V`: annihilation operators
`a i` and creation operators `ac i` (`i : Fin d`), satisfying the canonical commutation relations.
A physical system exhibits its own concrete operators as one instance of this (e.g.
`QuantumMechanics/HarmonicOscillator/LadderOperators.lean`'s `toLadderSystem`, via
`ContinuousLinearMap.toLinearMap`) and inherits every result in `LadderSystem/` for free. -/
structure LadderSystem (K V : Type*) [Field K] [AddCommGroup V] [Module K V] (d : ℕ) where
  /-- The `d` annihilation operators. -/
  a : Fin d → Module.End K V
  /-- The `d` creation operators, `a⁺`. -/
  ac : Fin d → Module.End K V
  /-- `[a i, ac j] = δᵢⱼ`. -/
  comm_a_ac : ∀ i j, (⁅a i, ac j⁆ : Module.End K V) = if i = j then 1 else 0
  /-- `[a i, a j] = 0`. -/
  comm_a_a : ∀ i j, (⁅a i, a j⁆ : Module.End K V) = 0
  /-- `[ac i, ac j] = 0`. -/
  comm_ac_ac : ∀ i j, (⁅ac i, ac j⁆ : Module.End K V) = 0

namespace LadderSystem

variable {K V : Type*} [Field K] [AddCommGroup V] [Module K V] {d : ℕ} (L : LadderSystem K V d)

lemma assoc_leibniz (x y z : Module.End K V) :
    (⁅x, y * z⁆ : Module.End K V) = ⁅x, y⁆ * z + y * ⁅x, z⁆ := by
  simp only [LieRing.of_associative_ring_bracket]
  noncomm_ring

lemma assoc_leibniz' (x y z : Module.End K V) :
    (⁅x * y, z⁆ : Module.End K V) = x * ⁅y, z⁆ + ⁅x, z⁆ * y := by
  simp only [LieRing.of_associative_ring_bracket]
  noncomm_ring

/-!

## B. The `gl(d)`-module structure

-/

/-- The `gl(d)` bilinears `E i j := ac i · a j`. -/
def E (i j : Fin d) : Module.End K V := L.ac i * L.a j

/-- `E` satisfies the defining relations of `gl(d)`:
`[E i j, E k l] = δⱼₖ E i l - δₗᵢ E k j`. -/
theorem lie_E (i j k l : Fin d) :
    (⁅L.E i j, L.E k l⁆ : Module.End K V)
      = (δ[j,k] : K) • L.E i l - (δ[l,i] : K) • L.E k j := by
  show (⁅L.ac i * L.a j, L.ac k * L.a l⁆ : Module.End K V) = _
  rw [assoc_leibniz' (L.ac i) (L.a j) (L.ac k * L.a l), assoc_leibniz (L.a j) (L.ac k) (L.a l),
    assoc_leibniz (L.ac i) (L.ac k) (L.a l), L.comm_a_ac j k, L.comm_a_a j l, L.comm_ac_ac i k]
  have hAl : (⁅L.ac i, L.a l⁆ : Module.End K V) = (-δ[l,i] : K) • (1 : Module.End K V) := by
    rw [← lie_skew, L.comm_a_ac l i]
    by_cases hli : l = i <;> simp [eq_zero_of_ne, hli]
  rw [hAl]
  by_cases hjk : j = k <;> by_cases hli : l = i <;>
    simp [hjk, hli, E, eq_zero_of_ne, mul_zero, zero_mul, mul_one, one_mul, sub_eq_add_neg]

/-- The matrix units satisfy the same relations, at the level of `gl(d)` itself. -/
lemma lie_single (i j k l : Fin d) :
    (⁅Matrix.single i j (1 : K), Matrix.single k l (1 : K)⁆ : Matrix (Fin d) (Fin d) K)
      = (δ[j,k] : K) • Matrix.single i l 1 - (δ[l,i] : K) • Matrix.single k j 1 := by
  rw [LieRing.of_associative_ring_bracket]
  by_cases hjk : j = k <;> by_cases hli : l = i <;>
    simp [Matrix.single_mul_single_same, Matrix.single_mul_single_of_ne, hjk, hli,
      eq_zero_of_ne, sub_eq_add_neg]

/-- The `K`-linear map sending matrix unit `Matrix.single i j 1` to `E i j`. -/
noncomputable def toGlHomLinear (L : LadderSystem K V d) :
    Matrix (Fin d) (Fin d) K →ₗ[K] Module.End K V :=
  (Matrix.stdBasis K (Fin d) (Fin d)).constr K (fun p => L.E p.1 p.2)

@[simp] theorem toGlHomLinear_stdBasis (L : LadderSystem K V d) (i j : Fin d) :
    L.toGlHomLinear (Matrix.stdBasis K (Fin d) (Fin d) (i, j)) = L.E i j :=
  Basis.constr_basis _ _ _ _

lemma toGlHomLinear_single (L : LadderSystem K V d) (i j : Fin d) :
    L.toGlHomLinear (Matrix.single i j (1 : K)) = L.E i j := by
  rw [← Matrix.stdBasis_eq_single, toGlHomLinear_stdBasis]

/-- `toGlHomLinear` respects brackets. -/
lemma toGlHomLinear_lie (L : LadderSystem K V d) (x y : Matrix (Fin d) (Fin d) K) :
    L.toGlHomLinear ⁅x, y⁆ = ⁅L.toGlHomLinear x, L.toGlHomLinear y⁆ := by
  apply LinearMap.lie_apply_eq_of_lie_basis_eq (Matrix.stdBasis K (Fin d) (Fin d)) L.toGlHomLinear
  rintro ⟨i, j⟩ ⟨k, l⟩
  simp only [Matrix.stdBasis_eq_single, lie_single, map_sub, map_smul,
    toGlHomLinear_single, L.lie_E i j k l]

/-- The `gl(d)`-representation on `V` generated by a ladder system, bundled as a `LieHom`. -/
noncomputable def toGlHom (L : LadderSystem K V d) :
    Matrix (Fin d) (Fin d) K →ₗ⁅K⁆ Module.End K V :=
  { L.toGlHomLinear with map_lie' := L.toGlHomLinear_lie _ _ }

/-- `V` as a `gl(d)`-module, the `LieRingModule` instance (not global -- depends on `L`; use via
`haveI := L.toLieRingModule`). -/
@[reducible] noncomputable def toLieRingModule (L : LadderSystem K V d) :
    LieRingModule (Matrix (Fin d) (Fin d) K) V :=
  LieRingModule.compLieHom V L.toGlHom

/-- The companion `LieModule` instance. -/
lemma toLieModule (L : LadderSystem K V d) :
    @LieModule K (Matrix (Fin d) (Fin d) K) V _ _ _ _ _ L.toLieRingModule :=
  LieModule.compLieHom V L.toGlHom

/-!

## C. The number operator

-/

/-- The number operator for mode `i`, `Nᵢ ≔ Eᵢᵢ = acᵢaᵢ`. -/
def N (i : Fin d) : Module.End K V := L.E i i

/-!

### C.1. Commutation relations

-/

/-- `[Nᵢ, aⱼ] = -δᵢⱼaᵢ`. -/
lemma lie_N_a (i j : Fin d) :
    (⁅L.N i, L.a j⁆ : Module.End K V) = (-δ[i,j] : K) • L.a i := by
  show (⁅L.ac i * L.a i, L.a j⁆ : Module.End K V) = _
  rw [assoc_leibniz' (L.ac i) (L.a i) (L.a j), L.comm_a_a i j, mul_zero, zero_add]
  have h : (⁅L.ac i, L.a j⁆ : Module.End K V) = (-δ[j,i] : K) • (1 : Module.End K V) := by
    rw [← lie_skew, L.comm_a_ac j i]
    by_cases hji : j = i <;> simp [eq_zero_of_ne, hji]
  rw [h, smul_mul_assoc, one_mul, KroneckerDelta.symm i j]

/-- `[Nᵢ, acⱼ] = δᵢⱼacᵢ`. -/
lemma lie_N_ac (i j : Fin d) :
    (⁅L.N i, L.ac j⁆ : Module.End K V) = (δ[i,j] : K) • L.ac i := by
  show (⁅L.ac i * L.a i, L.ac j⁆ : Module.End K V) = _
  rw [assoc_leibniz' (L.ac i) (L.a i) (L.ac j), L.comm_a_ac i j, L.comm_ac_ac i j, zero_mul,
    add_zero]
  by_cases hij : i = j <;> simp [eq_zero_of_ne, hij]

/-- `[Nᵢ, Nⱼ] = 0`: the number operators commute among themselves. -/
lemma lie_N_N (i j : Fin d) : (⁅L.N i, L.N j⁆ : Module.End K V) = 0 := by
  rcases eq_or_ne i j with rfl | hij
  · exact lie_self _
  · show (⁅L.ac i * L.a i, L.N j⁆ : Module.End K V) = 0
    rw [assoc_leibniz' (L.ac i) (L.a i) (L.N j),
      ← lie_skew (L.a i) (L.N j), lie_N_a, ← lie_skew (L.ac i) (L.N j), lie_N_ac]
    simp [eq_zero_of_ne, Ne.symm hij]

/-!

### C.2. The total number operator

-/

/-- The total number operator, `∑ᵢNᵢ` -- the total excitation count across every mode. -/
def totalN (L : LadderSystem K V d) : Module.End K V := ∑ i, L.N i

/-- The total number operator is central in `gl(d)`: it commutes with every generator
`E i j`, not just the diagonal ones (contrast `lie_N_N`, which only says the diagonal `Nᵢ`
commute *among themselves*). Consequently any operator built from `L.totalN` alone --
in particular an *isotropic* Hamiltonian -- preserves `vacuumSpan` sector-by-sector for the same
reason `vacuumSpanLieSubmodule` does: it is `L.toGlHomLinear` applied to a central element of
`gl(d)` (the identity matrix), so it acts diagonally on the whole `gl(d)`-module structure. -/
theorem lie_totalN_E (j k : Fin d) : (⁅L.totalN, L.E j k⁆ : Module.End K V) = 0 := by
  rw [totalN, sum_lie]
  have hstep : ∀ i, (⁅L.N i, L.E j k⁆ : Module.End K V)
      = (δ[i,j] : K) • L.E i k - (δ[k,i] : K) • L.E j i := fun i => L.lie_E i i j k
  simp_rw [hstep]
  rw [Finset.sum_sub_distrib]
  have hsum1 : (∑ i : Fin d, (δ[i,j] : K) • L.E i k) = L.E j k := by
    rw [Finset.sum_eq_single j (fun i _ hij => by simp [eq_zero_of_ne hij])
      (fun h => absurd (Finset.mem_univ j) h)]
    simp
  have hsum2 : (∑ i : Fin d, (δ[k,i] : K) • L.E j i) = L.E j k := by
    rw [Finset.sum_eq_single k (fun i _ hik => by simp [eq_zero_of_ne hik.symm])
      (fun h => absurd (Finset.mem_univ k) h)]
    simp
  rw [hsum1, hsum2, sub_self]

end LadderSystem
