/-
Copyright (c) 2024 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Mathlib.LinearAlgebra.CliffordAlgebra.Basic
public import Physlib.Relativity.Fermions.Dirac.GammaMatrices
/-!
# The Clifford Algebra

This file obtains the gamma matrices in the Dirac representation from the endomorphisms
`Fermion.Dirac.gamma` and describes their relationship to the Clifford algebra.
The algebra equivalence `Fermion.Dirac.endEquivMatrix` changes their chiral coordinates
to Dirac coordinates, preserving the existing matrix entries.

## Main Definitions

- `γ0, γ1, γ2, γ3`: The four gamma matrices in the Dirac representation (4×4 complex matrices)
- `γSet`: The set of gamma matrices
- `diracForm`: The quadratic form with Minkowski signature (+,-,-,-)
  corresponding to the gamma matrices
- `diracAlgebra`: The algebra generated by the gamma matrices over ℝ
- `ofCliffordAlgebra`: The algebra homomorphism from the Clifford algebra to `diracAlgebra`

## Main Results

- `ofCliffordAlgebra_surjective`: The homomorphism `ofCliffordAlgebra` is surjective

## TODO

- Complete the isomorphism by proving injectivity of `ofCliffordAlgebra` (requires dimension theory)
- Construct the `AlgEquiv` between `CliffordAlgebra diracForm` and `diracAlgebra`

-/

@[expose] public section
TODO "Prove injectivity of ofCliffordAlgebra and construct the full isomorphism."
namespace spaceTime
open Complex Fermion.Dirac

noncomputable section diracRepresentation

/-! ## A. Dirac matrix representation -/

/-- The γ⁰ gamma matrix in the Dirac representation. -/
def γ0 : Matrix (Fin 4) (Fin 4) ℂ :=
  endEquivMatrix (Fermion.Dirac.gamma (Sum.inl 0))

/-- The γ¹ gamma matrix in the Dirac representation. -/
def γ1 : Matrix (Fin 4) (Fin 4) ℂ :=
  endEquivMatrix (Fermion.Dirac.gamma (Sum.inr 0))

/-- The γ² gamma matrix in the Dirac representation. -/
def γ2 : Matrix (Fin 4) (Fin 4) ℂ :=
  endEquivMatrix (Fermion.Dirac.gamma (Sum.inr 1))

/-- The γ³ gamma matrix in the Dirac representation. -/
def γ3 : Matrix (Fin 4) (Fin 4) ℂ :=
  endEquivMatrix (Fermion.Dirac.gamma (Sum.inr 2))

theorem _root_.Matrix.one_fin_four {α} [Zero α] [One α] :
    (1 : Matrix (Fin 4) (Fin 4) α) = !![1, 0, 0, 0; 0, 1, 0, 0; 0, 0, 1, 0; 0, 0, 0, 1] :=
  Matrix.etaExpand_eq _ |>.symm

@[simp] lemma γ0_mul_γ0 : γ0 * γ0 = 1 := by simp [γ0, ← map_mul]
@[simp] lemma γ1_mul_γ1 : γ1 * γ1 = -1 := by simp [γ1, ← map_mul]
@[simp] lemma γ2_mul_γ2 : γ2 * γ2 = -1 := by simp [γ2, ← map_mul]
@[simp] lemma γ3_mul_γ3 : γ3 * γ3 = -1 := by simp [γ3, ← map_mul]

@[simp] lemma γ1_mul_γ0 : γ1 * γ0 = -(γ0 * γ1) := by
  rw [γ1, γ0, ← map_mul, Fermion.Dirac.gamma_mul_gamma_of_ne (by decide), map_neg, map_mul]
@[simp] lemma γ2_mul_γ0 : γ2 * γ0 = -(γ0 * γ2) := by
  rw [γ2, γ0, ← map_mul, Fermion.Dirac.gamma_mul_gamma_of_ne (by decide), map_neg, map_mul]
@[simp] lemma γ3_mul_γ0 : γ3 * γ0 = -(γ0 * γ3) := by
  rw [γ3, γ0, ← map_mul, Fermion.Dirac.gamma_mul_gamma_of_ne (by decide), map_neg, map_mul]
@[simp] lemma γ2_mul_γ1 : γ2 * γ1 = -(γ1 * γ2) := by
  rw [γ2, γ1, ← map_mul, Fermion.Dirac.gamma_mul_gamma_of_ne (by decide), map_neg, map_mul]
@[simp] lemma γ3_mul_γ1 : γ3 * γ1 = -(γ1 * γ3) := by
  rw [γ3, γ1, ← map_mul, Fermion.Dirac.gamma_mul_gamma_of_ne (by decide), map_neg, map_mul]
@[simp] lemma γ3_mul_γ2 : γ3 * γ2 = -(γ2 * γ3) := by
  rw [γ3, γ2, ← map_mul, Fermion.Dirac.gamma_mul_gamma_of_ne (by decide), map_neg, map_mul]

/-- The γ⁵ gamma matrix in the Dirac representation. -/
def γ5 : Matrix (Fin 4) (Fin 4) ℂ := I • (γ0 * γ1 * γ2 * γ3)

/-- The chirality matrix is the Dirac representation of the chirality endomorphism. -/
lemma γ5_eq_endEquivMatrix : γ5 = endEquivMatrix Fermion.Dirac.gamma5 := by
  simp only [γ5, Fermion.Dirac.gamma5, map_smul, map_mul, γ0, γ1, γ2, γ3]

/-! ## B. The algebra generated by the gamma matrices -/

namespace γ

open spaceTime

/-- The subset of `Matrix (Fin 4) (Fin 4) ℂ` formed by the gamma matrices in the Dirac
representation. -/
@[simp]
def γSet : Set (Matrix (Fin 4) (Fin 4) ℂ) :=
  {endEquivMatrix (gamma i) | i : Fin 1 ⊕ Fin 3}

lemma γ_in_γSet (μ : Fin 1 ⊕ Fin 3) : endEquivMatrix (gamma μ) ∈ γSet := ⟨μ, rfl⟩

/-- The algebra generated by the gamma matrices in the Dirac representation. -/
def diracAlgebra : Subalgebra ℝ (Matrix (Fin 4) (Fin 4) ℂ) :=
  Algebra.adjoin ℝ γSet

lemma γSet_subset_diracAlgebra : γSet ⊆ diracAlgebra :=
  Algebra.subset_adjoin

lemma γ_in_diracAlgebra (μ : Fin 1 ⊕ Fin 3) : endEquivMatrix (gamma μ) ∈ diracAlgebra :=
  γSet_subset_diracAlgebra (γ_in_γSet μ)

/-- The quadratic form of the Clifford algebra corresponding to the gamma matrices. -/
@[simps!]
def diracForm : QuadraticForm ℝ (Fin 4 → ℝ) :=
  QuadraticMap.sq.comp (LinearMap.proj 0)
    - QuadraticMap.sq.comp (LinearMap.proj 1)
    - QuadraticMap.sq.comp (LinearMap.proj 2)
    - QuadraticMap.sq.comp (LinearMap.proj 3)

/-- The algebra homomorphism from the Clifford algebra over `diracForm` to the algebra
generated by the Dirac representations of the gamma endomorphisms. -/
def ofCliffordAlgebra : CliffordAlgebra diracForm →ₐ[ℝ] diracAlgebra :=
  CliffordAlgebra.lift _
    ⟨∑ i, (LinearMap.proj i).smulRight
      ⟨endEquivMatrix (gamma (finSumFinEquiv.symm i)), γ_in_diracAlgebra _⟩, fun v => by
      ext : 1
      simp only [Fin.sum_univ_four, LinearMap.add_apply, LinearMap.coe_smulRight,
        LinearMap.coe_proj, Function.eval, SetLike.mk_smul_mk, AddMemClass.mk_add_mk,
        MulMemClass.mk_mul_mk]
      change (v 0 • γ0 + v 1 • γ1 + v 2 • γ2 + v 3 • γ3) *
        (v 0 • γ0 + v 1 • γ1 + v 2 • γ2 + v 3 • γ3) = _
      simp only [mul_add, Algebra.mul_smul_comm, add_mul, Algebra.smul_mul_assoc,
        γ0_mul_γ0, γ1_mul_γ0, smul_neg,
        γ2_mul_γ0, γ3_mul_γ0, smul_add, γ1_mul_γ1, γ2_mul_γ1, γ3_mul_γ1, γ2_mul_γ2, γ3_mul_γ2,
        γ3_mul_γ3, diracForm_apply, Algebra.algebraMap_eq_smul_one, SetLike.val_smul,
        OneMemClass.coe_one]
      module⟩

/-- The Clifford generators correspond to the gamma endomorphisms in the Dirac representation.
The equivalence `finSumFinEquiv` identifies the two Lorentz index types. -/
@[simp]
lemma ofCliffordAlgebra_ι_single (i : Fin 4) (r : ℝ) :
    ofCliffordAlgebra (CliffordAlgebra.ι _ (Pi.single i r)) =
      r • ⟨endEquivMatrix (gamma (finSumFinEquiv.symm i)), γ_in_diracAlgebra _⟩ :=
  CliffordAlgebra.lift_ι_apply _ _ _ |>.trans <| Subtype.ext <| by
    simp only [LinearMap.coe_sum, LinearMap.coe_smulRight, LinearMap.coe_proj, Function.eval,
      SetLike.mk_smul_mk, Finset.sum_apply, AddSubmonoidClass.coe_finsetSum]
    rw [Finset.sum_eq_single i]
    · simp
    · intro b _ hb
      simp [Pi.single_eq_of_ne hb]
    · simp

/-! ### B.1. Surjectivity of ofCliffordAlgebra -/

/-- Each gamma matrix (as an element of diracAlgebra) is in the range of ofCliffordAlgebra. -/
lemma γ_subtype_in_range (i : Fin 1 ⊕ Fin 3) :
    ⟨endEquivMatrix (gamma i), γ_in_diracAlgebra i⟩ ∈ ofCliffordAlgebra.range := by
  use CliffordAlgebra.ι diracForm (Pi.single (finSumFinEquiv i) 1)
  simp [ofCliffordAlgebra_ι_single]

/-- Helper lemma: If a matrix is in Algebra.adjoin ℝ γSet, then its subtype is in the range. -/
private lemma mem_adjoin_imp_subtype_in_range (m : Matrix (Fin 4) (Fin 4) ℂ)
    (hm : m ∈ Algebra.adjoin ℝ γSet) : ⟨m, hm⟩ ∈ ofCliffordAlgebra.range := by
  induction hm using Algebra.adjoin_induction with
  | mem y hy =>
    -- y ∈ γSet, so y = endEquivMatrix (gamma i) for some i
    obtain ⟨i, rfl⟩ := hy
    exact γ_subtype_in_range i
  | algebraMap r =>
    -- r from ℝ
    use algebraMap ℝ _ r
    ext
    simp [Algebra.algebraMap_eq_smul_one]
  | add y z _ _ hy hz =>
    -- If y and z are in range, so is y + z
    obtain ⟨y', hy'⟩ := hy
    obtain ⟨z', hz'⟩ := hz
    use y' + z'
    ext : 1
    have hy'' : (ofCliffordAlgebra y' : Matrix (Fin 4) (Fin 4) ℂ) = y := congr_arg Subtype.val hy'
    have hz'' : (ofCliffordAlgebra z' : Matrix (Fin 4) (Fin 4) ℂ) = z := congr_arg Subtype.val hz'
    simp [hy'', hz'']
  | mul y z _ _ hy hz =>
    -- If y and z are in range, so is y * z
    obtain ⟨y', hy'⟩ := hy
    obtain ⟨z', hz'⟩ := hz
    use y' * z'
    ext : 1
    have hy'' : (ofCliffordAlgebra y' : Matrix (Fin 4) (Fin 4) ℂ) = y := congr_arg Subtype.val hy'
    have hz'' : (ofCliffordAlgebra z' : Matrix (Fin 4) (Fin 4) ℂ) = z := congr_arg Subtype.val hz'
    simp [hy'', hz'']

/-- The range of ofCliffordAlgebra equals the top subalgebra (i.e., all of diracAlgebra). -/
lemma ofCliffordAlgebra_range_eq_top : ofCliffordAlgebra.range = ⊤ := by
  rw [eq_top_iff]
  intro x _
  exact mem_adjoin_imp_subtype_in_range x.val x.property

/-- The homomorphism `ofCliffordAlgebra` is surjective. -/
theorem ofCliffordAlgebra_surjective : Function.Surjective ofCliffordAlgebra := by
  rw [← AlgHom.range_eq_top]
  exact ofCliffordAlgebra_range_eq_top

end γ

end diracRepresentation
end spaceTime
