/-
Copyright (c) 2024 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Mathlib.Analysis.Complex.Basic
public import Mathlib.Data.Matrix.Reflection
public import Mathlib.LinearAlgebra.Matrix.Trace
public import Mathlib.LinearAlgebra.CliffordAlgebra.Basic
public import Physlib.Relativity.Tensors.RealTensor.Vector.MinkowskiProduct
public import Physlib.Meta.TODO.Basic
/-!
# The Clifford Algebra

This file defines the Gamma matrices and their relationship to the Clifford algebra.

## Main Definitions

- `γ0, γ1, γ2, γ3`: The four gamma matrices in the Dirac representation (4×4 complex matrices)
- `γSet`: The set of gamma matrices
- `diracForm`: The quadratic form with Minkowski signature (+,-,-,-)
  corresponding to the gamma matrices
- `diracAlgebra`: The algebra generated by the gamma matrices over ℝ
- `ofCliffordAlgebra`: The algebra homomorphism from the Clifford algebra to `diracAlgebra`

## Main Results

- `ofCliffordAlgebra_surjective`: The homomorphism `ofCliffordAlgebra` is surjective

## TODO

- Complete the isomorphism by proving injectivity of `ofCliffordAlgebra` (requires dimension theory)
- Construct the `AlgEquiv` between `CliffordAlgebra diracForm` and `diracAlgebra`

-/

@[expose] public section
TODO "Prove injectivity of ofCliffordAlgebra and construct the full isomorphism."
namespace spaceTime
open Complex

set_option maxHeartbeats 1000000

noncomputable section diracRepresentation

/-- The γ⁰ gamma matrix in the Dirac representation. -/
def γ0 : Matrix (Fin 4) (Fin 4) ℂ :=
  !![1, 0, 0, 0; 0, 1, 0, 0; 0, 0, -1, 0; 0, 0, 0, -1]

/-- The γ¹ gamma matrix in the Dirac representation. -/
def γ1 : Matrix (Fin 4) (Fin 4) ℂ :=
  !![0, 0, 0, 1; 0, 0, 1, 0; 0, -1, 0, 0; -1, 0, 0, 0]

/-- The γ² gamma matrix in the Dirac representation. -/
def γ2 : Matrix (Fin 4) (Fin 4) ℂ :=
  !![0, 0, 0, - I; 0, 0, I, 0; 0, I, 0, 0; -I, 0, 0, 0]

/-- The γ³ gamma matrix in the Dirac representation. -/
def γ3 : Matrix (Fin 4) (Fin 4) ℂ :=
  !![0, 0, 1, 0; 0, 0, 0, -1; -1, 0, 0, 0; 0, 1, 0, 0]

theorem _root_.Matrix.one_fin_four {α} [Zero α] [One α] :
    (1 : Matrix (Fin 4) (Fin 4) α) = !![1, 0, 0, 0; 0, 1, 0, 0; 0, 0, 1, 0; 0, 0, 0, 1] :=
  Matrix.etaExpand_eq _ |>.symm

@[simp] lemma γ0_mul_γ0 : γ0 * γ0 = 1 := by simp [γ0, Matrix.one_fin_four]
@[simp] lemma γ1_mul_γ1 : γ1 * γ1 = -1 := by simp [γ1, Matrix.one_fin_four]
@[simp] lemma γ2_mul_γ2 : γ2 * γ2 = -1 := by simp [γ2, Matrix.one_fin_four]
@[simp] lemma γ3_mul_γ3 : γ3 * γ3 = -1 := by simp [γ3, Matrix.one_fin_four]

@[simp] lemma γ1_mul_γ0 : γ1 * γ0 = -(γ0 * γ1) := by simp [γ0, γ1]
@[simp] lemma γ2_mul_γ0 : γ2 * γ0 = -(γ0 * γ2) := by simp [γ0, γ2]
@[simp] lemma γ3_mul_γ0 : γ3 * γ0 = -(γ0 * γ3) := by simp [γ0, γ3]
@[simp] lemma γ2_mul_γ1 : γ2 * γ1 = -(γ1 * γ2) := by simp [γ1, γ2]
@[simp] lemma γ3_mul_γ1 : γ3 * γ1 = -(γ1 * γ3) := by simp [γ1, γ3]
@[simp] lemma γ3_mul_γ2 : γ3 * γ2 = -(γ2 * γ3) := by simp [γ2, γ3]

/-- The γ⁵ gamma matrix in the Dirac representation. -/
def γ5 : Matrix (Fin 4) (Fin 4) ℂ := I • (γ0 * γ1 * γ2 * γ3)

/-- The γ gamma matrices in the Dirac representation. -/
@[simp]
def γ : Fin 4 → Matrix (Fin 4) (Fin 4) ℂ := ![γ0, γ1, γ2, γ3]

/-- The lowered gamma matrices in the Dirac representation. -/
@[simp]
def γDown (μ : Fin 4) : Matrix (Fin 4) (Fin 4) ℂ :=
  ((minkowskiMatrix ((@finSumFinEquiv 1 3).symm μ)
    ((@finSumFinEquiv 1 3).symm μ) : ℝ) : ℂ) • γ μ

namespace γ

open spaceTime

variable (μ ν : Fin 4)

/-- The subset of `Matrix (Fin 4) (Fin 4) ℂ` formed by the gamma matrices in the Dirac
representation. -/
@[simp]
def γSet : Set (Matrix (Fin 4) (Fin 4) ℂ) := {γ i | i : Fin 4}

lemma γ_in_γSet (μ : Fin 4) : γ μ ∈ γSet := by
  simp [γSet]

/-- The algebra generated by the gamma matrices in the Dirac representation. -/
def diracAlgebra : Subalgebra ℝ (Matrix (Fin 4) (Fin 4) ℂ) :=
  Algebra.adjoin ℝ γSet

lemma γSet_subset_diracAlgebra : γSet ⊆ diracAlgebra :=
  Algebra.subset_adjoin

lemma γ_in_diracAlgebra (μ : Fin 4) : γ μ ∈ diracAlgebra :=
  γSet_subset_diracAlgebra (γ_in_γSet μ)

/-- The Clifford anticommutator identity for gamma matrices. -/
theorem gamma_anticomm (μ ν : Fin 4) :
    γ μ * γ ν + γ ν * γ μ =
      (2 * ((minkowskiMatrix
        ((@finSumFinEquiv 1 3).symm μ)
        ((@finSumFinEquiv 1 3).symm ν)) : ℝ) : ℂ) •
        (1 : Matrix (Fin 4) (Fin 4) ℂ) := by
  fin_cases μ <;> fin_cases ν <;>
    simp [γ, γ0, γ1, γ2, γ3, Matrix.one_fin_four]

/-! ### Dirac Slash Operators -/

namespace Slash

/-- Components of a Lorentz vector in the `γ0,γ1,γ2,γ3` ordering. -/
def coord (k : Lorentz.Vector 3) : Fin 4 → ℂ :=
  ![(k (Sum.inl 0) : ℂ), (k (Sum.inr 0) : ℂ), (k (Sum.inr 1) : ℂ), (k (Sum.inr 2) : ℂ)]

/-- The Dirac slash of a Lorentz vector. -/
def slash (k : Lorentz.Vector 3) : Matrix (Fin 4) (Fin 4) ℂ :=
  ∑ μ, coord k μ • γ μ

/-- Product of slash factors, in left-to-right order. -/
def slashProd (ks : List (Lorentz.Vector 3)) : Matrix (Fin 4) (Fin 4) ℂ :=
  (ks.map slash).prod

@[simp]
lemma slash_zero : slash (0 : Lorentz.Vector 3) = 0 := by
  ext i j
  fin_cases i <;> fin_cases j <;> simp [slash, coord, Fin.sum_univ_four]

@[simp]
lemma slash_add (k l : Lorentz.Vector 3) : slash (k + l) = slash k + slash l := by
  ext i j
  fin_cases i <;> fin_cases j
  · simp [slash, coord, Fin.sum_univ_four]
    ring_nf

@[simp]
lemma slash_smul (c : ℝ) (k : Lorentz.Vector 3) : slash (c • k) = c • slash k := by
  ext i j
  fin_cases i <;> fin_cases j
  · simp [slash, coord, Fin.sum_univ_four, mul_assoc]
    ring_nf

@[simp]
lemma slashProd_nil : slashProd [] = 1 := rfl

@[simp]
lemma slashProd_cons (k : Lorentz.Vector 3) (ks : List (Lorentz.Vector 3)) :
    slashProd (k :: ks) = slash k * slashProd ks := rfl

/-- Off-diagonal Minkowski entries vanish after pulling indices back to `Fin 4`. -/
theorem minkowski_pull_diag (μ ν : Fin 4) :
    minkowskiMatrix ((@finSumFinEquiv 1 3).symm μ)
      ((@finSumFinEquiv 1 3).symm ν) =
      if μ = ν then
        minkowskiMatrix ((@finSumFinEquiv 1 3).symm μ)
          ((@finSumFinEquiv 1 3).symm μ)
      else 0 := by
  by_cases h : μ = ν
  · subst h
    simp
  · have h' : (@finSumFinEquiv 1 3).symm μ ≠
              (@finSumFinEquiv 1 3).symm ν := by
      intro hEq
      apply h
      exact (@finSumFinEquiv 1 3).injective
        (by simpa using congrArg (@finSumFinEquiv 1 3) hEq)
    simp [h, minkowskiMatrix.off_diag_zero h']

/-- Double contraction against the Minkowski matrix keeps only diagonal terms. -/
theorem sum_mul_metric_offdiag_vanish (f : Fin 4 → Fin 4 → ℂ) :
    ∑ μ, ∑ ν, ((minkowskiMatrix ((@finSumFinEquiv 1 3).symm μ)
      ((@finSumFinEquiv 1 3).symm ν) : ℝ) : ℂ) * f μ ν =
      ∑ μ, ((minkowskiMatrix ((@finSumFinEquiv 1 3).symm μ)
        ((@finSumFinEquiv 1 3).symm μ) : ℝ) : ℂ) * f μ μ := by
  simp [Fin.sum_univ_four, minkowski_pull_diag, mul_assoc, mul_left_comm, mul_comm]

/-- Contracting `coord` components with the Minkowski metric gives the Minkowski product. -/
theorem coord_metric_contract (a b : Lorentz.Vector 3) :
    ∑ μ, ((minkowskiMatrix ((@finSumFinEquiv 1 3).symm μ)
      ((@finSumFinEquiv 1 3).symm μ) : ℝ) : ℂ) *
      (coord a μ * coord b μ) =
      ((Lorentz.Vector.minkowskiProduct a b : ℝ) : ℂ) := by
  simp [coord, Fin.sum_univ_four, Lorentz.Vector.minkowskiProduct_toCoord, minkowskiMatrix.inl_0_inl_0,
    minkowskiMatrix.inr_i_inr_i, Complex.ofReal_neg, sub_eq_add_neg, mul_assoc, mul_left_comm,
    mul_comm]
  ring_nf

/-- Clifford anticommutator for slashed Lorentz vectors. -/
theorem slash_mul_add_mul_slash (a b : Lorentz.Vector 3) :
    slash a * slash b + slash b * slash a =
      ((2 * (Lorentz.Vector.minkowskiProduct a b : ℝ)) : ℂ) •
        (1 : Matrix (Fin 4) (Fin 4) ℂ) := by
  calc
    slash a * slash b + slash b * slash a
        = ∑ μ, ∑ ν, (coord a μ * coord b ν) • (γ μ * γ ν + γ ν * γ μ) := by
          simp [slash, mul_add, add_mul, Finset.sum_mul, Finset.mul_sum, smul_add, smul_mul_assoc,
            mul_smul_comm, mul_assoc, mul_left_comm, mul_comm, Finset.sum_add_distrib]
    _ = ∑ μ, ∑ ν,
          ((2 * ((minkowskiMatrix ((@finSumFinEquiv 1 3).symm μ)
            ((@finSumFinEquiv 1 3).symm ν) : ℝ) : ℂ)) *
            (coord a μ * coord b ν)) • (1 : Matrix (Fin 4) (Fin 4) ℂ) := by
          simp [gamma_anticomm, smul_smul, mul_assoc, mul_left_comm, mul_comm]
    _ = (∑ μ, ∑ ν,
          (2 * ((minkowskiMatrix ((@finSumFinEquiv 1 3).symm μ)
            ((@finSumFinEquiv 1 3).symm ν) : ℝ) : ℂ)) *
            (coord a μ * coord b ν)) • (1 : Matrix (Fin 4) (Fin 4) ℂ) := by
          simp [Finset.sum_smul]
    _ = ((2 : ℂ) * (∑ μ, ∑ ν,
          ((minkowskiMatrix ((@finSumFinEquiv 1 3).symm μ)
            ((@finSumFinEquiv 1 3).symm ν) : ℝ) : ℂ) *
            (coord a μ * coord b ν))) • (1 : Matrix (Fin 4) (Fin 4) ℂ) := by
          congr 1
          simp [Finset.mul_sum, Finset.sum_mul, mul_assoc, mul_left_comm, mul_comm]
    _ = ((2 : ℂ) * ((Lorentz.Vector.minkowskiProduct a b : ℝ) : ℂ)) •
          (1 : Matrix (Fin 4) (Fin 4) ℂ) := by
          congr 1
          rw [sum_mul_metric_offdiag_vanish]
          simpa [mul_assoc, mul_left_comm, mul_comm] using coord_metric_contract a b
    _ = ((2 * (Lorentz.Vector.minkowskiProduct a b : ℝ)) : ℂ) •
          (1 : Matrix (Fin 4) (Fin 4) ℂ) := by
          norm_num

end Slash

/-! ### Trace Identities -/

namespace Trace

/-- The `γ5 γ^μ γ^ν γ^ρ γ^σ` trace equals `4 i` times the Lorentz Levi-Civita symbol. -/
theorem trace_γ5_mul_γ_mul_γ_mul_γ_mul_γ (μ ν ρ σ : Fin 4) :
    Matrix.trace (γ5 * γ μ * γ ν * γ ρ * γ σ) =
      (4 * I) * (realLorentzTensor.leviCivita4Int μ ν ρ σ : ℂ) := by
  fin_cases μ <;> fin_cases ν <;> fin_cases ρ <;> fin_cases σ
  · norm_num [realLorentzTensor.leviCivita4Int, γ5, γ, γ0, γ1, γ2, γ3, Matrix.trace,
      Fin.sum_univ_four]

@[simp]
lemma trace_γ (μ : Fin 4) : Matrix.trace (γ μ) = 0 := by
  fin_cases μ <;> simp [Matrix.trace, Fin.sum_univ_four, γ, γ0, γ1, γ2, γ3]

@[simp]
lemma slash_trace (k : Lorentz.Vector 3) : Matrix.trace (Slash.slash k) = 0 := by
  simp [Slash.slash]

/-- Two-slash trace identity: `Tr[/a /b] = 4 a·b`. -/
theorem slash_mul_slash_trace (a b : Lorentz.Vector 3) :
  Matrix.trace (Slash.slash a * Slash.slash b) =
    (4 * (Lorentz.Vector.minkowskiProduct a b : ℝ) : ℂ) := by
  have hI2 : (I : ℂ) ^ 2 = -1 := by simpa [pow_two] using Complex.I_sq
  simp [Slash.slash, Matrix.trace, Fin.sum_univ_four, Fin.sum_univ_three,
    γ0, γ1, γ2, γ3, Lorentz.Vector.minkowskiProduct_toCoord, hI2]
  ring_nf

/-- `γ5` with two slashes has vanishing trace. -/
theorem gamma5_slash_mul_slash_trace (a b : Lorentz.Vector 3) :
  Matrix.trace (γ5 * Slash.slash a * Slash.slash b) = 0 := by
  simp [γ5, Slash.slash, Matrix.trace, Fin.sum_univ_four, Fin.sum_univ_three,
    γ0, γ1, γ2, γ3, Complex.I_sq, pow_two]
  ring_nf

/-- Cubic odd slash trace identity. -/
theorem slash_mul_slash_mul_slash_trace
  (k l m : Lorentz.Vector 3) :
  Matrix.trace (Slash.slash k * Slash.slash l * Slash.slash m) = 0 := by
  simp only [Slash.slash, add_mul, mul_add, Matrix.trace_add, Matrix.trace_neg, Matrix.trace_smul,
    map_add, map_mul, map_neg, map_sub]
  simp [Matrix.trace, Fin.sum_univ_four, γ0, γ1, γ2, γ3]

/-- The contracted identity `γ_μ γ^μ = 4 I`. -/
theorem gammaDown_mul_gamma :
    ∑ μ, γDown μ * γ μ = (4 : ℂ) • (1 : Matrix (Fin 4) (Fin 4) ℂ) := by
  ext i j <;> fin_cases i <;> fin_cases j <;>
    simp [γDown, γ, γ0, γ1, γ2, γ3, Matrix.one_fin_four]
  ring_nf

/-- The contracted identity `γ_μ /a γ^μ = -2 /a`. -/
theorem gammaDown_mul_slash_mul_gamma (a : Lorentz.Vector 3) :
    ∑ μ, γDown μ * Slash.slash a * γ μ = (-2 : ℂ) • Slash.slash a := by
  ext i j <;> fin_cases i <;> fin_cases j <;>
    simp [γDown, Slash.slash, Slash.coord, γ, γ0, γ1, γ2, γ3,
      Matrix.mul_assoc, Fin.sum_univ_four, Fin.sum_univ_three]
  ring_nf

/-- The contracted identity `γ_μ /a /b γ^μ = 4(a·b) I`. -/
theorem gammaDown_mul_slash_mul_slash_mul_gamma (a b : Lorentz.Vector 3) :
    ∑ μ, γDown μ * Slash.slash a * Slash.slash b * γ μ =
      ((4 * (Lorentz.Vector.minkowskiProduct a b : ℝ)) : ℂ) •
        (1 : Matrix (Fin 4) (Fin 4) ℂ) := by
  have hI2 : (I : ℂ) ^ 2 = -1 := by simpa [pow_two] using Complex.I_sq
  have hI4 : (I : ℂ) ^ 4 = 1 := by
    calc
      (I : ℂ) ^ 4 = ((I : ℂ) ^ 2) ^ 2 := by ring
      _ = (-1 : ℂ) ^ 2 := by simp [hI2]
      _ = 1 := by norm_num
  ext i j <;> fin_cases i <;> fin_cases j <;>
    simp [γDown, Slash.slash, Slash.coord, γ, γ0, γ1, γ2, γ3,
      Matrix.mul_assoc, Fin.sum_univ_four, Fin.sum_univ_three,
      Lorentz.Vector.minkowskiProduct_toCoord, hI2, hI4]
  ring_nf

/-- The contracted identity `γ_μ /a /b /c γ^μ = -2 /c /b /a`. -/
theorem gammaDown_mul_slash_mul_slash_mul_slash_mul_gamma
    (a b c : Lorentz.Vector 3) :
    ∑ μ, γDown μ * Slash.slash a * Slash.slash b * Slash.slash c * γ μ =
      (-2 : ℂ) • (Slash.slash c * Slash.slash b * Slash.slash a) := by
  have hI2 : (I : ℂ) ^ 2 = -1 := by simpa [pow_two] using Complex.I_sq
  have hI4 : (I : ℂ) ^ 4 = 1 := by
    calc
      (I : ℂ) ^ 4 = ((I : ℂ) ^ 2) ^ 2 := by ring
      _ = (-1 : ℂ) ^ 2 := by simp [hI2]
      _ = 1 := by norm_num
  ext i j <;> fin_cases i <;> fin_cases j <;>
    simp [γDown, Slash.slash, Slash.coord, γ, γ0, γ1, γ2, γ3,
      Matrix.mul_assoc, Fin.sum_univ_four, Fin.sum_univ_three, hI2, hI4]
  ring_nf

/-- Four-slash trace identity:
`Tr[ /a /b /c /d ] = 4 (a·b c·d - a·c b·d + a·d b·c)`. -/
theorem slash_mul_slash_mul_slash_mul_slash_trace
  (a b c d : Lorentz.Vector 3) :
  Matrix.trace (Slash.slash a * Slash.slash b * Slash.slash c * Slash.slash d) =
    (4 * (((Lorentz.Vector.minkowskiProduct a b : ℝ) *
      (Lorentz.Vector.minkowskiProduct c d : ℝ)) -
      ((Lorentz.Vector.minkowskiProduct a c : ℝ) *
        (Lorentz.Vector.minkowskiProduct b d : ℝ)) +
      ((Lorentz.Vector.minkowskiProduct a d : ℝ) *
        (Lorentz.Vector.minkowskiProduct b c : ℝ))) : ℂ) := by
  have hI2 : (I : ℂ) ^ 2 = -1 := by simpa [pow_two] using Complex.I_sq
  have hI4 : (I : ℂ) ^ 4 = 1 := by
    calc
      (I : ℂ) ^ 4 = ((I : ℂ) ^ 2) ^ 2 := by ring
      _ = (-1 : ℂ) ^ 2 := by simp [hI2]
      _ = 1 := by norm_num
  simp [Slash.slash, Matrix.trace, Fin.sum_univ_four, Fin.sum_univ_three,
    γ0, γ1, γ2, γ3, Lorentz.Vector.minkowskiProduct_toCoord, hI2, hI4]
  ring_nf
  simp [Slash.coord, hI2, hI4, sub_eq_add_neg]
  ring_nf

private def reverseConj : Matrix (Fin 4) (Fin 4) ℂ := γ1 * γ3

private def reverseConjInv : Matrix (Fin 4) (Fin 4) ℂ := γ3 * γ1

@[simp] private lemma reverseConj_mul_reverseConjInv : reverseConj * reverseConjInv = 1 := by
  ext i j <;> fin_cases i <;> fin_cases j <;>
    simp [reverseConj, reverseConjInv, γ1, γ3, Matrix.one_fin_four]

@[simp] private lemma reverseConjInv_mul_reverseConj : reverseConjInv * reverseConj = 1 := by
  ext i j <;> fin_cases i <;> fin_cases j <;>
    simp [reverseConj, reverseConjInv, γ1, γ3, Matrix.one_fin_four]

@[simp] private lemma reverseConj_mul_γ_transpose_mul_reverseConjInv (μ : Fin 4) :
  reverseConj * Matrix.transpose (γ μ) * reverseConjInv = γ μ := by
  ext i j
  fin_cases μ <;> fin_cases i <;> fin_cases j <;>
    simp [reverseConj, reverseConjInv, γ, γ0, γ1, γ2, γ3]

@[simp] private lemma reverseConj_mul_slash_transpose_mul_reverseConjInv (k : Lorentz.Vector 3) :
  reverseConj * Matrix.transpose (Slash.slash k) * reverseConjInv = Slash.slash k := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Slash.slash, Slash.coord, reverseConj, reverseConjInv, γ, γ0, γ1, γ2, γ3,
      Matrix.mul_apply, Fin.sum_univ_four, Fin.sum_univ_three]
  ring_nf

private lemma reverseConj_mul_transpose_mul_reverseConjInv_eq_slashProd_reverse
    (ks : List (Lorentz.Vector 3)) :
  reverseConj * Matrix.transpose (Slash.slashProd ks) * reverseConjInv = Slash.slashProd ks.reverse := by
  induction ks using List.reverseRecOn with
  | nil =>
      simp [Slash.slashProd]
  | append_singleton ks k ih =>
      calc
        reverseConj * Matrix.transpose (Slash.slashProd (ks ++ [k])) * reverseConjInv
          = reverseConj * Matrix.transpose (Slash.slashProd ks * Slash.slash k) * reverseConjInv := by
              simp [Slash.slashProd, List.map_append, List.prod_append]
        _ = reverseConj * (Matrix.transpose (Slash.slash k) * Matrix.transpose (Slash.slashProd ks)) * reverseConjInv := by
              simp [Matrix.transpose_mul]
        _ = (reverseConj * Matrix.transpose (Slash.slash k) * reverseConjInv) *
            (reverseConj * Matrix.transpose (Slash.slashProd ks) * reverseConjInv) := by
              simp [mul_assoc]
        _ = Slash.slash k * Slash.slashProd ks.reverse := by simpa [ih]
        _ = Slash.slashProd ((ks ++ [k]).reverse) := by simp [Slash.slashProd]

/-- Reversing a slash-product list leaves the trace unchanged:
`Tr[ /a /b /c /d ] = Tr[ /d /c /b /a ]`. -/
theorem slashProd_trace_reverse (ks : List (Lorentz.Vector 3)) :
    Matrix.trace (Slash.slashProd ks) = Matrix.trace (Slash.slashProd ks.reverse) := by
  calc
    Matrix.trace (Slash.slashProd ks)
        = Matrix.trace (Matrix.transpose (Slash.slashProd ks)) := by
            simpa using (Matrix.trace_transpose (Slash.slashProd ks)).symm
    _ = Matrix.trace (reverseConj * Matrix.transpose (Slash.slashProd ks) * reverseConjInv) := by
          symm
          rw [Matrix.trace_mul_cycle (A := reverseConj) (B := Matrix.transpose (Slash.slashProd ks))
            (C := reverseConjInv)]
          simp [mul_assoc]
    _ = Matrix.trace (Slash.slashProd ks.reverse) := by
          simp [reverseConj_mul_transpose_mul_reverseConjInv_eq_slashProd_reverse]

/-- Reversing the order of four slash factors leaves the trace unchanged:
`Tr[ /a /b /c /d ] = Tr[ /d /c /b /a ]`. -/
theorem slash_mul_slash_mul_slash_mul_slash_trace_reverse
  (a b c d : Lorentz.Vector 3) :
  Matrix.trace (Slash.slash a * Slash.slash b * Slash.slash c * Slash.slash d) =
    Matrix.trace (Slash.slash d * Slash.slash c * Slash.slash b * Slash.slash a) := by
  simpa [Slash.slashProd, Matrix.mul_assoc] using
    (slashProd_trace_reverse [a, b, c, d])

/-- `γ5` four-slash trace identity in terms of the tensor-level Lorentz Levi-Civita symbol:
`Tr[ γ5 /a /b /c /d ] = 4i ε^{μνρσ} a_μ b_ν c_ρ d_σ`. -/
theorem gamma5_slash_mul_slash_mul_slash_mul_slash_trace
  (a b c d : Lorentz.Vector 3) :
  Matrix.trace (γ5 * Slash.slash a * Slash.slash b * Slash.slash c * Slash.slash d) =
    (4 * I) *
      (∑ μ, ∑ ν, ∑ ρ, ∑ σ,
        (realLorentzTensor.leviCivita4Int μ ν ρ σ : ℂ) *
          Slash.coord a μ * Slash.coord b ν * Slash.coord c ρ * Slash.coord d σ) := by
  simp [Slash.slash, Slash.coord, γ, Fin.sum_univ_four,
    mul_add, add_mul, mul_assoc, Matrix.trace_add, Matrix.trace_smul,
    Finset.mul_sum, Finset.sum_mul, trace_γ5_mul_γ_mul_γ_mul_γ_mul_γ]
  ring_nf



end Trace

/-- The quadratic form of the clifford algebra corresponding to the `γ` matrices. -/
@[simps!]
def diracForm : QuadraticForm ℝ (Fin 4 → ℝ) :=
  QuadraticMap.sq.comp (LinearMap.proj 0)
    - QuadraticMap.sq.comp (LinearMap.proj 1)
    - QuadraticMap.sq.comp (LinearMap.proj 2)
    - QuadraticMap.sq.comp (LinearMap.proj 3)

/-- The injection from the clifford algebra over `diracForm` into the algebra generated by the
`γ` matrices. -/
def ofCliffordAlgebra : CliffordAlgebra diracForm →ₐ[ℝ] diracAlgebra :=
  CliffordAlgebra.lift _
    ⟨∑ i, (LinearMap.proj i).smulRight ⟨γ i, γ_in_diracAlgebra _⟩, fun v => by
      ext : 1
      simp only [γ, Fin.sum_univ_four, Fin.isValue, Matrix.cons_val_zero, Matrix.cons_val_one,
        Matrix.cons_val, LinearMap.add_apply, LinearMap.coe_smulRight, LinearMap.coe_proj,
        Function.eval, SetLike.mk_smul_mk, AddMemClass.mk_add_mk, MulMemClass.mk_mul_mk, mul_add,
        Algebra.mul_smul_comm, add_mul, Algebra.smul_mul_assoc, γ0_mul_γ0, γ1_mul_γ0, smul_neg,
        γ2_mul_γ0, γ3_mul_γ0, smul_add, γ1_mul_γ1, γ2_mul_γ1, γ3_mul_γ1, γ2_mul_γ2, γ3_mul_γ2,
        γ3_mul_γ3, diracForm_apply, Algebra.algebraMap_eq_smul_one, SetLike.val_smul,
        OneMemClass.coe_one]
      module⟩

/-- The generators of the clifford algebra correspond to the elements `γ`. -/
@[simp]
lemma ofCliffordAlgebra_ι_single (i : Fin 4) (r : ℝ) :
    ofCliffordAlgebra (CliffordAlgebra.ι _ (Pi.single i r)) = r • ⟨γ i, γ_in_diracAlgebra _⟩ :=
  CliffordAlgebra.lift_ι_apply _ _ _ |>.trans <| Subtype.ext <| by
    simp only [γ, LinearMap.coe_sum, LinearMap.coe_smulRight, LinearMap.coe_proj, Function.eval,
      SetLike.mk_smul_mk, Finset.sum_apply, AddSubmonoidClass.coe_finsetSum]
    rw [Finset.sum_eq_single i]
    · simp
    · intro b _ hb
      simp [Pi.single_eq_of_ne hb]
    · simp

/-! ### Surjectivity of ofCliffordAlgebra -/

/-- Each gamma matrix (as an element of diracAlgebra) is in the range of ofCliffordAlgebra. -/
lemma γ_subtype_in_range (i : Fin 4) :
    ⟨γ i, γ_in_diracAlgebra i⟩ ∈ ofCliffordAlgebra.range := by
  use CliffordAlgebra.ι diracForm (Pi.single i 1)
  simp [ofCliffordAlgebra_ι_single]

/-- Helper lemma: If a matrix is in Algebra.adjoin ℝ γSet, then its subtype is in the range. -/
private lemma mem_adjoin_imp_subtype_in_range (m : Matrix (Fin 4) (Fin 4) ℂ)
    (hm : m ∈ Algebra.adjoin ℝ γSet) : ⟨m, hm⟩ ∈ ofCliffordAlgebra.range := by
  induction hm using Algebra.adjoin_induction with
  | mem y hy =>
    -- y ∈ γSet, so y = γ i for some i
    obtain ⟨i, rfl⟩ := hy
    exact γ_subtype_in_range i
  | algebraMap r =>
    -- r from ℝ
    use algebraMap ℝ _ r
    ext
    simp [Algebra.algebraMap_eq_smul_one]
  | add y z _ _ hy hz =>
    -- If y and z are in range, so is y + z
    obtain ⟨y', hy'⟩ := hy
    obtain ⟨z', hz'⟩ := hz
    use y' + z'
    ext : 1
    have hy'' : (ofCliffordAlgebra y' : Matrix (Fin 4) (Fin 4) ℂ) = y := congr_arg Subtype.val hy'
    have hz'' : (ofCliffordAlgebra z' : Matrix (Fin 4) (Fin 4) ℂ) = z := congr_arg Subtype.val hz'
    simp [hy'', hz'']
  | mul y z _ _ hy hz =>
    -- If y and z are in range, so is y * z
    obtain ⟨y', hy'⟩ := hy
    obtain ⟨z', hz'⟩ := hz
    use y' * z'
    ext : 1
    have hy'' : (ofCliffordAlgebra y' : Matrix (Fin 4) (Fin 4) ℂ) = y := congr_arg Subtype.val hy'
    have hz'' : (ofCliffordAlgebra z' : Matrix (Fin 4) (Fin 4) ℂ) = z := congr_arg Subtype.val hz'
    simp [hy'', hz'']

/-- The range of ofCliffordAlgebra equals the top subalgebra (i.e., all of diracAlgebra). -/
lemma ofCliffordAlgebra_range_eq_top : ofCliffordAlgebra.range = ⊤ := by
  rw [eq_top_iff]
  intro x _
  exact mem_adjoin_imp_subtype_in_range x.val x.property

/-- The homomorphism `ofCliffordAlgebra` is surjective. -/
theorem ofCliffordAlgebra_surjective : Function.Surjective ofCliffordAlgebra := by
  rw [← AlgHom.range_eq_top]
  exact ofCliffordAlgebra_range_eq_top

end γ

end diracRepresentation
end spaceTime
