/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import Mathlib.Geometry.Convex.Cone.TensorProduct
public import Mathlib.Algebra.Order.Module.PositiveLinearMap
public import PhyslibAlpha.AlgebraicFramework.OrderUnit.Basic

/-!
# Composite order-unit systems

## i. Overview

The underlying vector space of a composite of systems `E₁` and `E₂` is the algebraic tensor
product `E₁ ⊗[ℝ] E₂`. Its order is extra structure: in general, the orders on the factors do not
determine a unique positive cone on the tensor product.

Mathlib supplies the two canonical extremal choices. The **minimal tensor cone** is generated by
positive elementary tensors. The **maximal tensor cone** consists of the tensors on which every
pair of positive linear functionals takes a nonnegative value. Every compatible tensor cone lies
between these two.

`TensorCone E₁ E₂` bundles precisely such an intermediate choice. This makes it possible to state
results for an unspecified composite model, while `TensorCone.minimal` and `TensorCone.maximal`
recover the two extremal models. The construction uses Mathlib's `PointedCone` API throughout;
despite its name, a `PointedCone` here means a cone containing zero, bundled as an `ℝ≥0`-submodule.

## ii. Key definitions and results

- `minTensorCone E₁ E₂`: the cone generated by positive elementary tensors.
- `maxTensorCone E₁ E₂`: the dual-defined maximal tensor cone.
- `TensorCone E₁ E₂`: a choice of cone between `minTensorCone` and `maxTensorCone`.
- `TensorCone.tmul_mem`: every compatible tensor cone contains positive elementary tensors.
- `TensorCone.tmulRight`, `TensorCone.tmulLeft`: the canonical positive tensor embeddings.
- `exists_eq_sub_minTensorCone`: the minimal tensor cone is reproducing when both factors have
  order units.

## iii. Table of contents

- A. The extremal tensor cones
- B. Compatible intermediate tensor cones
- C. Positive elementary tensors
- D. Canonical tensor embeddings
- E. The minimal tensor cone is reproducing

-/

@[expose] public section

open scoped NNReal TensorProduct

variable (E₁ E₂ : Type*)
  [AddCommGroup E₁] [PartialOrder E₁] [IsOrderedAddMonoid E₁] [Module ℝ E₁] [PosSMulMono ℝ E₁]
  [AddCommGroup E₂] [PartialOrder E₂] [IsOrderedAddMonoid E₂] [Module ℝ E₂] [PosSMulMono ℝ E₂]

/-!

## A. The extremal tensor cones
-/

/-- The minimal tensor cone of two ordered real vector spaces: the cone generated by elementary
tensors `x ⊗ₜ y` with `0 ≤ x` and `0 ≤ y`. -/
noncomputable def minTensorCone : PointedCone ℝ (E₁ ⊗[ℝ] E₂) :=
  PointedCone.minTensorProduct (PointedCone.positive ℝ E₁) (PointedCone.positive ℝ E₂)

/-- The maximal tensor cone of two ordered real vector spaces: the tensors pairing nonnegatively
with every elementary tensor of positive linear functionals. -/
noncomputable def maxTensorCone : PointedCone ℝ (E₁ ⊗[ℝ] E₂) :=
  PointedCone.maxTensorProduct (PointedCone.positive ℝ E₁) (PointedCone.positive ℝ E₂)

/-- The minimal tensor cone is contained in the maximal tensor cone. -/
lemma minTensorCone_le_maxTensorCone : minTensorCone E₁ E₂ ≤ maxTensorCone E₁ E₂ :=
  PointedCone.minTensorProduct_le_maxTensorProduct _ _

/-!

## B. Compatible intermediate tensor cones
-/

/-- A compatible positive cone for a composite system: a tensor cone containing the minimal
tensor cone and contained in the maximal tensor cone.

The two inequalities express the usual compatibility conditions. The lower bound makes every
positive elementary tensor positive in the composite. The upper bound says that every pair of
positive functionals on the factors remains positive on the composite. -/
structure TensorCone where
  /-- The chosen positive cone on the tensor-product vector space. -/
  toPointedCone : PointedCone ℝ (E₁ ⊗[ℝ] E₂)
  /-- Every positive elementary tensor belongs to the chosen cone. -/
  min_le : minTensorCone E₁ E₂ ≤ toPointedCone
  /-- Every element of the chosen cone is positive against product positive functionals. -/
  le_max : toPointedCone ≤ maxTensorCone E₁ E₂

namespace TensorCone

instance : Coe (TensorCone E₁ E₂) (PointedCone ℝ (E₁ ⊗[ℝ] E₂)) := ⟨toPointedCone⟩

/-- A pair of positive functionals evaluates nonnegatively on every element of a compatible
composite cone.  This is the defining operational content of the maximal tensor bound. -/
lemma productFunctional_nonneg (C : TensorCone E₁ E₂) (φ : PositiveLinearMap ℝ E₁ ℝ)
    (ψ : PositiveLinearMap ℝ E₂ ℝ)
    {z : E₁ ⊗[ℝ] E₂} (hz : z ∈ C.toPointedCone) :
    0 ≤ TensorProduct.dualDistrib ℝ E₁ E₂ (φ.toLinearMap ⊗ₜ[ℝ] ψ.toLinearMap) z := by
  have hzmax : z ∈ maxTensorCone E₁ E₂ := C.le_max hz
  change z ∈ PointedCone.maxTensorProduct (PointedCone.positive ℝ E₁)
    (PointedCone.positive ℝ E₂) at hzmax
  rw [PointedCone.mem_maxTensorProduct] at hzmax
  exact hzmax φ.toLinearMap (fun x hx => φ.map_nonneg hx)
    ψ.toLinearMap (fun y hy => ψ.map_nonneg hy)

variable {F₁ F₂ : Type*}
  [AddCommGroup F₁] [PartialOrder F₁] [IsOrderedAddMonoid F₁] [Module ℝ F₁]
  [PosSMulMono ℝ F₁]
  [AddCommGroup F₂] [PartialOrder F₂] [IsOrderedAddMonoid F₂] [Module ℝ F₂]
  [PosSMulMono ℝ F₂]

/-- The image of the positive cone under a positive linear map remains in the positive cone. -/
lemma positiveCone_map_le (φ : PositiveLinearMap ℝ E₁ F₁) :
    (PointedCone.positive ℝ E₁).map φ.toLinearMap ≤ PointedCone.positive ℝ F₁ := by
  rintro _ ⟨x, hx, rfl⟩
  exact φ.map_nonneg hx

/-- Tensor products of positive maps preserve the minimal tensor cone. -/
lemma minTensorCone_map_le (φ : PositiveLinearMap ℝ E₁ F₁)
    (ψ : PositiveLinearMap ℝ E₂ F₂) :
    (minTensorCone E₁ E₂).map (TensorProduct.map φ.toLinearMap ψ.toLinearMap) ≤
      minTensorCone F₁ F₂ :=
  (PointedCone.minTensorProduct_map_le φ.toLinearMap ψ.toLinearMap _ _).trans
    (PointedCone.minTensorProduct_mono
      (positiveCone_map_le (E₁ := E₁) (F₁ := F₁) φ)
      (positiveCone_map_le (E₁ := E₂) (F₁ := F₂) ψ))

/-- Tensor products of positive maps preserve the maximal tensor cone. -/
lemma maxTensorCone_map_le (φ : PositiveLinearMap ℝ E₁ F₁)
    (ψ : PositiveLinearMap ℝ E₂ F₂) :
    (maxTensorCone E₁ E₂).map (TensorProduct.map φ.toLinearMap ψ.toLinearMap) ≤
      maxTensorCone F₁ F₂ :=
  (PointedCone.maxTensorProduct_map_le φ.toLinearMap ψ.toLinearMap _ _).trans
    (PointedCone.maxTensorProduct_mono
      (positiveCone_map_le (E₁ := E₁) (F₁ := F₁) φ)
      (positiveCone_map_le (E₁ := E₂) (F₁ := F₂) ψ))

/-- The elements of a compatible tensor cone form an `ℝ≥0`-module. This bridges Mathlib's
generic nonnegative-scalar subtype with `NNReal`, which this order-unit API uses throughout. -/
instance instModuleNNReal (C : TensorCone E₁ E₂) : Module ℝ≥0 C.toPointedCone where
  smul c x := ⟨(c : ℝ) • (x : E₁ ⊗[ℝ] E₂), C.toPointedCone.smul_mem c.2 x.2⟩
  one_smul _ := Subtype.ext (one_smul ℝ _)
  mul_smul c d _ := Subtype.ext (mul_smul (c : ℝ) (d : ℝ) _)
  smul_zero _ := Subtype.ext (smul_zero _)
  smul_add c _ _ := Subtype.ext (smul_add (c : ℝ) _ _)
  add_smul c d _ := Subtype.ext (by push_cast; exact add_smul (c : ℝ) (d : ℝ) _)
  zero_smul _ := Subtype.ext (by push_cast; exact zero_smul ℝ _)

@[ext]
lemma ext {C D : TensorCone E₁ E₂} (h : C.toPointedCone = D.toPointedCone) : C = D := by
  cases C
  cases D
  simp_all

/-- Compatible tensor cones are ordered by inclusion of their underlying cones. -/
instance instPartialOrder : PartialOrder (TensorCone E₁ E₂) where
  le C D := C.toPointedCone ≤ D.toPointedCone
  le_refl _ := le_rfl
  le_trans _ _ _ := le_trans
  le_antisymm C D hCD hDC := TensorCone.ext (E₁ := E₁) (E₂ := E₂) (le_antisymm hCD hDC)

/-- The minimal compatible tensor cone. -/
noncomputable def minimal : TensorCone E₁ E₂ where
  toPointedCone := minTensorCone E₁ E₂
  min_le := le_rfl
  le_max := minTensorCone_le_maxTensorCone E₁ E₂

/-- The maximal compatible tensor cone. -/
noncomputable def maximal : TensorCone E₁ E₂ where
  toPointedCone := maxTensorCone E₁ E₂
  min_le := minTensorCone_le_maxTensorCone E₁ E₂
  le_max := le_rfl

@[simp]
lemma minimal_toPointedCone : (minimal E₁ E₂).toPointedCone = minTensorCone E₁ E₂ := rfl

@[simp]
lemma maximal_toPointedCone : (maximal E₁ E₂).toPointedCone = maxTensorCone E₁ E₂ := rfl

@[simp]
lemma minimal_le (C : TensorCone E₁ E₂) : minimal E₁ E₂ ≤ C := C.min_le

@[simp]
lemma le_maximal (C : TensorCone E₁ E₂) : C ≤ maximal E₁ E₂ := C.le_max

/-!

## C. Positive elementary tensors
-/

/-- A tensor of positive elements belongs to the minimal tensor cone. -/
lemma tmul_mem_minimal {x : E₁} {y : E₂} (hx : 0 ≤ x) (hy : 0 ≤ y) :
    x ⊗ₜ[ℝ] y ∈ minTensorCone E₁ E₂ :=
  PointedCone.tmul_mem_minTensorProduct
    (by simpa only [PointedCone.mem_positive] using hx)
    (by simpa only [PointedCone.mem_positive] using hy)

/-- Every compatible tensor cone contains every tensor of positive elements. -/
lemma tmul_mem (C : TensorCone E₁ E₂) {x : E₁} {y : E₂} (hx : 0 ≤ x) (hy : 0 ≤ y) :
    x ⊗ₜ[ℝ] y ∈ C.toPointedCone :=
  C.min_le (tmul_mem_minimal E₁ E₂ hx hy)

/-!

## D. Canonical tensor embeddings
-/

variable {E₁ E₂}

/-- For fixed `0 ≤ y₀`, tensoring on the right with `y₀` maps the positive cone of `E₁`
`ℝ≥0`-linearly into any compatible tensor cone. -/
def tmulRight (C : TensorCone E₁ E₂) {y₀ : E₂} (hy₀ : 0 ≤ y₀) :
    PosCone E₁ →ₗ[ℝ≥0] C.toPointedCone where
  toFun x := ⟨(x : E₁) ⊗ₜ[ℝ] y₀, tmul_mem E₁ E₂ C x.2 hy₀⟩
  map_add' x y := by
    apply Subtype.ext
    exact TensorProduct.add_tmul _ _ _
  map_smul' c x := by
    apply Subtype.ext
    exact (TensorProduct.smul_tmul' (c : ℝ) (x : E₁) y₀).symm

@[simp]
lemma tmulRight_apply (C : TensorCone E₁ E₂) {y₀ : E₂} (hy₀ : 0 ≤ y₀) (x : PosCone E₁) :
    (C.tmulRight hy₀ x : E₁ ⊗[ℝ] E₂) = (x : E₁) ⊗ₜ[ℝ] y₀ := rfl

/-- For fixed `0 ≤ x₀`, tensoring on the left with `x₀` maps the positive cone of `E₂`
`ℝ≥0`-linearly into any compatible tensor cone. -/
def tmulLeft (C : TensorCone E₁ E₂) {x₀ : E₁} (hx₀ : 0 ≤ x₀) :
    PosCone E₂ →ₗ[ℝ≥0] C.toPointedCone where
  toFun y := ⟨x₀ ⊗ₜ[ℝ] (y : E₂), tmul_mem E₁ E₂ C hx₀ y.2⟩
  map_add' x y := by
    apply Subtype.ext
    exact TensorProduct.tmul_add _ _ _
  map_smul' c y := by
    apply Subtype.ext
    exact TensorProduct.tmul_smul _ _ _

@[simp]
lemma tmulLeft_apply (C : TensorCone E₁ E₂) {x₀ : E₁} (hx₀ : 0 ≤ x₀) (y : PosCone E₂) :
    (C.tmulLeft hx₀ y : E₁ ⊗[ℝ] E₂) = x₀ ⊗ₜ[ℝ] (y : E₂) := rfl

end TensorCone

/-!

## E. The minimal tensor cone is reproducing

An order unit makes each factor's positive cone reproducing: every vector is a difference of two
positive vectors. Expanding both factors of an elementary tensor then shows that the minimal
tensor cone is reproducing as well. No multiplication, star operation, or C⋆-algebraic Jordan
decomposition is needed.
-/

variable {E₁ E₂} [One E₁] [IsOrderUnit E₁] [One E₂] [IsOrderUnit E₂]

/-- Every element of the tensor product is a difference of two elements of the minimal tensor
cone when both factors have order units. -/
lemma exists_eq_sub_minTensorCone (t : E₁ ⊗[ℝ] E₂) :
    ∃ tp tn : minTensorCone E₁ E₂,
      t = (tp : E₁ ⊗[ℝ] E₂) - (tn : E₁ ⊗[ℝ] E₂) := by
  induction t using TensorProduct.induction_on with
  | zero => exact ⟨0, 0, by simp⟩
  | tmul x y =>
      obtain ⟨xp, xn, hxp, hxn, hx⟩ := IsOrderUnit.exists_eq_sub_nonneg x
      obtain ⟨yp, yn, hyp, hyn, hy⟩ := IsOrderUnit.exists_eq_sub_nonneg y
      refine ⟨⟨xp ⊗ₜ[ℝ] yp + xn ⊗ₜ[ℝ] yn,
          add_mem (TensorCone.tmul_mem_minimal E₁ E₂ hxp hyp)
            (TensorCone.tmul_mem_minimal E₁ E₂ hxn hyn)⟩,
        ⟨xp ⊗ₜ[ℝ] yn + xn ⊗ₜ[ℝ] yp,
          add_mem (TensorCone.tmul_mem_minimal E₁ E₂ hxp hyn)
            (TensorCone.tmul_mem_minimal E₁ E₂ hxn hyp)⟩, ?_⟩
      rw [hx, hy]
      simp only [TensorProduct.sub_tmul, TensorProduct.tmul_sub]
      abel
  | add t₁ t₂ h₁ h₂ =>
      obtain ⟨ap, an, ha⟩ := h₁
      obtain ⟨bp, bn, hb⟩ := h₂
      refine ⟨ap + bp, an + bn, ?_⟩
      change t₁ + t₂ = ((ap : E₁ ⊗[ℝ] E₂) + bp) - ((an : E₁ ⊗[ℝ] E₂) + bn)
      rw [ha, hb]
      abel
