/-
Copyright (c) 2026 Tom Ole Diem. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Tom Ole Diem
-/
module

public import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Commute
public import PhyslibAlpha.AlgebraicFramework.CStarAlgebra.Jordan

/-!
# Continuous functional calculus for Cstar Jordan observables

This is the realization-specific CFC boundary.  An abstract JB-algebra does not yet have the real
Gelfand/complexification theorem needed to construct its one-generator calculus; see
`JordanOrderUnit/JB/GeneratedByOne/CFC_AUDIT.md`.  A self-adjoint element of a Cstar algebra does
have Mathlib's real isometric CFC.  This file simply packages that existing construction with
codomain `selfAdjoint A`, so its output is a Jordan observable by construction.

The definition is deliberately not imported by abstract Jordan/JB files.
-/

@[expose] public section

namespace JB

variable {A : Type*} [CStarAlgebra A]

open scoped selfAdjoint

/-- The real continuous functional calculus of a self-adjoint Cstar element, packaged into the
Jordan algebra of observables.  This is a specialization of Mathlib's `cfcHom`, not a second CFC
construction.  Its codomain is deliberately a linear map: the observable Jordan product is
nonassociative globally, so an `AlgHom` into it would state the wrong structure. -/
noncomputable def jordanCfc (a : selfAdjoint A) :
    C(spectrum ℝ (a : A), ℝ) →ₗ[ℝ] selfAdjoint A where
  toFun f := ⟨cfcHom a.property f, cfcHom_predicate a.property f⟩
  map_add' f g := by
    ext
    exact map_add (cfcHom a.property) f g
  map_smul' c f := by
    ext
    exact map_smul (cfcHom a.property) c f

/-- The coordinate function is sent to the original Jordan observable. -/
@[simp]
theorem jordanCfc_id (a : selfAdjoint A) :
    jordanCfc a ((ContinuousMap.id ℝ).restrict (spectrum ℝ (a : A))) = a := by
  ext
  exact cfcHom_id (p := IsSelfAdjoint) a.property

/-- The concrete Jordan CFC is isometric. -/
theorem norm_jordanCfc (a : selfAdjoint A) (f : C(spectrum ℝ (a : A), ℝ)) :
    ‖jordanCfc a f‖ = ‖f‖ := by
  change ‖cfcHom (p := IsSelfAdjoint) a.property f‖ = ‖f‖
  exact norm_cfcHom (p := IsSelfAdjoint) (a : A) f a.property

/-- Although `jordanCfc` is packaged as a linear map, its values commute because its source is
commutative.  Hence it preserves the Jordan product exactly. -/
theorem jordanCfc_mul (a : selfAdjoint A) (f g : C(spectrum ℝ (a : A), ℝ)) :
    jordanCfc a (f * g) = jordanCfc a f * jordanCfc a g := by
  have hcomm : cfcHom (p := IsSelfAdjoint) a.property f *
      cfcHom (p := IsSelfAdjoint) a.property g =
      cfcHom (p := IsSelfAdjoint) a.property g * cfcHom (p := IsSelfAdjoint) a.property f := by
    rw [← map_mul, ← map_mul, mul_comm]
  ext
  rw [selfAdjoint.mul_def, selfAdjoint.val_jordanMul]
  change cfcHom (p := IsSelfAdjoint) a.property (f * g) =
    (2 : ℝ)⁻¹ • (cfcHom (p := IsSelfAdjoint) a.property f *
      cfcHom (p := IsSelfAdjoint) a.property g +
      cfcHom (p := IsSelfAdjoint) a.property g * cfcHom (p := IsSelfAdjoint) a.property f)
  rw [map_mul, ← hcomm, ← two_smul ℝ (cfcHom (p := IsSelfAdjoint) a.property f *
    cfcHom (p := IsSelfAdjoint) a.property g), smul_smul, inv_mul_cancel₀ (by norm_num), one_smul]

/-- Every continuous function of an observable commutes with that observable in its ambient Cstar
algebra.  Thus the one-variable calculus lands in the compatible Jordan fragment generated by
the observable. -/
theorem jordanCfc_commute (a : selfAdjoint A) (f : C(spectrum ℝ (a : A), ℝ)) :
    Commute ((jordanCfc a f : selfAdjoint A) : A) (a : A) := by
  change Commute (cfcHom (p := IsSelfAdjoint) a.property f) (a : A)
  apply Commute.cfcHom (p := IsSelfAdjoint) a.property (Commute.refl _)
  simpa only [a.property.star_eq] using (Commute.refl (a : A))

section Order

variable [PartialOrder A] [StarOrderedRing A]

/-- A nonnegative continuous function of a Jordan observable is nonnegative. -/
theorem jordanCfc_nonneg (a : selfAdjoint A) {f : C(spectrum ℝ (a : A), ℝ)} (hf : 0 ≤ f) :
    0 ≤ jordanCfc a f := by
  change (0 : A) ≤ cfcHom (p := IsSelfAdjoint) a.property f
  have h := cfcHom_mono (p := IsSelfAdjoint) a.property
    (f := (0 : C(spectrum ℝ (a : A), ℝ))) (g := f) hf
  simpa using h

/-- The concrete Jordan continuous functional calculus is order-preserving. -/
theorem jordanCfc_monotone (a : selfAdjoint A) : Monotone (jordanCfc a) := by
  intro f g hfg
  change cfcHom (p := IsSelfAdjoint) a.property f ≤ cfcHom (p := IsSelfAdjoint) a.property g
  exact cfcHom_mono (p := IsSelfAdjoint) a.property hfg

end Order

end JB
