/-
Copyright (c) 2025 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Mathematics.OneParameterSubgroups.Unitary
public import Physlib.Meta.TODO.Basic
public import Physlib.QuantumMechanics.PlanckConstant
/-!

# Finite-dimensional quantum systems

A `FiniteTarget` consists of a finite-dimensional Hilbert space together with a self-adjoint
Hamiltonian. Its Hamiltonian determines a unitary time evolution through Stone's correspondence.

Physical examples of such systems include:
- Spin systems.
- Tight binding chains.

-/

@[expose] public section

open Constants Module

namespace QuantumMechanics

/-- A finite-dimensional quantum system with a self-adjoint Hamiltonian. -/
structure FiniteTarget (H : Type*) [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [CompleteSpace H] [FiniteDimensional ℂ H] (n : ℕ) where
  /-- The Hilbert space has dimension `n`. -/
  hdim: Module.finrank ℂ H = n
  /-- The Hamiltonian. -/
  Ham : H →L[ℂ] H
  /-- The Hamiltonian is self-adjoint. -/
  Ham_selfAdjoint: IsSelfAdjoint Ham

namespace FiniteTarget
variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  [FiniteDimensional ℂ H] -- a Hilbert Space with finite dimension
variable {n : ℕ} (A : FiniteTarget H n)

/-- The unitary time evolution generated by the Hamiltonian of `A`. -/
noncomputable def unitaryTimeEvolution : UnitaryOneParameterGroup H :=
  UnitaryOneParameterGroup.ofSelfAdjoint (A := ((ℏ : ℂ)⁻¹) • A.Ham) (by
    have hℏself : IsSelfAdjoint (ℏ : ℂ) := by
      rw [isSelfAdjoint_iff, Complex.star_def, Complex.conj_ofReal]
    exact hℏself.inv₀.smul A.Ham_selfAdjoint)

/-- The generator of time evolution is the Hamiltonian divided by `ℏ`. -/
@[simp]
lemma unitaryTimeEvolution_generator :
    A.unitaryTimeEvolution.generator = ((ℏ : ℂ)⁻¹) • A.Ham := by
  apply Eq.symm
  apply UnitaryOneParameterGroup.generator_unique
  intro t
  rw [unitaryTimeEvolution, UnitaryOneParameterGroup.ofSelfAdjoint_apply]

/-- The operator implementing the time evolution of `A` at time `t`. -/
noncomputable def timeEvolution (t : ℝ) : H →L[ℂ] H := A.unitaryTimeEvolution t

@[simp] lemma timeEvolution_eq_exp (t : ℝ) :
    A.timeEvolution t = NormedSpace.exp ((-(t : ℂ) * Complex.I / ℏ) • A.Ham) := by
  rw [timeEvolution, UnitaryOneParameterGroup.apply_eq_exp_generator,
    unitaryTimeEvolution_generator, smul_smul]
  congr 1

/-- The matrix of the time-evolution operator at time `t` in the basis `b`. -/
noncomputable def timeEvolutionMatrix (t : ℝ) (b : Basis (Fin n) ℂ H) :
  Matrix (Fin n) (Fin n) ℂ :=
  LinearMap.toMatrix b b (A.timeEvolution t).toLinearMap

/-- The matrix of the time-evolution operator in a chosen basis indexed by `Fin n`. -/
noncomputable def timeEvolutionMatrixStandard (t : ℝ) :
  Matrix (Fin n) (Fin n) ℂ :=
  let b : Basis (Fin n) ℂ H := Module.finBasisOfFinrankEq ℂ H A.hdim
  timeEvolutionMatrix A t b

TODO "Define a smooth structure on `FiniteTarget`."

end FiniteTarget

end QuantumMechanics
